### ISSUE TITLE
Maintenance mode - RSS table update stuck

### ISSUE THREAD

**Issue by artscreen** [mylar3/mylar3#1018]
Stuck at RSS table update overnight in maintenance mode, killed, restarted, gets stuck at the same spot.

**Comment by evilhero** [comment]
Please follow the issue template.

Even in maintenance mode there are logs that we need to see.

**Comment by artscreen** [comment]
How can I pull logs/carepackage if I cant get out of maintenance mode?

**Comment by evilhero** [comment]
Just kill mylar. The logs are in your logs directory in the root of the Mylar install. Pastebin the last portion from stratuo to the point where it locks

**Comment by artscreen** [comment]
25-Jan-2022 17:08:16 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar_4/Mylar.py", line 449, in <module>
    main()
  File "/opt/mylar_4/Mylar.py", line 315, in main
    restart_method = ur.update_db()
  File "/opt/mylar_4/mylar/maintenance.py", line 507, in update_db
    filelist = flc.listFiles()
  File "/opt/mylar_4/mylar/filechecker.py", line 117, in listFiles
    runresults = self.parseit(self.dir, self.file)
  File "/opt/mylar_4/mylar/filechecker.py", line 905, in parseit
    'position':      split_file.index(new_issuenumber, yearposition),
UnboundLocalError: local variable 'new_issuenumber' referenced before assignment

**Comment by evilhero** [comment]
Ok, we're missing some commication here. I need to see the full log, from startup. Not just the error, as that doesn't help as that's a huge module that covers an even larger set. 

Start mylar with the ``-v`` switch to enable verbose logging. Let mylar run and wait for it to lock up. Stop mylar. Get the mylar.log file that's generated and put that file somewhere for me to grab in its entirety - whether dropbox, mega, w/e. If you want to email directly to me, you can do that too - but in order to really figure out what's happening and help you, I need to see that entire log.

**Comment by evilhero** [comment]
Update your version of mylar - fix is now in that should let the update complete.

Sorry for the delay!

**Comment by artscreen** [comment]
that did it.  I had started it up verbose but for whatever reason, the rss update was super slow, had been running for 3 days without reaching the halfway point.  Dit a git pull and restarted again and it went pretty quickly and finished this time.  
Thanks
