### ISSUE TITLE
Where to GetComics downloads get stored?

### ISSUE THREAD

**Issue by thewindupboy** [mylar3/mylar3#1034]
**Describe the bug**
Sometimes a comic gets pulled from GetComics, but stays as 'snatched'.  Can you tell me where those comics end up?  Just trying to figure out whats happening.

**CarePackage**
On the confi
[carepackage.zip](https://github.com/mylar3/mylar3/files/7964740/carepackage.zip)
g page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Branch / commit: [e.g. Dev/38aksi1]

**Additional information**
Add any other information about the problem here.

**Comment by CDarwin7** [comment]
The "Snatched" status is one of more curious of all the concepts in Mylar. From what I can tell, Snatched status is when Mylar finds the comic during its search and downloads the comic. It is then stored in /config/mylar/cache/{Comic Series Title}. The next step would be the Post-Processing rules kick in, where the comic's metadata is applied, renamed and copied/moved into its proper folder. For whatever reason, something goes wrong with Post-Processing and the comic is stuck in Snatched. You can see the file in the /config/mylar/cache/ folder. Usually, going into Manage Comics, then click on the double arrow circle under Options, the one when you hover over it says 'Retry the Same Download Again' For me, that usually then gets the whole process to go through and it winds up where it should.

**Comment by evilhero** [comment]
@thewindupboy DDL downloads generally go to your cache folder that's within the mylar directory. If you specified a different location using the ``ddl_location`` value in the config.ini, then they would get dropped into the location specified therein.

@CDarwin7 not to correct you, but ...I'm gonna correct you just a little bit.

``Snatched`` is when Mylar grabs the nzb/torrent and sends it to your respective client. With DDL, ``Snatched`` means that it was sent to the queue to be downloaded as there is no external client for DDL.

Only DDL downloads get stored directly in your cache folder. When Mylar starts metatagging items, then the issues gets moved from their respective download location (sab/nzbget/torrents/etc) into the cache folder whereby they are metatagged and then moved to their series folders.

Just because a DDL is ``Snatched`` doesn't mean it was succesfully completed  - DDL has loads of timeout issues due to the site getting bombarded by users, so it's not unusual for DDL downloads to fail. In which case they stay in a 'Snatched' status (cause they never completed), and the files remain in the cache folder (in case you click on Resume download it will try to restart from where it left off instead of starting at the beginning of the download). You can use the ``Manage`` tab / ``Manage DDL`` to see what the current DDL is, the status of other ones, restart or resume existing downloads, etc.

DDL also has the wonderful added benefit of having different filenames than what the Mylar client is expecting (due to Mylar having to parse the details from the webpage, and not knowing what the filename is actually going to be until the download actually starts). So in these cases where the names are different and Mylar can't parse them to determine what they are, it doesn't initiate post-processing on them.

These DDL issues should be resolved in the next python3-dev to master merge as it tries to assign the relevant issueid directly to the download which seems to fix the various naming problems.

**Comment by thewindupboy** [comment]
Thank you both, I appreciate it!

**Comment by CDarwin7** [comment]
Mr. Hero, you are our hero. By all means please and thank you for the correction. 

And thank you for the explanation about snatched, especially about how the DDL file name changes from search to download, that makes perfect sense from what I see happen in a great many instances. As does the timeout issue. Awesome to hear some of these issues are getting fixes in the short term. 

And by the way, love the project. I have Mylar setup for my workflow for several months now. After a fair bit of fine tuning and trial and error, it's now humming for me. It's adapted more to my workflow than I've had to adapt to it.. And that's after a long period of configuration, failures, successes, workarounds etc. I love firing it up for the first time in a couple of days, or right after release day and seeing what's new. I've got it paired with Komga. It's a dream.
