### ISSUE TITLE
Heavy Metal Magazine

### ISSUE THREAD

**Issue by macbean101** [mylar3/mylar3#1041]
Mylar doesn't appear to recognize the numbering used for Heavy Metal Magazine.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/8002338/carepackage.zip)

Xubuntu 20.04 Host
Docker 20.10.12
Mylar v0.6.3

Mylar won't import Heavy Metal Magazine regardless of numbering scheme used:
Here's what is using in the destination folder:  Heavy Metal Magazine 202003 (2020).cbz

Heavy Metal Magazine 202108 (2021).cbr
Heavy Metal Magazine #202108 (2021).cbr
Heavy Metal Magazine #309 (2021).cbr
Heavy Metal Magazine 309 (2021).cbr

I knew the 3-4 items wouldn't work as these are name issue names not issue #s but I wanted to try it nonetheless.

I thought I saw earlier references (2 of them) to this issue but could not find them when searching.  I think the last person said adding # worked for them but it does not for me.  

EDIT:  gave it some thought and checked something, sure enough it was the prior version where this issue was seen.  this is why searching here didn't find anything.  But the issue below is pretty much exactly what I'm seeing but without it suddenly working.  

https://github.com/evilhero/mylar/issues/553

**Comment by evilhero** [comment]
The problem  is the numbering convention is different between the pullist and what CV has - so the issues will never match up properly which is one of the safety checks (an ongoing series should have weekly pull data, or else it's not ongoing). So back in the original version, we didn't have various saftey checks for the pull matching - which caused alot of incorrect matches, etc. In mylar3, we added in a bunch of saftey checks to ensure that it's post-processing the correct issue to the correct series, and in this case, because the issue numbers are different (the pull looks like it's tracking by the #309 as opposed to #202108) it will never match up correctly.

So post-processing them won't currently work (I'll have to look into it, but that's a huge mess when the numbering is different between the 2 systems) - but they will get recognised if you drop them into the series folders and then do a ReCheck Files. Once they've been detected (so they're in a Downloaded status) you can do a manual metatag on each of the new issues and that will write the metatagging information as well as rename things according to your file format. It's not  the most ideal, or automatic way to do things, but that will at least get them into the system with metadata until I can figure out a way to link all of these things together...

**Comment by macbean101** [comment]
Makes perfect sense.  Thanks.
