### ISSUE TITLE
Mylar crashes during Update  v0.6.4

### ISSUE THREAD

**Issue by Galardin** [mylar3/mylar3#1049]
**Describe the bug**
Updating from Mylar Version v0.6.3 & pressing the Update button Mylar starts updating, but crashes during the process.

**CarePackage**
Not possible since Mylar wont start

Do not paste from the command shell.
language detected as non-English (de_DE). Forcing specific logging module - errors WILL NOT be captured in the logs
Initializing startup sequence....
Traceback (most recent call last):
  File "mylar.py", line 449, in <module>
    main()
  File "mylar.py", line 248, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "c:\Mylar3\mylar\__init__.py", line 204, in initialize
    CONFIG = cc.read(startup=True)
  File "c:\Mylar3\mylar\config.py", line 573, in read
    bcheck = cc.backup_files(cfg=True, dbs=False, backupinfo=backupinfo)
  File "c:\Mylar3\mylar\maintenance.py", line 370, in backup_files
    logger.info('Attempting to backup %s...' % cf)
  File "c:\Mylar3\mylar\logger.py", line 172, in info
    if mylar.LOG_LEVEL > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Environment (please complete the following information):**
Windows 10
Updating from Mylar Version v0.6.3

Thanks for any help

**Comment by evilhero** [comment]
(This seems to be only affecting users that run a non-English language)

Start Mylar with the ``-v`` switch to bypass the logging error.

You'll be brought into the maintenance mode screen where it will perform the update. It's possible you might not even see the update screen if you have not used RSS within Mylar.

When it's complete, you'll get another traceback error that will say something pertaining to ``[MAINTENANCE-MODE][DB-CONVERSION][CLEANUP] Cleaning up...``. At that point the update has completed, but the error stops the reboot process.

Forcibly shutdown Mylar. Then start it up as per normal (without the ``-v`` switch most likely), and you'll be good to go thereafter. 

The fix(es) for both of these are currently in py3-dev, but because of 0.6.4 we have to wait a few days prior to merging again.

**Comment by Galardin** [comment]
Thank you very much, this worked for me! :)
