### ISSUE TITLE
Mylar failing to add new series

### ISSUE THREAD

**Issue by LusiphurTemps** [mylar3/mylar3#1054]
**Describe the bug**
Mylar3 is not adding any new series. This was working on Friday.

If I choose a series via search. Click on the add button it starts the process. If I then go to the series it is stuck on the Comic Information being loaded bit with a spinning circle (currently 45 mins). I have tried this a couple of times now.

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Branch / commit: [e.g. Dev/38aksi1] 
[carepackage.zip](https://github.com/mylar3/mylar3/files/8055425/carepackage.zip)

Master 0.64
**Additional information**
Add any other information about the problem here.

**Comment by LusiphurTemps** [comment]
I cut it over to the development branch and I am seeing the same issue. It is just not doing any comic related updates.

For example, I hit refresh on the first comic in my database and that now shows in light blue on the main screen and has been sitting like that for an hour.

No Tasks show as running.

**Comment by evilhero** [comment]
hyena_pool is a remote mount I'm guessing. You have enforce_permissions enabled which is  a huge no for remote locations as it's next to impossible to properly enforce remotely. You probably need to turn off enforce permissions and let your OS handle it. 

You also have your folder monitor running every minute on the same 0-day pack. And you don't have torrents enabled, so there's no reason to keep on monitoring it. Literally the second it finishes checking the folder it starts up again - so your logs roll over almost immediately due to the size of the packs your checking every minute.

There nothing wrong with CV, and no problems adding series on either branch. The ca r that you  an flip branches and still have the same error probably is an indicator of something amiss in you setup somewhere.

**Comment by LusiphurTemps** [comment]
I have made both those changes and restarted Mylar. I also cut back the monitoring for downloads to 10 minutes.

It is still showing that one series as stuck trying to update and I cannot add new series. This was working fine on Friday with that old set up and with no intervention on my part.

**Comment by LusiphurTemps** [comment]
I should also point out I migrated everything from the old version (Python 2) to the new version (Python 3) during the week, last week. I was able to add and update series after that. It only stopped working yesterday.
When I look, all of my series have no cover image etc and as I say if I hit update on a series  it just gives the spinning circle. Note the spinning circle behaviour persists through a restart of Mylar.

**Comment by evilhero** [comment]
Yeah regardless if it's been that long there's something in your setup that is causing the problem at hand as adding series, CV works for everyone else atm, so whatever it is seems to be isolated to your setup. 

Maybe turn off Folder Monitor temporarily, restart mylar and try to add a series. When it doesn't add, generate a new carepackage and paste that so that the logs can capture the error (it wasn't captured at all in the last package). 

Some other config inconsistencies (that may help) :
- You have your cache folder location set to ``~/cache`` which would could certainly cause some path issues with the way paths are conjoined in mylar - it would be best to use the full path or set it to ``None`` and then cache folder is created under your mylar program root directory.

- There is no development branch, which is what your ``git_branch`` is set to use (it's ``python3-dev `` in mylar3).

-``locmove`` is set to ``True``, which it should not be once you've done your db moving - I'm guessing it was just never auto-reset for some reason, but that should be set to ``False``.

**Comment by fcimeson** [comment]
The new "Add this Comic" button is sketchy for me:
- I have to reload to see if was added.
- Even after waiting a long time, it sometimes doesn't add and I have to repeat.
- The old system of jumping to the library link worked better for me.
