### ISSUE TITLE
On-the-fly changes sans restart

### ISSUE THREAD

**Issue by CDarwin7** [mylar3/mylar3#1061]
**Describe the request**
Mylar3 should be able to update options changes on the fly and not require restarting the application. Also, make clear UI changes when the option has been changed. Very confusing right now if/when  the option has been updated. If on the fly updates is implemented, please inform the user the change was successful or there was an error right there in the UI. Right now we have to look in the STDOUTPUT/Logs

**How did you come up with the idea?**
changing even the simplest update seems to require a restart. Frustration

**Environment (please complete the following information):**
 - OS: Docker
 - Branch / commit:[v0.6.3] 

**Additional information**
Add any other information about the request here.

**Comment by evilhero** [comment]
Frustration is having to answer the same thing repeatedly: github issues are for bugs - this is NOT a bug, this is your experience with Mylar. The forums are for these types of questions. 

FYI: Mylar does have a popup that displays when a UI settings change are made successfully or in error. It also shows updates almost immediately when config settings have been changed.

Having to restart the application hasn't been required since the beginning of the og mylar, and even then it was only for webserver changes.

I don't know what you're doing that requires a restart, but maybe you're not using the program right.

If you want to hate on Mylar (on Valentine's day, like really), no one is forcing you to use the program.  However, I'll be considerate and offer you some advice that you should consider next time (or at least prior to having a rant on a github repo issue tracker because you're pissed off about something) : treat others the way you want to be treated. 

If you want some actual help maybe provide some insight as to the pages that don't work, where you're having to restart, or whatever the frick it is that you're trying to do when said problems occur. 

evil / out.

**Comment by CDarwin7** [comment]
I thought this was Valentines Day not April Fools. Are you being serious? I took time to make a thoughtful request to improve a program I love and use everyday, where it says is the appropriate place to make the request. I re-read what I wrote I thought you must have replied to wrong message for a moment. There is not one ounce of hate in that message directed at either you or the project. I had much respect for you, Mr. Hero, as you always help people who need help with Mylar, and I've been trying to answer a question here and there myself trying to help. I'm a business analyst by trade and write software requirements, so when I was using Mylar yesterday and thought of something that could improve Mylar, I wanted to give back both to you and the project.Have a look, it literally says when you click on New Issue...two buttons, one for bug one for Feature Request.

![image](https://user-images.githubusercontent.com/57640874/153984650-b4ddebb7-287e-4486-8601-a4e7d43c2793.png)

Next, you say you don't have to restart Mylar. Great! May I suggest we then remove the bit next to the Save button. It reads:
![image](https://user-images.githubusercontent.com/57640874/153985134-827b8d37-72e0-4adb-ba2c-96f70c2eb870.png)
I can enter it into your Bug tracker if you'd like. Should I file it as a feature request or a bug?
I've been screwing around with my setting trying to setup some features I've never used before, and sometimes I'll put away Mylar, but lately I've got a real good workflow going. I'm amazed how much developement goes into Mylar and there are always new features . The notification screen is really nice. So again, no hate was directed at you, Chief Dev. Nothing but love for the project, and you had always inspired and been admired by me. 

I appreciate the offer at the end, but I think I'll try and figure it out on my own.. You've got a short fuse right now for some reason, it's not pleasant. I worked all day and come back to a message that's borderline hostile over nothing. I work with a bunch of people that really get under each others skins and I have to manage them, they say some pretty awful stuff! Coming home to the My computer, my mylar and my comics is something  look forward to and not be triggered by over literally trying to help.

**Comment by CDarwin7** [comment]
whopps, 2nd screenshot should be;

![image](https://user-images.githubusercontent.com/57640874/153986137-10dfdd4b-7c1d-4e23-a2c6-2381addc2d2a.png)

**Comment by evilhero** [comment]
Look I'm not going to get into semantics about things - it's neither here nor there. Could I have been nicer? sure. Could you have been more detailed in your explanation ? sure. At the end of the day it doesn't matter, and I have enough on my plate as it is. You have people to manage at work, I have a gazillion kids to watch at home - we each have different perspectives on life.

Like I said before - you provided no insight as to where and why you were encountering your problems. I have no problems helping people nor explaining to them how things might need to be done to accomplish their workflows using the program. I do have a problem with people wanting to be hand-held for every little thing, or reporting false information / bugs that then trickle down to other people thinking the software is completely broken when in fact it's usually not (unless I intentionally break things). While you may not be in either categories, if I put you in the 2nd category then that's obviously on me and I apologise.

I get your inspection of the bug/feature aspect, however, if you look on the main github page - it clearly states therein that the github issue tracker should only be used for issues / feature requests: 
![ypwujwzs](https://user-images.githubusercontent.com/909424/153988032-644ff065-8e2f-4577-b75a-b93b31824766.png)
I get that most people don't like to read the wiki, or anything like where it's situated - but aside from the warning there as well as being reiterated in the wiki itself, you're not the only person to make the mistake to post herein.

The Web Interface screen you posted is just that - it states that Web Interface changes require a restart - nothing about any other options in the configuration. The Web Interface tab is clearly labelled within the configuration page, so any changes on that specific tab would need to have Mylar restarted for the changes to take full effect. You can't change the IP/Port of the server without having to restart the server so it can use the new settings. You can't change the interface from default to carbon without having some weird css overlays when flipping between pages. There are reasons why it says "Web Interface changes requires a restart to take effect" and not "All changes require a restart to take effect."

If you can provide shots / proof or something concrete as to which pages you're having problems with or what's not working then that's a bug and it can stay open. Otherwise, it should be closed as it's not really a feature request if it's already present within the application.

**Comment by CDarwin7** [comment]
THanks for the thoughtful reply, very much appreciated. Apology more than accepted. Understand fully about misinformation and how things trickle down and become wildly bent out of proportion. I'll be more care in future, sorry about that. In regards to my issues, I'll close this issue and do some more reading. If I need help I'll reach out in the appropriate manner. Thank you sir!
