### ISSUE TITLE
Issue Post Processing 'Killadelphia' .. all other series post process fine.

### ISSUE THREAD

**Issue by LusiphurTemps** [mylar3/mylar3#1069]
**Describe the bug**
This series will not post-process. It snatches fine but just sits at snatched status even though the files are where they should be and correctly named. All other series work fine.

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.03
 - Branch / commit:  python3-dev, [8cf60d5dd2c36dc9c8ef6739919078eda611126e]
[carepackage(1).zip](https://github.com/mylar3/mylar3/files/8119426/carepackage.1.zip)

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
It's actually one of those fringe exceptions - the series is an Ongoing series that was on hiatus until recently it looks like. So, atm at least, Mylar thinks the series is Ended as there is no new issue information available on CV. However the pull knows that's there's a new issue coming out this week (I think it's this week) and so it's indicating the series is Ongoing. The Ongoing pull flag is making mylar do an Ongoing-series check against an Ended series, and as such, the data doesn't line up and it won't post-process things.

However, that doesn't fix things atm. If you enable the ``Forcibly Mark as Continuing`` option in the Edit Settings tab of the given series it will be able to bypass the pull-checks / ongoing aspect and be able to post-process the issues thereafter.

As an aside, this will resolve itself when the new issue gets posted to CV and then Mylar can update the dates so that the series is marked as being a Continuing series (it will do this automatically). However, I'm going to still going to try to figure out the best way to accommodate this scenario (there are more than one series coming out of an extended hiatus that this would also apply to),

**Comment by LusiphurTemps** [comment]
Thanks. That did the trick.
