### ISSUE TITLE
Unknown Version

### ISSUE THREAD

**Issue by wraith1385** [mylar3/mylar3#1090]
Just installed new on ubuntu server and I am getting "You're running an unknown version of Mylar. [Update] or [Close]" A git status in the folder shows that I am on master and up to date with the branch.

Care package attached.

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Branch / commit: master / 4d2666d781629771e9170f2f41f9520e22eba8f3

[carepackage.zip](https://github.com/mylar3/mylar3/files/8202505/carepackage.zip)

**Comment by evilhero** [comment]
Just merged up dev into master - the version updates / fixes / etc are in the latest version as of a few minutes ago (v0.6.5), and should fix the problems you're experiencing.

**Comment by wraith1385** [comment]
I downloaded the new version and while I am no longer getting the popup about being on the unknown version,  it still says "[None]" under Version on the settings information page.

**Comment by wraith1385** [comment]
New care package in case it's needed.
[carepackage.zip](https://github.com/mylar3/mylar3/files/8205997/carepackage.zip)

**Comment by evilhero** [comment]
Yeah you have to check for a new version at least once. You have the version scheduler paused, as well as having the ``check_github_on_startup = False`` so it doesn't check github for any info unless you force it.

Ideally, your versioncheck in the scheduler should be In a Waiting status (you can click on Resume to start the scheduler up).

Setting the ``check_github_on_startup = True`` will also check github for new releases every startup (if it's been at least 15mins since the last check).

**Comment by wraith1385** [comment]
Thanks, I changed those settings and it fixed the issue!
