### ISSUE TITLE
NZB Searches Not Running

### ISSUE THREAD

**Issue by wraith1385** [mylar3/mylar3#1091]
I have nzb search providers configured through prowlarr.  All 4 of them test successfully.  However, no search actually seems to run when I move something to wanted.  In the logs, I can see "Completed queuing of search request." when I move something to wanted status but no search actually runs, nor does anything run when I do a force check on the Wanted page.

Care Package attached

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Branch / commit: Master/ v0.6.5

[carepackage.zip](https://github.com/mylar3/mylar3/files/8206914/carepackage.zip)

**Comment by evilhero** [comment]
I'm not sure if this is how you're doing it - but changing the status to Wanted from the Wanted page will not force it to run immediately (because it's already in a Wanted status).

Try going to the series page itself, and clicking on the magnifying glass beside the issue and see if that works. Aside from your indexers all returning 0 results for RSS feeds, which could be pointing to a possible misconfiguration on the prowlarr side, everything else seems to be functioning as intended as there is nothing being added to the search queue in the logs.

It does look like you have some permissions related problems as well as there are a bunch of Operation not permitted errors scattered throughout the logs which usually means that the user running mylar cannot move/write the file to the destination location.

**Comment by wraith1385** [comment]
This is what I see when I click on the magnifying glass, but still no actual search is being done.  Also these same indexers connected through prowlarr are working fine for sonarr and radarr.  



2022-03-08 14:53:40 | INFO | [WANTED-SEARCH] Now Queueing Star Wars: Darth Vader (2020) #20 for search
-- | -- | --
2022-03-08 14:53:40 | INFO | Initiating manual search for Star Wars: Darth Vader issue: 20
2022-03-08 14:53:40 | DEBUG | mode: want
2022-03-08 14:53:40 | DEBUG | ComicID: 124821

**Comment by evilhero** [comment]
Your search queue isn't being loaded for some reason - try restarting Mylar maybe. 

As an aside, Sonarr / Radarr use different calls than what Mylar does - so just because it works for one don't assume it will automatically work for the other since they have different code bases. For example, nzb.su may not work properly via Prowlarr since Mylar has it setup outside of the newznab provider section- prowlarr only syncs currently with the newznab / torznab sections of Mylar.

**Comment by evilhero** [comment]
There's  been a few patches today, one of which addresses this, but those are also in the python3-dev branch, not the master.

If you go to the **Manage** tab / **Activity/Job** tab  - is the Check Version Status set to Waiting or Paused? 

I'm guessing the prev run time for the Check Version is set to **-----**, meaning it hasn't been run previously. Can you try to do a ``Force`` on the Check Version? 

The main point in trying it like this is that you want the prev run time column to be populated for the Check Version. 

Once it's populated, you can restart Mylar and your queues should be loading fine at that point.

**Comment by wraith1385** [comment]
It doesn't populate even after the force and this error is in the logs:

Uncaught exception: Traceback (most recent call last):
File "/home/wraith1385/mylar/mylar3/Mylar.py", line 449, in
main()
File "/home/wraith1385/mylar/mylar3/Mylar.py", line 415, in main
versioncheck.versionload()
File "/home/wraith1385/mylar/mylar3/mylar/versioncheck.py", line 445, in versionload
rd = datetime.datetime.utcfromtimestamp(chk_last['prev_run_timestamp'])
TypeError: an integer is required (got type NoneType)

**Comment by evilhero** [comment]
Ok, maybe try to set the ``check_github_on_startup = False`` in your config.ini (with Mylar not running). Start it up after you save the ini, and go into the Activity / Jobs tab in the Manage tab and try to do the Force again.

**Comment by wraith1385** [comment]
Ok, now the searches work again, but it's back to being [None] in the version section of the settings.

**Comment by evilhero** [comment]
yeah this is the glitchy part that we kinda fixed already.

Now that you have it working, is there a prev run time value for the Check Version scheduler on the Activity / Jobs page ? I'm guessing at this point there probably is - and if so, you should be able to shutdown mylar, edit the config.ini and change the ``check_github_on_startup = True``, save the config and start it up.  This should fix the None value, as well as allowing you to search again.

If it's still None, or errors out again - the only alternative atm is to switch to the python3-dev branch, update and then run the scheduler when on the python3-dev branch.

**Comment by wraith1385** [comment]
Ok, I cloned the dev branch and those problems are fixed.  Now I just have to figure out how to get this to work properly with Sab on Windows.
