### ISSUE TITLE
Refresh Wanted Comics on Pull List

### ISSUE THREAD

**Issue by foinse** [mylar3/mylar3#1172]
**Describe the request**
A button on the weekly pull list to refresh series that are set to wanted

**How did you come up with the idea?**
After comic information is added to comicvine there's no quick way to refresh weekly wanted comics that now have CV data. Options are either wait for mylar to do it, or go through each series one by one and refresh.

**Environment (please complete the following information):**
 - OS: lsio docker
 - Branch / commit: python3-dev/6325c914e5b1602a384afed3fa764b579b638417

**Comment by barbequesauce** [comment]
You can also go to the Manage tab, Activity/Jobs, and then click "Force" on the Weekly pulllist line...

**Comment by foinse** [comment]
That's true, I just thought a refresh wanted button on the pull list page would be handy to just refresh the comics wanted this week,

**Comment by evilhero** [comment]
Mylar will automatically refresh the given series when it determines that CV has posted new issue information. It does this in 4hr increments.

It's almost impossible to have issue data for a given series not be accounted for in the weekly pull as the pull is what tells mylar to refresh the data for a series. 

If it's not pointing to the correct series however then it would not be able to signal the refresh of the series, which is what I think might be happening here as maybe the series you're looking for is pointing to an incorrect volume possibly. 

That being said, the Recreate Pullist will regenerate the pull and if any issues have CV data since the last pull update, the series will be tagged for a refresh.

**Comment by foinse** [comment]
Sounds good.
