### ISSUE TITLE
Series added to watchlist show wanted but are not

### ISSUE THREAD

**Issue by DieselTech** [mylar3/mylar3#1185]
**Describe the bug**
Adding a new series that doesn't have many issues yet will make it show up as red (wanted). Upon going into said series none of the issues are actually marked as wanted, giving a false impression they would be grabbed. 

![image](https://user-images.githubusercontent.com/30128380/165229257-7efed88f-5319-4e66-ad67-d46af2e179a7.png)

Logs don't show anything indicating this problem 

**Environment (please complete the following information):**
 - OS: Linux / Docker
 - Branch / commit: Dev /  73808fe31936b18692739536bd56204ffa800f92 

This _might_ be related to #1182 in some way.

**Comment by evilhero** [comment]
This is expected behaviour for issues that don't exist on CV, but Mylar is aware that there is an expected issue to come out that wiki.

As per the wiki topic https://github.com/mylar3/mylar3/wiki/Where-Mylar-gets-the-metadata-from:
In these cases Mylar knows that an issue is due out for that specific week, but can't verify anything against CV - so it changes the status of it to Wanted on the weekly pullist, but does not mark it as Wanted for the actual series (as there is nothing to link it to yet).
