### ISSUE TITLE
installation instruction unclear add clarity, make windows install super simple. 

### ISSUE THREAD

**Issue by Tom-Neverwinter** [mylar3/mylar3#1198]
**Describe the request**
clean up installation instructions. should be concise and not require outside reading

**How did you come up with the idea?**
I went to install the software

**Environment (please complete the following information):**
 - OS: [Windows10]
 - Branch / commit: [current 5/3/2022]
 - python 3.10.4 [dont have time for software that cant update its depends]

**Additional information**
```
Installation
from the root of the mylar installation (the location where you installed Mylar to), run the following command pip3 install -r requirements.txt to install all required dependencies not included.
Note Windows users open CMD/Terminal and CD [change directory] to installation directory: run "py -m pip install -r requirements.txt"
Prefer Docker? Take a look over [here](https://docs.linuxserver.io/images/docker-mylar3)!
How to start Mylar
Depending on your version of python, and how many different versions you have installed on your machine - executing the python command itself may be different than normal.

Typically this is either python or python3 - however in some cases, python3.9 or python39 may also work (as an example if you had python3.9 installed, other versions you would just change out the 3.9/39 for that version). Note that this will normally coincide with the pip command above - python3 = pip3, python3.9 = pip3.9, python = pip, etc [3.10.4 seems to work fine, again update your depends. nobody has time for that.]

From a command prompt/shell, and from within the Mylar program directory - type in <python executable> Mylar.py where python executable is python, python3,etc as previously mentioned above

on windows open CMD, "CD" again into install directory and run "python mylar.py"

Once it's started, check out the wiki entry on [Basic Usage](https://github.com/mylar3/mylar3/wiki/Usage#basic-usage)

```

**Comment by evilhero** [comment]
There is no outside reading required. There is a expectation however, that you already know the basics of a command line and have python installed. 

This is also not an issue with the program, but with your personal interpretation of the instructions which are sufficient for most people willing to spend the time reading.

There is no easy, simple, one-click method because you're  too lazy to figure things out yourself. We will not change the instructions. 

If you don't have time for software that doesn't update it's dependencies, maybe you should use docker. 

Or like find another program. 

Because if something as basic as installing the program is making your head swim, maybe you should find an alternative where you feel more comfortable.
