### ISSUE TITLE
Alpha and Omega issues not processing correctly

### ISSUE THREAD

**Issue by blyat** [mylar3/mylar3#1228]
Issues that have a name such as "Alpha" and "Omega" instead of actual numbering are not processing correctly (tried renaming MANY different times). The only workaround is renaming with # before the Alpha or Omega like for example "Devil's Reign #Omega (2022)" and moving it directly into the comic directory and rechecking in Mylar, but even then when you try to "rename" you get an error for those issues so you really never get proper naming or follow a correct workflow.

Also, those issues are not downloaded even if they are searched by providers.

Examples of issues are:

Devil's Reign Omega (2022)
Spider-Man 2099: Exodus Alpha (2022)
Hulk vs. Thor: Banner Of War Alpha (2022)

Version:
Docker Nightly Latest

**Comment by evilhero** [comment]
Should have been fixed with #1211 as far as processing and searching/downloading correctly.

Tested naming as ``Devil's Reign Omega 001``, ``Devil's Reign Omega #001``, ``Devil's Reign Omega`` (since it's a one-shot, the issue number can be left off).

Also tested same naming against the other 3 series mentioned and all are able to ReCheck properly when placed within the directory as is.

Downloaded and post-processed directly with no issues.

Renaming also appears to be working in regards to handling of these issues (it will use the numerical issue number with regards to one-shots however, instead of not using it as per the above situations).

So closing this - if this happens to still be an issue, please log a new issue and attach a carepackage with debug logs so we can try to isolate any futher problems.

**Comment by war3zlod3r** [comment]
Having this same issue on the latest build, cannot get it to pick up devil's reign omega no matter what I name it running bbccef9c8615063ab7f27354d3ae1e9e1a345574 (master)

**Comment by evilhero** [comment]
@war3zlod3r please don't re-open a closed issue - it's closed for a reason due to builds. 

Like was mentioned in the post, if it's still an issue provide a carepackage and open a new issue with the details and carepackage attached therein.
