### ISSUE TITLE
Searches not completing

### ISSUE THREAD

**Issue by ryborg** [mylar3/mylar3#1242]
**Describe the bug**
Everything was working wonderfully earlier in the month. Now I see no trace of searching through either DDL or torznab providers. Have tested them and they work. Mylar isn't searching. 

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.
[carepackage_v0.zip](https://github.com/mylar3/mylar3/files/8952826/carepackage_v0.zip)
If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Debian / Docker container
 - Branch / commit: [0.6.8](url)

**Additional information**
Add any other information about the problem here.

**Comment by DieselTech** [comment]
You say your running on docker but your carepackage says your running from source. 

If it is docker, what image are you using?

If it is source, you need to re-run 'pip3 install -r requirements.txt' since your missing some.

**Comment by ryborg** [comment]
I'm using kizaing/Kavita:latest

**Comment by ryborg** [comment]
I'm using latest docker image, but I updated from within Mylar3. I'm not sure that my container is updated. Should I try that from the console in docker?

**Comment by DieselTech** [comment]
Kavita is a reader app. It has nothing to do with mylar.

**Comment by DieselTech** [comment]
I asked what container you were using and you answered:

"I'm using kizaing/Kavita:latest"

Thus my confusion.

**Comment by ryborg** [comment]
Right. 
Ok, so I've updated my requirements. Restarted. Restarted container as well.

**Comment by DieselTech** [comment]
Before, your install was missing user-agent2. That would of stopped searches from happening. Now I see it there, but it doesn't look like there has been enough time for it to kick off any searches since the new container has been running. Let it run in the background for a bit and see if it starts to pull down issues. Once it's been running for a while and the logs have had time to fill up some, if it's still not snatching things then post back with another carepackage.

**Comment by ryborg** [comment]
I'm trying manual searches and nothing is happening.

**Comment by ryborg** [comment]
2022-06-21 22:20:48 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar3/Mylar.py", line 496, in main()File "/app/mylar3/Mylar.py", line 462, in mainr.loaders()File "/app/mylar3/mylar/req_test.py", line 47, in loadersself.check_the_pip()File "/app/mylar3/mylar/req_test.py", line 55, in check_the_pipwith open(self.file, 'r')as f:FileNotFoundError: [Errno 2] No such file or directory: '/config/mylar/requirements.txt'
-- | -- | --

**Comment by evilhero** [comment]
Don't retry the issue, use the magnifying glass to initial a search. You cannot retry a download that has already post-processed, which is what the logs indicate you're doing.

Also, your torznab providers are probably not doing any good either. TPB has zero for comics, KAT hasn't been what it used to be, and Lime is a hot mess.

Experimental is probably also giving you issues as it's what the title says for it - it's experimental. Query too much / too often, they'll temp ban your IP and then you won't get any results so it ends up being more problematic over time than worth it if that's what one of your main sources are.

DDL is dependent on GC, which is also possibly having high traffic due to the day, or its dead links it can't retrieve any longer (can't tell from the logs if that's the case, but timeouts can happen with ddl and it'll stall the download and possibly queue so that nothing subsequent can be downloaded via ddl)

Will look into the requirements.txt problem, podman is looking for the requirements.txt in the /config  which is just supposed to be for user files - not sure if they're moving files, expect it to be moved by Mylar or what, but there's some issue going on when you supply the data_dir option to the startup line (@DieselTech already made an issue in regards to this)

**Comment by ryborg** [comment]
I doubt those other settings are related. It doesn't matter what is available on those providers as they are never searched according to the logs. Searches are queued and that is all. No outbound connections at all. Then there is this problem: 
<img width="974" alt="Screen Shot 2022-06-21 at 6 43 18 PM" src="https://user-images.githubusercontent.com/3150498/174909043-15498b97-e52c-4ce9-982b-af5152db8d14.png">

I think this started after I updated from within Mylar although I am running in a container. The dates listed in the job queue coincide with when I updated. I will just run from source. Thanks anyway.

**Comment by ryborg** [comment]
Was able to redownload DDL files through Queue Management, restart just fine.

**Comment by evilhero** [comment]
You should never ever update from within Mylar if you're running in a docker / container. It won't work first of all, and second if it does it will probably bomb out in some way. Update your container images outside of the application itself (note that if it was properly detecting as a docker emvioit would show no option  to update from within the program itself).

And yes, those other settings will impact your success with mylar. To shoo what was mentioned aside in relation to your provider choices (which basically amounts to you having just ddl) is foreshadowing the amount of problems you'll probably experience in the future when it comes to mylar not downloading.

If the search queue dies due to a traceback error or some other problem it can't recover from, the only solution is to restart Mylar so it can load everything fresh.

I also have zero idea what you're trying to indicate with the screenshot.

**Comment by ryborg** [comment]
The last job updates took place weeks ago. That's why I referred to dates.
So then the problem is that not by not detecting I was running In a
container allowed me to update when I shouldn't have been able to.

Thanks. My settings seemed to work just fine until I updated. I don't
normally keep those other sources enabled. Only DDL.  Are we focusing on
the bug here or my actions?
