### ISSUE TITLE
Issue on clicking this week

### ISSUE THREAD

**Issue by Tomservov2** [mylar3/mylar3#1246]
Getting the following error on clicking this week.  Mylar3 up to date, windows 10.  Just switched fully from old mylar, so may be related

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\mylar3\mylar\webserve.py", line 2756, in pullist
    repoll = self.pullrecreate(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
  File "C:\mylar3\mylar\webserve.py", line 2979, in pullrecreate
    statchk = weeklypull.pullit(forcecheck, weeknumber, year)
  File "C:\mylar3\mylar\weeklypull.py", line 115, in pullit
    new_pullcheck(chk_locg['weeknumber'],chk_locg['year'])
  File "C:\mylar3\mylar\weeklypull.py", line 934, in new_pullcheck
    if 'Present' in watch['ComicPublished'] or (helpers.now()[:4] in watch['ComicPublished']) or watch['ForceContinuing'] == 1 or len(listit) >0:
TypeError: argument of type 'NoneType' is not iterable

Powered by [CherryPy 18.6.0](http://www.cherrypy.org/)

**Comment by DieselTech** [comment]
You said you just switched from "old mylar", have you reran the pip requirements? There has been some changes and updates from versions in the past.

**Comment by evilhero** [comment]
An item in your watchlist has an invalid publication run field. Could be due to not finishing refreshing/reloading the series or invalid data was present. If the pull update is still running it may be just a timing issue, but usually it's due a CV type of problem.

You'll have to go to your main index page, and sort by last issue date by clicking on the column header. You should be able to see at that point the series that have invalid dates (sometimes it's a form of the word ``Unknown``). You can also view items by going to the Manage tab / Manage Comics and sort by the date field therein. 

Once you find the series, go into the detail page for the series and click on the Refresh Series option -  you should then see the publication run field update accordingly on the detail page.

After updating the series, you'll be able to get into the pull again.

**Comment by Tomservov2** [comment]
I might know what the issue is, it's not finding my python when I try the pip command, but finds to to load mylar.pyw

I'll try that as well evilhero, thanks

**Comment by Tomservov2** [comment]
Ok, figured out my python situation.  verified that all requirements are installed.

I just installed the python 3.10 from windows store, then added scripts path it needed to environment variables. mylar shows 3.8.3


No series show unknown for latest issue.  I had one with status unknown.  I refreshed it and this week works now.  Not sure if mylar python version listing matters.

Thanks for the help


MYLAR PROGRAM OPTIONS
Python Version : 3.8.3
Language : en_US.cp1252
