### ISSUE TITLE
[BUG] version check fails, because it looks in the wrong folder

### ISSUE THREAD

**Issue by hotio** [mylar3/mylar3#126]
**Describe the bug**
At line 168 https://github.com/mylar3/mylar3/blob/4cd2abcfa3ad5ce0c48c0875570b6d41273a0fb9/mylar/versioncheck.py#L168
we combine app path and the file name....

However on line 174 https://github.com/mylar3/mylar3/blob/4cd2abcfa3ad5ce0c48c0875570b6d41273a0fb9/mylar/versioncheck.py#L174
we no longer use our combined path, but just look at the file `.LAST_RELEASE` without the app path, this will most likely fail...

**Environment (please complete the following information):**
 - OS: [all]
 - Branch / commit: [python3-dev & master]

**Comment by Bart274** [comment]
It shouldn’t fail. The `with open(...)` part should create the file in the working directory of mylar which should be the prog dir

**Comment by hotio** [comment]
It says it can't find the file and can't determine the version...

**Comment by evilhero** [comment]
Are you running from source or some other way? And how are you running Mylar? 

The .LAST_RELEASE only applies to source installs on master branch, otherwise it's not even generated.

It probably doesn't hurt to specify the data_dir in the os.join regardless. 

But for future reference please don't assume it breaks in all OS' simply because you tried it on one OS - just specify exactly what you're running and the commit, as that's what you've tested against.

**Comment by hotio** [comment]
I'm testing this with my own docker container (https://github.com/hotio/docker-mylar3), the version tested was commit e1c3f4a7a221f61eca7a6086f47864dc29dad4d2, ubuntu version in the container is 19.10 (eoan) and I'm running from source.

**Comment by evilhero** [comment]
Will update so it does the os.join - we had some people running our own [docker version](https://github.com/mylar3/mylar3/pull/121), but never came up with the error which is why I was asking. Expect a commit up into python3-dev as soon as I finish my coffee...

**Comment by hotio** [comment]
I am getting a bit confused however with all this talk about "should create the file" and "otherwise it's not even generated".

When you download the source there's a file containing
```
 (python3-dev)
e1c3f4a7a221f61eca7a6086f47864dc29dad4d2

```

When you start Mylar without doing `cd /pathmylarisinstalled` first, it will look for `.LAST_RELEASE` in whatever directory the user is currently in, eventhough it first checks if `/pathmylarisinstalled/.LAST_RELEASE` exists.....

**Comment by evilhero** [comment]
the .LAST_RELEASE is generated via git when you pull the source down. However, when you do a git clone, the variables aren't initialised so it's just the variables showing. It's mainly used for us to track source installs alot easier, and we've started using tags for the master branch in addition to this method.

**Comment by hotio** [comment]
OK, I thought me linking to the code parts for source installs would make it clear enough that I was running from source....will do better next time. :-)

**Comment by hotio** [comment]
I've also noticed that when `ct_settingspath` in config.ini isn't set yet, it'll try creating the folder `.ComicTagger` in the current home directory....What is your thought on maybe putting this under the `--datadir` or make it configurable with `--ctdir`?

**Comment by evilhero** [comment]
That's entirely based off of ComicTagger - we didn't alter the path configuration for the the settings file so as to not spike too far from their source. However, since we went full cli and removed all the GUI stuff, we pretty much did that anyways. 

I'll look into adding it under the --datadir option, but no promises as I'm not sure how deeply tied into CT the references are for the .ComicTagger directory portion.

**Comment by evilhero** [comment]
As of python3-dev commit 6022b05, under the **[Metatagging]** section of the config.ini you can alter the ```ct_settingspath``` to indicate the folder location where you want ComicTagger to create the settings file (and thereby subsequently load it from). If you leave it blank, it will default to your DATA_DIR location (ie. it will create a .ComicTagger folder in the DATA_DIR location and store the settings file in there).

Note that you might have to make sure that you don't have a ```ct_settingspath``` in the **[General]** section as well - if you do, you need to remove that entire line from that section so that it can properly load up the ```ct_settingspath``` value from the **[Metatagging]** section.

**Comment by barbequesauce** [comment]
@hotio do these patches resolve your issue? Can you comment or close the issue please?

**Comment by hotio** [comment]
Yep all good. Thanks for the quick fixes.
