### ISSUE TITLE
[RPI4] Can't connect Deluge to Mylar (docker version)

### ISSUE THREAD

**Issue by Tchiimy** [mylar3/mylar3#1265]
Hello,

On my Raspberry Pi 4 (RPi OS 32bits) I've recently installed the docker version of Deluge and Mylar (via portainer).

On deluge, I have activated the option "Allow Remote Connections" and I have this deamon : 
![image](https://user-images.githubusercontent.com/75799578/182258046-bcae2c47-f50f-4881-bd18-2026c52b995e.png)

On Mylar I try to connect Deluge with these parameters but I always get "Error establishing connection to Deluge".
![image](https://user-images.githubusercontent.com/75799578/182257751-6b5a78b4-e431-469f-9c12-be28cb881e00.png)

Have I made errors in the Mylar settings ? I don't really understand where I can find out what is the : 
- Deluge Host:port (I know the port is 58846 but the host is the RPi adress or the deamon adress 127.0.0.1 ?)
- Deluge username
- Deluge password

(sorry for the dumb question)

**Comment by barbequesauce** [comment]
Both are pointing at localhost (127.0.0.1). You’re using Docker - treat each container as it’s own machine - so localhost is not visible from the other container…  

--  
***@***.******@***.***)

**Comment by ajslater** [comment]
chances are you've named your deluge docker service 'deluge' or something. so 'deluge:58846' may be what you want.

**Comment by evilhero** [comment]
Mylar uses the daemon port not the web UI port. 

So while you have it connecting ok from the looks of it (outside of what @barbequesauce mentioned about specifying the ip) - you need to use the Deluge auth file to control daemon/remote access. The username and password are required for auth security by Deluge, so that's where you get the username / password from. 

You can read about how to setup the auth file by checking the Deluge docs : https://dev.deluge-torrent.org/wiki/UserGuide/Authentication

**Comment by Tchiimy** [comment]
Ok so I tchecked Portainer to find the IP of the deluge container and where is the /config file.

On the raspberry pi terminal I did : 
```
cd /portainer/Files/AppData/Config/Deluge
sudo nano auth
```

Then I added a line with `tchimy:password:10`

And I used this to connect Deluge on Mylar : 
![image](https://user-images.githubusercontent.com/75799578/182262524-b64ef9e0-c18e-4d6a-953b-7ce9bd33494a.png)
(the Deluge Host:Port  is the deluge_container_ip:58846)

And now Deluge seems to be detected so it have worked ! Thanks for the help !
