### ISSUE TITLE
DDL not matching issues

### ISSUE THREAD

**Issue by Roshri** [mylar3/mylar3#1279]
**Describe the bug**
Trying to fetch some missing issues using the "search 4 missing option", mylar searches for the series, finds some issues (including the missing one) and then skips them all and doesn't download a thing

[mylar.log](https://github.com/mylar3/mylar3/files/9396995/mylar.log)

**Additional information**
[carepackage_v0.6.9.zip](https://github.com/mylar3/mylar3/files/9397003/carepackage_v0.6.9.zip)

**Comment by evilhero** [comment]
Not sure what I'm looking for exactly. Nothing in the mylar log file posted shows any successful matches, just alot of failure to match for some reason or another. It's finding issues that match based on some aspect, but fails to be a full match and is rejected which is the expected result.

Try enabling debug logging, and then trying a search to get full logging as INFO level logging makes it difficult to see everything. Post a new carepackage after the search fails and we can look more into it. 

Maybe, also indicate what it is that you were attempting to download so that it's easier for us to locate said items in the log files.

**Comment by evilhero** [comment]
You also have your folder monitor set to monitor your comic location path for new comics. So it's continually checking your entire collection for new issues and trying to post-process them over and over and over again.

Never set the folder monitor location  to anything in your comic location path or downlaod path as it will screw up your pathing and post-processing. Folder monitor is intended to be used to monitor a location where downloads that mylar has not been involved with sourcing can be post-processed into mylar.

**Comment by Roshri** [comment]
Ok that was on me, the series I'm trying for is Draculina. The issue missing is #3, but it exists on getcomics.
Looking at the console output it's ignoring the issue because of date mismatch I think.

Thanks A LOT for the heads-up about the folder monitor! I was completely wrong about what it was for.
I have it disabled for now.

[carepackage_v0.6.9.zip](https://github.com/mylar3/mylar3/files/9397531/carepackage_v0.6.9.zip)
?

**Comment by evilhero** [comment]
So you just happened to pick one of the issues that looks like it has a discrepancy between CV and the actual date of the issue.

Issue #3 on CV has a store date of May 27, 2022. However the issue was actually released on April 27, 2022 (see where I'm going?). I'm pretty sure whoever added the entry on CV incorrectly put the store date as May  27, 2022, especially since the cover date on CV says April (cover dates are always day of or a few months after the store date).

So there are 2 things you can do to solve this:
- hope someone that has the power on CV will correct the store date to the right date (or if someone sees this that has the power).
- edit the Store Date value within Mylar itself. 
 
The quickest and easiest is actually the 2nd. This can be done by just double-clicking over the date for issue #3 when it's displaying the store date (not cover date), and a text box will appear. Enter in the date as ``2022-03-27`` and hit Enter. You'll see the edit box disappear and the new value will be present. Clicking on the magnifying glass will do an immediate search for the issue and you'll be able to grab it no problems.

**Comment by Roshri** [comment]
Thanks! Option 2 fixed it almost instantly!
Didn't know it was possible to manually set the cover date, this helps a lot!
