### ISSUE TITLE
Mylar3 not running on Ubuntu 22.04

### ISSUE THREAD

**Issue by musictrivianut** [mylar3/mylar3#1280]
**Describe the bug**
Just upgraded to Ubuntu 22.04 and Mylar3 will not start as a service, nor from the command line.

The error is gives is:

Traceback (most recent call last):
  File "/home/xxxxx/mylar/Mylar.py", line 27, in <module>
    import mylar
  File "/home/xxxxx/mylar/mylar/__init__.py", line 38, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'

I know that a lot went on during the upgrade, but I am most definitely not python savvy.  If someone could point me in the right direction on maybe what needs to be fixed, I would greatly appreciate.

And if it might be best to just re-install Mylar3, I can do that, too.  Just wanted to know if there was a simpler/better solution.

Thanks!

**Comment by evilhero** [comment]
Upgrading ubuntu also updates your version of python. In doing so it does a clean install of python, so any dependencies that were installed on the old version are not installed now.

You simply need to do the ``pip install -r requirements.txt`` from the root of the mylar directory, let it install / update the python dependencies, and that's it. (note that it might be pip3 depending on how your system is).

Also, make sure that the systemd file that you're starting mylar with is calling the correct version of python on your system (since it won't automatically detect that you updated things).

If you can successfully start mylar directly via the command line (not as a system service), then the systemd should start fine as well provided the right version is being called.

**Comment by musictrivianut** [comment]
Yes, sir/madam, are awesome.  I had seen that the upgrade was doing something with python, so I did check that the path to it was still okay (which python) and good in the systemd file.  Just had not thought of the requirements bit for the program.  One simple line and all is well again.  Thank you greatly!!
