### ISSUE TITLE
Dockerfile Build Failure "ERROR: unsatisfiable constraints:"

### ISSUE THREAD

**Issue by greycubesgav** [mylar3/mylar3#1312]
**Describe the bug**
The current Dockerfile provides an "ERROR: unsatisfiable constraints:" error while trying to build from scratch.

**CarePackage**
Not available pre-build.

**Environment (please complete the following information):**
 - OS: Docker version 20.10.21, build baeda1f [under macOS m1] & Docker version 20.10.18, build b40c2f6 [x86_64]
 - Branch / commit: ['python3-dev'](https://github.com/mylar3/mylar3/commit/bbccef9c8615063ab7f27354d3ae1e9e1a345574)

**Additional information**

##### Steps to Reproduce #####
* git clone git@github.com:mylar3/mylar3.git
* cd mylar3
* git switch python3-dev
* docker build -t mylar3 .

##### Docker Output #####
[error.txt](https://github.com/mylar3/mylar3/files/10135114/error.txt)

**Comment by evilhero** [comment]
The dockerfile included in the repo is severely outdated and probably unusable, so that comes as no surprise. 

We always recommend using LSIO docker (it's mentioned in our wiki), as we've worked with them in the past and they do a much better job of maintaining images. 

The dockerfile should be removed from the repo.
