### ISSUE TITLE
Update to version 0.7.0 results in empty db

### ISSUE THREAD

**Issue by xavier7179** [mylar3/mylar3#1314]
I updated the docker container to version 0.7.0, and now the DB is empty. Is there a way to go back or has the DB been completely erased? The comic folder is still with files, but I do not find any way to at least repopulate the DB from there...

I also tried to revert the container to v0.6.8 and copy the DB from the backup folder but still nothing...

 - OS: Linux Ubuntu 20.4
 - Branch: 0.7.0 

[carepackage_v0.7.0.zip](https://github.com/mylar3/mylar3/files/10199883/carepackage_v0.7.0.zip)

**Comment by evilhero** [comment]
Going back a version has nothing to do with the db file. They are separate items and the version of mylar will have nothing to do with your db contents. Mylar doesn't physically touch your db location unless it was instructed to. 

Based on the logs, your db file never had any entries in it. The number of items in your db file has never changed since you ran it initially back in 2021. You also had no backups running according to the logs. 

So either you are running the wrong local image of mylar (if you have multiples), or the mylar config files location was moved and they're no longer pointing to the correct location. That, or there never was anything in your warchlist (your last update prior to 0.7.0 was 0.5.1). 

Or possibly, you're not using the LSIO docker image, or wasn't previouslyand then converted over?

**Comment by xavier7179** [comment]
I moved to LSIO because I was on hotio and it is not supporting mylar anymore. But technically, the config dir is the same... at least, I thought it was...

**Comment by evilhero** [comment]
LSIO keeps their config in a different location than hotio did at one point. Not sure if he fixed that prior to stopping new images.

You'll have to find the location where hotio was dropping your db file and see if it's larger than 1mb in size (roughly).  If it is, odds are that's your db that had content within it.

Regardless at this point, your db is empty unless you can find your original db file. Once you find it, or make a new one, enabling the ``backup_on_startup`` option might be helpful, so that you can have some rolling backups for next time this may happen.

**Comment by xavier7179** [comment]
Thank you! I found a bug in the LSIO configuration. The Hotio DB was in the right place. I did not notice that inside the folder pointed as config in the docker file, LSIO was creating a mylar subfolder where everything was anew!
