### ISSUE TITLE
Error searching: "Unable to convert timestamp"

### ISSUE THREAD

**Issue by fabiorzfreitas** [mylar3/mylar3#1315]
**Describe the bug**
This bug happens whenever I search for an issue, the following WARNING appears on the GUI log and I don't get a download: `WARNING :: SEARCH-QUEUE : search_filer.py:checker:263 : Unable to convert timestamp from : (None,) ['NoneType' object is not subscriptable]` I'm not sure if it's related to any indexer, but I'm using NZBGeek and NZBPlanet. From the GUI log, it seems Mylar3 is finding some results, but is unable to parse them.

**CarePackage**
(CarePackage below contains a DEBUG log).
[carepackage_v0.7.0.zip](https://github.com/mylar3/mylar3/files/10253981/carepackage_v0.7.0.zip)

**Environment (please complete the following information):**
 - OS: Windows 10, pt-BR
 - Python 3.8.1 on Conda 22.9.0 (using an environment exclusive to Mylar3)
 - Branch / commit: master/5c1b5e2 (v0.7.0 release)

**Comment by evilhero** [comment]
Those are ddl related errors. Something about the timestamp that is being used for a ddl result can't be parsed properly - in guessing probably due to how you lr windows environment is setup (non-English, not gmt most likely). I'll ha e to take a look into it when I can. Your other providers aren't throwing the error, and it doesn't kill the queue,so I'm assuming the reason no downloads are happening is that the files you're searching for are only available on DDL. 

So you can disable DDL temporarily until we can figure out a patch, and you won't see that error any longer at least.

**Comment by fabiorzfreitas** [comment]
Yeah, I made sure to describe that my OS is pt-BR (although I never made any modification to the time/date format) because I could see on the output dates printed like `17-dez-2022`. If you decide to tackle this by translating strings, I'd be willing to do the ones for Brazilian Portuguese, although it would probably be more efficient to find a way that ignores localization.

Nevertheless, I can see the comic issues I was searching for on NZBGeek's website, but for some reason Mylar3 still won't grab them. Do the logs say that it's not finding them? If so, should I open another issue to try and solve this?

**Comment by fabiorzfreitas** [comment]
Setting the region to USA on Windows' time and date settings "fixes" it, so that's definitely the problem here. Mylar3 now outputs dates such as `18-dec-2022`

**Comment by evilhero** [comment]
You could also try to change the date format of your OS so that it displays in the format that mylar is expecting. Mylar does work with non-English languages, however it needs to use your system locale settings to figure out dates so they are localized to the client (it does it as UTC, but the dates posted are not always in UTC so it has to convert prior to calcs)
