### ISSUE TITLE
Error converting CBR to CBZ

### ISSUE THREAD

**Issue by fabiorzfreitas** [mylar3/mylar3#1316]
**Describe the bug**
I have a few comics in CBR format which were probably downloaded by Mylar3 back when I didn't have Metadata Tagging enabled. When applying "Metadata Series" to those, Mylar3 DEBUG log will display an error when it gets to the conversion part: `readArchiveFile(): [[WinError 87] The parameter is incorrect]  C:\tools\Mylar3\cache\mylar_7kpu4qn2\[ISSUE]` (please note I translated the error message from Brazilian Portuguese, I just googled for "WinError87 parameter").

On the regular log, the output is the following: `cmtagmylar.py:run:297 : [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ]Failed to convert cbr to cbz - check permissions on folder C:\tools\Mylar3\cache and/or the location where Mylar is trying to tag the files from.`

I have thoroughly checked the permissions from both folders and I manually ensured my current user, administrators and ALL APPLICATION PACKAGES have full access to them. I also took ownership with my current user. Finally, I tried running Mylar3 from an elevated cmd, so I'm pretty sure permissions are not the problem here!

**CarePackage**
The CarePackage below contains a DEBUG log.
[carepackage_v0.7.0(1).zip](https://github.com/mylar3/mylar3/files/10254007/carepackage_v0.7.0.1.zip)

**Environment (please complete the following information):**
 - OS: Windows 10, pt-BR
 - Python 3.8.1 on Conda 22.9.0 (using an environment exclusive to Mylar3)
 - Branch / commit: master/5c1b5e2 (v0.7.0 release)

**Comment by evilhero** [comment]
Pretty sure all the issues your having is due to using a version of python that's not official.   It's calling everything from your anaconda directory (``C:\Users\Fabio\.conda\envs\mylar3\python.exe``). Also your python environment has a tonne of extra calls to stuff within said directory which if you have anything comictagger related would hit that. Mylar can only use the CT that it comes packaged with. 

You run from source, when you upgraded did you happen to install mylar3 into a clean new directory or did you just hammer what was there already. If you just hammered it, source installs do not delete outdated files and there has been issues with mylar still calling old outdated files instead of newer ones in this situation. 

If the above applies, back up your config.ini, mylar.db and your entire cache folder to a location outside of the mylar3 directory. Wipe the mylar3 directory. Git clone a new version of you are able to do that (it's far better to use it than source to avoid these problems) or install from source. Copy the backed up files back into the new directory. 

If you only use Python with Mylar, I would uninstall any versions of python you have. You have several versions of python listed in your environment paths, so it may be trying to load stuff from an incorrect location. 

Install a version of python 3 from the official Python website (do not use the  MS store version) - preferably something around 3.9.6±.

Remove all references to mylar3 paths in your windows environment path. If you only use it with mylar3, remove any Python references in your environment path as Mylar will look in there for files it needs and may pull an unintended version. 

Rerun the requirements.txt against the version you just installed.

If you're still having problems after that:
Make sure you have WinRAR installed still. Open up the config.ini and find the value for ``unrar_cmd`` and set that to the full path to your WinRAR.exe file, including the executable in the path. Save the config.

**Comment by fabiorzfreitas** [comment]
Thank you for your quick response!

I can see I left out a lot of information I should have added before.

My PATH is cluttered with old entries from the mess I used to make with Python. As I decided to start learning the language, I removed every old installation (which was not an easy process) and started managing environments with Anaconda3. This means I don't have Python anywhere outside Anaconda environments and now I run every "project", such as Mylar3, in it's own environment in order to avoid conflicts. This means I don't have anything else related to ComicTagger.

---

I also tried to be very thorough in my own debugging before opening an issue, even if I forgot to get into those details: since I manage no more than 10 comics with Mylar3, I actually purged everything, except `config.ini`

---

Python 3.8.1 was something I got from reading [this comment of yours](https://github.com/mylar3/mylar3/issues/680#issuecomment-808822503) in #680. I was having some trouble with Pillow, so I just tried to copy your working setup.

---

I also checked for `unrar.exe` prior to opening this issue. It's available on PATH for me (via Chocolatey, so PATH gets a little less cluttered) from any folder.

---

This doesn't mean I won't be following your instructions, e.g. using a more recent Python, but I should have given all that information before, so here it is!

**Comment by evilhero** [comment]
Just an FYI, anaconda is fine for usage, however they also include their own version of python which deviates from the official Python package as they do "improvements" to speed up code. All of your environment calls are within the anaconda environment which may lead to problems with actual calls mylar has to make. Removing all mylar3 related env calls is best.

If all else fails I would try to do a python install outside of using anaconda and using an official repo in order to make sure its not env related. You can use env environments in normal Python (pyenv), outside of using a GUI there is no operating difference (outside of the fact that it uses official repos).

**Comment by fabiorzfreitas** [comment]
So I decluttered my PATH and also tried using Python 3.9.6 from Anaconda, which didn't work, so I tried using a fresh Python 3.9.6 install from Python.org. I even made sure I was calling the full path to the python executable.

Still no luck.

[carepackage_None_(master).zip](https://github.com/mylar3/mylar3/files/10254488/carepackage_None_.master.zip)

**Comment by evilhero** [comment]
I think you're possibly mistaken.

According to the logs it successfully tagged the cbz files (#32 of Rick and Morty) and subsequent attempts were successful too.

No WinErrors in the log after the last restart, so it's tagging as expected.

**Comment by fabiorzfreitas** [comment]
I'm not, the only CBR files are #12 to #31. I'm generating these attempts by going to Manage Comics, selecting the series and choosing MetaTag Series from the dropdown menu.

**Comment by evilhero** [comment]
It's tagging the zip files properly, the issue is your unrar - you have to tell Mylar where it's located by setting it in the ini as I indicated above. It's currently not set in your ini

**Comment by fabiorzfreitas** [comment]
unrar was available on system path all along. Still, I tried manually pointing to it on `config.ini`, with no luck
![image](https://user-images.githubusercontent.com/12950727/208317726-72816042-c533-4687-b79f-4c8b9ce46fec.png)

**Comment by evilhero** [comment]
Not config.ini, the settings file in the .ComicTagger directory. 

The unrar test on the configuration page just tests if it can locate winrar, there could still be linking problems so sometimes you need to forcibly set the path instead of having mylar resolve it.

**Comment by fabiorzfreitas** [comment]
That did it, thank you!

BTW, I tried it again from the conda environment and now it's also working fine from there as well!
