### ISSUE TITLE
[Bug] Slow console output since v0.7.2

### ISSUE THREAD

**Issue by ojmaster** [mylar3/mylar3#1353]
**Describe the bug**
After upgrading to this version my console does not output as quickly rather almost every 5 minutes

**CarePackage**
[carepackage_v0.7.2.zip](https://www.dropbox.com/s/v3blvtxe4d2v1j9/carepackage_v0.7.2.zip?dl=0)
(It's above 25mb upload limit)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.10
 - Branch / commit: [v0.7.2](https://github.com/mylar3/mylar3/releases/tag/v0.7.2)

**Comment by evilhero** [comment]
This is not a bug, your folder monitor is firing off every 5 minutes checking for new downloads as expected. Set your logging to debug and you'll probably see additional logging as it's being performed. 

Mylar doesn't continually search and fire off stuff every second, the auto-search only fires off every 6hrs, the pull gets updated every 4hrs, the database gets updated every 24hrs, etc. Anything else occurring outside of those aspects is a manual interaction.

Also, you should never ever set your folder monitor to your cache folder. As that is where your ddl downloads go by default - if it's downloading something while the folder monitor starts (every 5mins), it could try to post-process files that aren't fully downloaded. While it tries not to, the possibility is always there. 

It's fine to do a manual post-processing against the cache folder as those are manually performed. 

If your reasoning is because the ddl downloads are not being moved after being done, then there is something else occurring that needs to be addressed. Folder monitor is not the answer for this.

**Comment by ojmaster** [comment]
No, what was happening was nothing was outputting to the console and then in around 5 minute intervals everything in those 5 minutes would output at once, this issue was only occurring in mylar but recreated the docker container and it was fixed.
