### ISSUE TITLE
Queue not downloading for hours but manually starting an item is successful

### ISSUE THREAD

**Issue by hwwilliams** [mylar3/mylar3#1355]
**Describe the bug**
Queue is full of snatched issues from DDL but they don't download, if I click start on an issue manually then it downloads and post-processes fine, it's been like this for several hours so unless there's some kind of daily queue task I didn't see I don't understand what its waiting for to start downloading issues.

**CarePackage**
[carepackage_v0.7.2.zip](https://github.com/mylar3/mylar3/files/11512485/carepackage_v0.7.2.zip)

**Environment (please complete the following information):**
 - OS: Debian 11
 - Branch / commit: master/eca80ef

**Additional information**
![image](https://github.com/mylar3/mylar3/assets/20447447/6babc032-ffa4-4299-b808-fa3d9aac91a9)

**Comment by evilhero** [comment]
Have you tried to use the ``restart the queue`` button at the top right instead of selecting start for a single issue?

Most likely the queue is locked due to encountering an error from which it couldn't auto-restart. When the queue is locked, it can't proceed further and any additional items that are queued just get added to the stalled queue. 

You need to restart the queue so that it can start downloading them individually in sequence. If you restarted mylar, I don't believe the items will auto-start so you have to use the restart queue option to force fire it off. 

With DDL, Snatched means it is queued for downloading, but has not yet been actually downloaded. It literally goes into a queue to download items as it can only download one item at a time.  On the Manage DDL page, when it says Completed it has successfully downloaded the item. An item that is Snatched, may not be able to download due to invalid links, timeouts, etc but that only occurs when it's trying to download the item, not during the snatched stage of DDL.

**Comment by hwwilliams** [comment]
> If you restarted mylar, I don't believe the items will auto-start so you have to use the restart queue option to force fire it off.

This is what confused me, I did restart Mylar several times when I noticed and I figured that would restart any tasks that had gotten messed up.

Restarting the queue itself solved the issue immediately, thanks for the quick fix!
