### ISSUE TITLE
NZB Search Issues

### ISSUE THREAD

**Issue by NickSica** [mylar3/mylar3#1377]
**Describe the bug**
When searching for an issue, NZBGeek and ALTHub never find matches. The same search done through the same URL in my browser produces results(trying to be careful about what I show in the NZBGeek screenshot). I am not sure if it is even grabbing results from NZBGeek since I don't see anything in the logs about rejecting search results.  
![image](https://github.com/mylar3/mylar3/assets/26910401/82ac165a-c5b2-4e16-9633-1faaf83ef6a0)

**CarePackage**
[carepackage_v0.7.2.zip](https://github.com/mylar3/mylar3/files/12098771/carepackage_v0.7.2.zip)

**Environment (please complete the following information):**
 - OS: Docker image
 - Branch / commit: Latest Docker

**Comment by evilhero** [comment]
Curious since it's all blocked out due to the carepackage, for the althub url you put into mylar as a newznab, did you add an /api to the end of the url or did you put it without it?

I think you may have added it, but you don't add one for althub since it's redirecting to the api url - you'd get a valid response from a test, but searches would come back empty (I'm guessing here)

**Comment by NickSica** [comment]
Yep that did it, I can't believe I missed that, sorry for the annoyance.

**Comment by evilhero** [comment]
No annoyance, but it's a good reminder that I should up the default to something bigger since it's 2023. Glad you got it working!
