### ISSUE TITLE
Retry Same Download Again Results in Uncaught Exception

### ISSUE THREAD

**Issue by thrillho93** [mylar3/mylar3#1387]
**Describe the bug**
I have several issues that have been marked as "snatched" but I don't believe Mylar's actually downloaded them. After upgrading I tried to get them out of that status using the "retry same download again" button. However, according to the log data this throws an immediate uncaught exception:

<html><body>

```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.11/threading.py", line 975, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar3/mylar/webserve.py", line 2443, in retryissue
sendit = search.searcher(fullprov, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/mylar3/mylar/search.py", line 2875, in searcher
nzbid = comicinfo[0]['nzbid']
~~~~~~~~~~~~^^^^^^^^^
KeyError: 'nzbid'
```

I'm using DDL with Getcomics enabled.

</body>
</html>

**CarePackage**
[carepackage_v0.7.3.zip](https://github.com/mylar3/mylar3/files/12270944/carepackage_v0.7.3.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu - Docker 
 - Branch / commit:  v0.7.3 (master)

**Comment by evilhero** [comment]
Unfortunately it's not really a bug, but it could be handled alot better.

When a DDL item goes into snatched status it doesn't mean it was actually snatched (unlike nzbs where it does mean it was sent to your download client). It means that it was put in the ddl queue to download but nothing has been done as of yet. What ends up happening is sometimes another download causes an error and the queue stops, or the ddl item in question is linked behind a paywall type of download and mylar cannot grab those. This is primarily because DDL is done via http so there are some limitations as to what can be done. 

So it can't retry it because it never was actually snatched (if that makes sense). It should actually say it was Queued, and then Snatched after it successfully downloads, but there was some workflow issues that caused some problems when that was attempted (awhile ago mind you).

**Comment by thrillho93** [comment]
Thank you for the explanation. Is there a log somewhere to view details about failed downloads?
