### ISSUE TITLE
Post-Processing finishes work, but reports failure and doesn't clean up cache directory

### ISSUE THREAD

**Issue by SScorpio00** [mylar3/mylar3#1409]
I've been using Mylar for many years under Windows and switched to a Linux container setup porting over my configuration. The uploaded carepackage doesn't contain the database which is over 560MB, and max zip compression brings the archive down to 63MB which is over Github's 25MB max size. Let me know if there's an alternative way to share it if needed. The file I'm uploading contains just the log down to the error and configuration files.

Post-processing seems to be working, even cleaning up the NZBGet directory, the problem is that /opt/Mylar3/cache isn't being cleaned up. This leaves *.nzb, *.cbr, *.cbz, and mylar_ABCXYZ123 directories around that quickly use up space.

My setup is a separate NAS device that hosts a Media share, and a ProxMox host running Mylar and NZBGet containers. Post-processing is configured in NZBGet and is successfully triggering on download, but reports back failure, even though the file ends up converted and tagged in the final library destination.

Mylar is running under Debian 12.
Version: e210d31af07a5abaad3750710d5c8276ef20dae4 (python3-dev) 

The ProxMox host has a mapping for the NAS Media share and then mounts each container into its needed paths. Internally in the container, the /mnt location is set up as root:lxc_shares with 770 permissions. And Mylar is run via systemd as mylar:lxc_shares.

The relevant layout is as follows:

Media
|
| -- Comics
| -- -- Mylar --> maps in Mylar container to /mnt/library
|
| -- Staging 
| -- -- Usenet --> maps in NZBGet container as /mnt/usenet
| -- -- -- Comics --> maps in Mylar container to /mnt/ingest

Mylar is able to successfully search and initiate a download, NZBGet grabs the content, unpacks to a location readable by Mylar, and then successfully triggers the Mylar post-processing. The file is converted and tagged and then ends up in the final library location. But /opt/Mylar3/cache directory isn't cleaned up.

In the Mylar container, the file system is like this.

/opt/Mylar   		mylar:lxc_shares 770
/opt/Mylar/cache     mylar:lxc_shares 775
/mnt/ingest  		root:lxc_shares  770
/mnt/library 		root:lxc_shares  770

If I manually connect to the Mylar container and switch to the mylar user, I'm able to access both /mnt directories without issue, and able to issue any copy, move, or delete command without error. I'm also able to remove the files that aren't cleaned up out of /opt/Mylar/cache.

[carepackage_e210d31af07a5abaad3750710d5c8276ef20dae4_(python3-dev).zip](https://github.com/mylar3/mylar3/files/12446062/carepackage_e210d31af07a5abaad3750710d5c8276ef20dae4_.python3-dev.zip)

**Comment by evilhero** [comment]
The nzb, cbr and cbz files aren't automatically cleaned up unless the ``cleanup_cache = True`` is set in your config.ini. It will run on each startup and clear out any unnecessary files.

As far as the mylar_xxxxx directories, the only reason those couldn't be cleaned up is if mylar can't delete the files/directory. This can occur when permissions aren't enough, or if there was a problem with metatagging.

I'm going to guess that the constant downtime for CV and the problems of them blocking comictagger is resulting in missed metatagging and causing it to not delete the mylar_xxxxx directories due to the failure. I which case if that's the issue, there's not much that can be done as far as the abandoned directories as mylar isn't sure if the files have been moved or not, so it plays it safe and aborts the process.

**Comment by SScorpio00** [comment]
Yeah, I noticed that error, but I can't figure out what permission issue there could be. When connected as the mylar user I can perform any operation I can think of without issue. Is there a setting that will list out the commands it's calling to help track down the source of the issue?

**Comment by evilhero** [comment]
Well it's during the move after the tagging so it's possible it can't move the file to the given location, or it can't remove the files after the move. Since it's an OS level (done via shutil), there isn't any info being returned outside of the error number unfortunately.

I did see that you have enforce permissions enabled in mylar. That may be causing an issue as mylar can't enforce permissions across any type of remote mount, and on other types of locked down systems. Try turning off enforce permissions within mylar and doing another post-processing attempt, it may actually clear things up (the OS is usually smart enough to enforce permissions on its own, or it's inheritable via the mounts)

**Comment by SScorpio00** [comment]
I enabled auto update and the cleanup cache settings, while disabling enforce_perms and then rebooted the whole container just to be sure.

I then deleted an issue from its location in /mnt/library and checked that /opt/Mylar/cache was clean. I triggered a download from Mylar. And I'm still getting the Operation not permitted error. I still have the mylar_xyz folder in cache, but the others (nzb cbr cbz) are no longer there. But the issue did end up in its final target location under /mnt/library.

I tried repeating using copy rather than move under the post-processing settings and it's the same issue.

It'll take a bit more configuring, but I think I can set up a new mount in the host just for Mylar that I'll be able to resolve so the shares will have mylar:lxc_share permissions. This will take a while to get switched around though.

**Comment by SScorpio00** [comment]
I was able to reconfigure my setup to create a shared mapping just for Mylar that handles the way the unprivileged LXC containers do their user mapping so that /mnt/ingest and /mnt/library show as mylar:lxc_shares rather than root:lxc_shares with everything else being exactly the same.

And, the post-processing reported success back to NZBGet, and everything cleaned up as I would expected.

So even though the user Mylar is running under had full access via its group. There's still something that requires the target directory to be owned by that user even with the enforce_perm disabled.

Thanks for taking the time to look at this, as well as for creating and maintaining this awesome software.
