### ISSUE TITLE
DDL Seemingly Not Actually Searching: 0 results for comics on GC, Last Search Time Forever Increasing

### ISSUE THREAD

**Issue by scooterpsu** [mylar3/mylar3#1414]
**Describe the bug**
DDL doesn't error while searching, but never finds anything. And then the Last Search seemingly goes up on each search, seemingly counting back to when it tried the first time.

**CarePackage**
https://drive.google.com/file/d/1FbVEPoJ1ekTPqLkj0oCv_0us4l30D75b/view?usp=sharing

**Environment (please complete the following information):**
 - OS: UnRaid (Slackware Linux)
 - Branch / commit: Dev, LSIO Nightly Docker

**Additional information**
I deleted my cache and .secret folders before restarting the container to see if any remnant files were to blame

**Comment by OddBloke** [comment]
I've spent a while digging through the code, here are some findings.

I don't believe that the logic in `getcomics.GC()` is the issue here: the `lastrun` for GC in the `provider_searches` table does match the last search attempted in the log, so I think it is correctly writing updates in.

I have noticed a discrepancy in the value in the log lines for the provider:

```
06-Sep-2023 21:14:14 - INFO    :: mylar.search_init.587 : SEARCH-QUEUE : Could not find Issue 65 of Saga (2012) using DDL(GetComics) [api]
06-Sep-2023 21:14:14 - INFO    :: mylar.search_init.598 : SEARCH-QUEUE : attempting to set DDL(GetComics) to not being the active provider.
06-Sep-2023 21:14:14 - INFO    :: mylar.search_init.600 : SEARCH-QUEUE : setting last run to: 1694020695.215568
06-Sep-2023 21:14:14 - INFO    :: mylar.search_init.604 : SEARCH-QUEUE : setting took. Current provider is: {'DDL(GetComics)': {'type': 'DDL', 'lastrun': 1694049239.082092, 'active': False, 'hits': 1074, 'id': 200}}
06-Sep-2023 21:14:14 - INFO    :: mylar.search_init.351 : SEARCH-QUEUE : checked_once: ['DDL(GetComics)']
06-Sep-2023 21:14:14 - DEBUG   :: mylar.search_init.639 : SEARCH-QUEUE : findit: {'status': False, 'provider': 'DDL(GetComics)', 'lastrun': 1694020695.215568}
06-Sep-2023 21:14:14 - INFO    :: mylar.search_init.641 : SEARCH-QUEUE : Finished searching via : api. Issue not found - status kept as Wanted.
```

```
06-Sep-2023 21:14:19 - INFO    :: mylar.search_init.364 : SEARCH-QUEUE : prov_order[prov_count]: DDL(GetComics)
06-Sep-2023 21:14:19 - INFO    :: mylar.search_init.466 : SEARCH-QUEUE : current_prov: {'DDL(GetComics)': {'type': 'DDL', 'lastrun': 1694020695.215568, 'active': True, 'hits': 1074, 'id': 200}}
```

The values prefixed with `169404` are correct, `1694020695.215568` is incorrect.

My best guess is that a stale `provider_stat` is being held in memory and reused, instead of being recreated from a database lookup. Next steps are to look up the call chain.

**Comment by OddBloke** [comment]
@scooterpsu Setting the timings aside for a moment, I notice you have Flaresolverr enabled. I don't have experience using it, but are you able to check if it is correctly forwarding requests to GC? If it's returning empty pages, for example, that could explain the lack of results.

**Comment by scooterpsu** [comment]
Getting empty pages is the reason I turned on Flaresolverr in the first place. With the old code I could verify the returned pages were Cloudflare error pages, since they'd dump html in the cache folder. With Flaresolverr turned off, my logs look identical to before, except now without lines about getting/finding a cookie.

**Comment by OddBloke** [comment]
> Unless you redirected something in your code change, Flaresolverr is only called when getting the initial cookie. So that's the only call I see in Flaresolverr logs.

Aha, OK, I understand how that works now. I _shouldn't_ have changed that behaviour: my changes were around how the results were parsed. (I did refactor the fetching to a separate function, but it still calls `self.cookie_receipt()` before making any requests, and the actual `.get()` call is unchanged).

Incidentally, I actually have the timestamp mismatch issue on my install: it looks orthogonal to your issue here (in that it happens for any failure, whatever the reason) so I've filed #1415 for it.

**Comment by OddBloke** [comment]
> the actual `.get()` call is unchanged

Actually, apologies, this isn't true! I was looking at the wrong subset of my commits. We did stop passing `stream=True` and, as you note, we did stop writing the pages to disk (instead just keeping them in memory).

**Comment by scooterpsu** [comment]
I realized it's probably worth noting that I haven't had success with DDL since before your code changes. For whatever reason Flaresolverr gets a valid cookie but even with that it never returns valid page results. Eventually I was going to look into routing all calls through Flaresolverr, but it's a bit beyond me.

**Comment by OddBloke** [comment]
> I realized it's probably worth noting that I haven't had success with DDL since before your code changes. For whatever reason Flaresolverr gets a valid cookie but even with that it never returns valid page results.

Okay, that's good to know! I was staring at this trying to figure out how my changes could have changed behaviour this substantially, haha

> Eventually I was going to look into routing all calls through Flaresolverr, but it's a bit beyond me.

Yeah, I think this would be moderately complicated: we'd need to set up a Flaresolverr session and then use Flaresolverr API calls instead of direct HTTP requests, and then correctly destroy the session when done with it (else I think we'd just leave a browser running within Flaresolverr indefinitely).

**Comment by scooterpsu** [comment]
Flailing at this with evilhero yesterday sorted out my primary issue. In the end I didn't end up needing Flaresolverr, the header issues were causing the problems, rather than the cookie.

It doesn't seem to be incrementing forever so I think your other commits sorted that out.
