### ISSUE TITLE
Not possible to search series with '.' in name

### ISSUE THREAD

**Issue by diax78** [mylar3/mylar3#1423]
**Describe the bug**
When searching for 'L.E.G.I.O.N. Annual' in search bar results returned are all but not the one I looked for. So the actual question is, how to escape special characters in search so the query will return proper outcome. 

**Environment (please complete the following information):**
 - OS: docker on QNAP
 - Branch / commit: 0.7.5 and previous

**Comment by evilhero** [comment]
Looks like you can't atm due to some stripping of characters issues along with passing of variables. This may/may not be able to get addressed. 

There are 2 options available in the meantime:

- add the series directly by putting the full comicid (4050-xxxxxx) in the search bar and it will add that specific id.

- use the tampermonkey script from our forums that will put an icon beside the title when you view a series on the CV website. Clicking on the icon will add the series directly into your mylar instance.

**Comment by diax78** [comment]
Thanks! The trick with comicid (which I did not know) works like a charm. I think for now this is enough - there is not so much of such cases and usually I know exactly which ones.
