### ISSUE TITLE
Error popup when clicking Issue details

### ISSUE THREAD

**Issue by neuzeltje** [mylar3/mylar3#1467]
**Describe the bug**
First of all let me say thank you for an amazing program. Even though it was quite a steep learning curve I do appreciate the program very much. And it usually works like a charm. But after I updated, I noticed the following, maybe not a correlation but just so you know. 

when I look in a serie, for instance Big Game, I have five files and when I click on view CBZ issue details, 2 are blue and the rest is orange. When I click on the orange one I get a popup stating there is an error. with a bit of googling it looks like there is an error with the rawimage. I even tried to look in the getimage.py but that went quickly over my head.  I have attached the error message as well. 

**CarePackage**
[carepackage_v0.7.7.zip](https://github.com/mylar3/mylar3/files/13799071/carepackage_v0.7.7.zip)
[ERRO !DOCTYPE html PUBLIC.txt](https://github.com/mylar3/mylar3/files/13799079/ERRO.DOCTYPE.html.PUBLIC.txt)

**Environment (please complete the following information):**
 - OS: [Windows11]
 - Branch / commit: [Master/[v0.7.7]]

Thanks very much for your effort in advance.

**Comment by evilhero** [comment]
Blue indicates cbz, orange means cbr. So if you click on the orange and it throws a error, usually that means that it's unable to access the file, possibly due to a corrupt image within the archive.

Have you tried metatagging the series and there were a few cbr files that didn't convert to cbz? 

I would enable verbose / debug logging (via the config.ini so it's persistent thru restarts, ``log_level = 2``), then try to click on the orange icon to get the error message, and maybe try to metatag it (you should be able to click on the comictagger icon on the same line as the orange ``i`` icon). 

Then if it doesn't change to a blue icon, there will be an error in the logs that will indicate what the problem is and you can generate a new carepackage and attach that.

**Comment by neuzeltje** [comment]
Thanks for the fast reply. I have edited the ini file to set it level 2. Restarted and opened the file first to see if there where errors. Could open and read it normally. Issue details gave same error, did the metatag and clicked details again. Also tried two others in the same folder. Same result. Have attached the care package 
[carepackage_v0.7.7(1).zip](https://github.com/mylar3/mylar3/files/13799362/carepackage_v0.7.7.1.zip)

the logfile says something about changing from cbr to cbz, and permissions. on the cache directory mylar has full control.\
Hope this helps.

**Comment by evilhero** [comment]
Unfortunately I guess you had mylar running when you edited the config.ini, so the setting change never took. Mylar has to be not running whenever you edit the config.ini, as it will overwrite any changes that are made otherwise.

You'll have to try the process again (shutdown mylar, edit ini, start mylar, click on orange icon, try metatagging, generate carepackage).

The permissions could also relate to where it's metatagging issues to - the series directory itself, especially if it's not a local mount. You can also open up an archive that has a corrupt image, and it would appear fine until you try to open the corrupt image file and it could even show up as a truncated image.

**Comment by neuzeltje** [comment]
you were correct, I have it running as a service. So I stopped the service, edited the ini, restarted the service and tried manual tagging. stilll no issue details and some error message to check the logs
[carepackage_v0.7.7(2).zip](https://github.com/mylar3/mylar3/files/13800534/carepackage_v0.7.7.2.zip)

Do you want the  mylar.log file as well. or is that taken care of in the carepackage?

**Comment by evilhero** [comment]
Nope it's all included in the carepackage which sanitizes the logs as well.

I think the problem is that mylar can't locate a version of rar on your system. In order to view cbr files (or even convert them), you have to have a version of unrar on your system. 

If it's not in your PATH, then you have to tell mylar where it is via the ini so that it can execute it when required. I can't remember offhand what the ini variable is, it's in the metatagging section of the ini and it should be fairly easy to figure out (unrar_cmd or rar_exe_path, can't recall). I can't check until I'm home which won't be for another 12hrs probably at least.

**Comment by neuzeltje** [comment]
I have added winrar, which was on the system already to the path. But the document was a CBZ and not a CBR. Rebooted just to be sure. Still same error. other 4 issues could be retrieved. both cbr and cbz. Manual tagging didnt work, so I tried the comic tagger app just to do comic number 3 and that worked. Now Mylar can retrieve issue details.
Other directories still have the same issue. will try to correct them with comic tagger as well to see if that solves anything. 
[carepackage_v0.7.7.zip](https://github.com/mylar3/mylar3/files/13800914/carepackage_v0.7.7.zip)

when I went to get a new care package a new box was highlighted stating that PYsocks 1.5 is not installed. That is also a new one. 
but solved that one by updating pip and pysocks. (still learning every day even on my old age :) )
Will give an update regarding the other directories.

**Comment by neuzeltje** [comment]
First of all a happy new year. I think I have broken my installation completely. I thought that updating the python version to the latest, 3.12.11 would help but now mylar wont start at all, the service is paused and will not start. I tried to manually restart mylar with the command python mylar.py and I get the following traceback

Traceback (most recent call last):
  File "E:\_Port appl\Mylar\mylar.py", line 27, in <module>
    import mylar
  File "E:\_Port appl\Mylar\mylar\__init__.py", line 38, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "C:\Appl\Python\Lib\site-packages\apscheduler\__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "C:\Appl\Python\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

I then tried to reinstall in a different folder, cloned from git and restart again but it gave the same error. Do I need to uninstall python and go back to an older version?

**Comment by neuzeltje** [comment]
Ok, removed python latest version and went back to version 3.11.5. so we are back to fully operational and it can now do manual meta tagging again without an error. so progress has been made. Only the issue details still gives the error frame but not on every comic I open with that one. Just bad luck, corrupt file or something else?

**Comment by evilhero** [comment]
Have you verified permissions on those particular files that you're trying to tag but cannot ? I saw some remote mounting and I'm wondering if mylar doesn't have access to those particular files because they're on a different / remote filesystem.

If they do have permissions, I would surmise that they are probably corrupt or possibly even people renaming the extension but the files are a different format (ie. renaming it to cbz, but they are cbr files or vice-versa).  If CT can tag them manually in the standalone app, I would think it would be either of those 2 issues as Mylar has problems sometimes with incorrectly renamed filetypes as well as with permissions on remote mounts.

**Comment by neuzeltje** [comment]
Ah ok. I do have the tendency to sometimes rename the filename to cbr instead of cbz.
Thanks for all the help so far, I learned a lot and keep up the good work. I think the issue can be closed.
