### ISSUE TITLE
Unable to connect to Deluge

### ISSUE THREAD

**Issue by DrSeussFreak** [mylar3/mylar3#147]
**Describe the bug**
Deluge fails to connect each time I run test.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4276418/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Branch / commit: Version: adc9bb5ecad33428fb36b74c53c1b4e9b76f939c (python3-dev)

**Additional information**
Deluge runs on a separate VM, and it is working just fine.  I do have a self-signed certificate in front of deluge (mylar too).

**Comment by psychogun** [comment]
In my config.ini, I have a Value in the `deluge_username` parameter. 

Is it stripped from the carepackage.zip > clean_config.ini?

Anyways, I am connecting to Deluge through ip-to-deluge:58846. 

Then I am using a username and password which I have defined in the `deluge/.config/deluge/auth` file;
`Mylarusername:mylarpassword:10`.

**Comment by DrSeussFreak** [comment]
I have the following

```
[Deluge]
deluge_host = https://torrent-01:9089
deluge_username = None
deluge_password = <removed>
deluge_label = mylar
deluge_download_directory = /torrents/watching
deluge_done_directory = /torrents/done
deluge_pause = False
```

I don't have a username for deluge, and the default is none.

**Comment by psychogun** [comment]
Yes, but, I don't think you are supposed connect to the web interface. 

Can you try to define a username and password in the auth file, and use the `deluged` port instead of the `deluge_web` port (??). And just a IP.

You'll probably in the `auth` file see that there is a user defined; `localclient`? Just add another line with `mylarusername:mylarpassword:10` and see if this works with `torrent-01:58846` or whichever port the deluge daemon listens to (?)

**Comment by DrSeussFreak** [comment]
trying this now

**Comment by DrSeussFreak** [comment]
Awesome, this did the trick!  Much obliged @psychogun, thanks!

**Comment by evilhero** [comment]
@psychogun , no other way to communicate - so this kinda sucks. Saw your FBSD wiki in the mylar repo, can I move that to the mylar3 wiki ? Also, you might want to look at [this](https://github.com/mylar3/mylar3/wiki/FreeBSD-unrar-cffi-installation-instructions) for your unrar-cffi installation problems ;)

**Comment by psychogun** [comment]
@evilhero Yes, please do. Just a comment, it is a work in progress / ever changing place for all my notes :)

Regarding unrar-cffi; I have not tried it, though - but someone gave a comment on the freebsd channel;

> you could just "MAKE=gmake python setup.py build"
> likely
> getenv() above tries to get $MAKE and if it's not present uses the default option
> like how you'd use get() in Python to get a default in case there's no key you are looking for in your dict
> keep that in mind for the future I guess, to avoid edits \o/

**Comment by evilhero** [comment]
Yup that's pretty much the gist of what that wiki entry I just did does (changing make to gmake only by editing the file first - setting it like that is easier).

Will note that it's a WIP - since there's no one on the dev team that uses it (some people that hang on the irc channel do and that's how we test things with them), the more information we have available is never a bad thing.

Thanks for the wiki entry - and for the shorter way to do the gmake!
