### ISSUE TITLE
Searching for Wolverine causes 500 Internal Server Error

### ISSUE THREAD

**Issue by Roshri** [mylar3/mylar3#1517]
**Describe the bug**
Wanted to Add Wolverine to my Watched list and when I searched for it, got 500 Internal Server Error.

It's worth noting this only happens when searching for the string "Wolverine", if I search other more specific like "Savage Wolverine" it works as intended 

**CarePackage**

[carepackage_v0.7.8.zip](https://github.com/mylar3/mylar3/files/14454091/carepackage_v0.7.8.zip)

**Environment (please complete the following information):**
 - OS: W10
 - Branch / commit: Master  v0.7.8 (master) 

**Additional information**
When this happens, it also causes comicvine to become unreachable via browser

**Comment by evilhero** [comment]
I'm guessing it's probably due to how CV is rate-limiting requests now and that Wolverine is requesting 10 pages worth of results and it's just saying nope for w/e reason.

It seems like sometimes changing the cv_user_agent value in the config.ini will allow users to connect with better results, as long as you enter in a more current user_agent than the one that is the default atm.  You can browse to https://www.whatismybrowser.com/detect/what-is-my-user-agent/ and change the value in the config.ini to whatever it shows on that page.

If you can mimic your browser's user_agent string, it could also help as it seems that if you get flagged for the rate-limit (or w/e CV is calling it nowadays), you also won't be able to browse CV until it's lifted, usually a few minutes worth.

**Comment by Roshri** [comment]
Changed to the user agent to latest firefox and now it's working, thanks!
