### ISSUE TITLE
What happens to the interface in the latest version?

### ISSUE THREAD

**Issue by bulletproof2k** [mylar3/mylar3#1530]
- OS: Windows 11 Pro
 - 1920x1080
 - http://localhost:8090/home (On the other tabs, the interface does not move out and looks fine)
 
This repetition is also confusing: "Version: v0.8.0, v0,8.0 (master)"

After the update, the lower part of the interface moved to the left side of the screen.
 
![2024-03-14_12-02-00](https://github.com/mylar3/mylar3/assets/1818579/6537ec6e-bcbb-42f8-8745-d5a80ceb49ea)

**Comment by bulletproof2k** [comment]
@evilhero I have done all of the above, the problem is not solved.

**Comment by evilhero** [comment]
Did you check the watchlist for anything that was being flagged as being colour coded (they'll be easy to find).

I can't reproduce this, so I'm guessing it's probably due to one of your series titles causing some boundary issues with the way the css is being lined up for some reason.

Unfortunately until I can reproduce it, I can't fix it.

**Comment by bulletproof2k** [comment]
> Did you check the watchlist for anything that was being flagged as being colour coded (they'll be easy to find).
> 
> I can't reproduce this, so I'm guessing it's probably due to one of your series titles causing some boundary issues with the way the css is being lined up for some reason.
> 
> Unfortunately until I can reproduce it, I can't fix it.

By a "watchlist", do you mean a readinglist?
What needs to be done so that you can reproduce it?

**Comment by evilhero** [comment]
The watchlist is the main index page - the page that shows everything that mylar is monitoring and is having the display problem for you.

Like i said above, it's probably due to a series on your watchlist causing a problem (whether the series or just the flagging of it). If it's a series I should be able to replicate the display issue if I know the series causing the issue. If it's due to the new colour coding (flagging), knowing what status is causing the issue can help as well.

You can generate a carepackage and attach that to the issue (or put it on wormhole, mega, etc)... If I had the same db file you're using it's possible it could be replicated outside of your environment.

**Comment by bulletproof2k** [comment]
@evilhero 
How do I generate a carepackage?
I can just copy the files from the Mylar folder and put them somewhere. 🤔

**Comment by evilhero** [comment]
It's easier (and safer) to generate a carepackage since it removes all personal information from your log /config files and includes the db as well as an environmental snapshot.

See [here](https://mylarcomics.com/docs/guides/carepackage) on how to generate one from within mylar.

**Comment by bulletproof2k** [comment]
@evilhero 
[carepackage_v0.8.0, v0,8.0.zip](https://github.com/mylar3/mylar3/files/14607016/carepackage_v0.8.0.v0.8.0.zip)
I was pleasantly surprised to learn that Milar has its own website 😊

**Comment by evilhero** [comment]
Seems like it's an issue with the alpha index being used on the page. You can disable alpha indexing by setting the ``alpha_index = False`` in the config.ini with mylar not running.

The alpha index, while it has everything seperated based on the first letter of a series, does have shortcomings with displaying large libraries (takes a bit to load the main page).

The non-alpha index page loads everything dynamically so it's much quicker to display, but no alphabetical seperation by letter so you need to use the filter box more.

I'll look into this and see if I can get a patch out, but unsure of the timeline atm for it.

**Comment by bulletproof2k** [comment]
`alphaindex = False` No, unfortunately it didn't help 🙁

**Comment by evilhero** [comment]
If mylar was shutdown when you changed the config.ini, then you probably have to clear the browser cache or have your browser go incognito. 

Using a different browser would retain the previous time you tested against it earlier today, resulting in the same problem.
