### ISSUE TITLE
DDL Issue Number incorrect parsing causes failed match when searching for issue.

### ISSUE THREAD

**Issue by rboylesDev** [mylar3/mylar3#1565]
**Describe the bug**

When searching for issue 68 with DDL(GetComics), issue is found but result's issue number gets parsed as "68000" and then does not match the searched for issue number.

**CarePackage**

[carepackage_None_(master).zip](https://github.com/user-attachments/files/16852072/carepackage_None_.master.zip)

**Environment (please complete the following information):**
 - OS: Gentoo 6.1.67
 - Branch / commit: master/ca4a373

**Additional information**
Add any other information about the problem here.

**Comment by falo2k** [comment]
Your logs cut off before it gets to what you describe, but is that not just the matching check for avoiding decimal issues?  i.e. it's multiplying both sides by 1000 and comparing integers (hence Int_IssueNumber in the database).

**Comment by evilhero** [comment]
This is not a problem - the 68000 is the integer value of Issue 68. It's working as intended like was mentioned above it's just to help with  parsing out decimals and alpha issues. Unfortunately we can't see the last actual search since it's cut off in the logs, so the following is addressing stuff that you may have already fixed prior. 

Your logs say that you have a blank newznab entry so it can't resolve any search requests, which is probably causing it to fail on search requests.

Turn off experimental, set your downloader to use sab instead of blackhole (just leave the sab entry blank), and make sure the use newznab option is unchecked. Experimental is returning errors, and it's a experimental for a reason, so best to not even use it if it's throwing errors.
