### ISSUE TITLE
Entire series marked as Snatched with the same file

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#201]
**Describe the bug**
Mylar set all of the Wanted comics of a series to Snatched with the same NZB ID. I had manually searched for issues 1 and 2, and the remaining 30+ issues all got flagged as Snatched at the same time

**CarePackage**
Care package is 169MB for some reason, so here are the logs:
https://pastebin.com/6CUqYgBD

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Branch / commit: Master / a5e12b5c11864a4ecaf3f806aef47c942d062ae3

**Additional information**
N/A

**Comment by evilhero** [comment]
It looks like it figured out that the given issue 1 was inside of a DDL pack, and then failed to retrieve it (no idea why atm, just according to the log it couldn't). Once it failed to retrieve it, it retried the search for another item, but still had the pack info in it's memory and basically assigned the pack info from the DDL to an nzb download that just was for the same issue (not a pack, since it doesn't consider nzb's as pack eligible, but it does for DDL/32P).

I'll have to look into this some more, but it seems like it's just a weird glitch that's due to using DDL + a newznab.

**Comment by barbequesauce** [comment]
Is this still happening?

**Comment by Serneum** [comment]
It's been a while since I've added a new comic series that wasn't a brand new series with just one issue, so I can't confirm either way. I'll mark this as closed and reopen it if it happens again
