### ISSUE TITLE
Not post processing downloaded files

### ISSUE THREAD

**Issue by crobibero** [mylar3/mylar3#210]
**Describe the bug**
Mylar3 not importing files after download or on manual import

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4364152/carepackage.zip)

**Environment (please complete the following information):**
 - OS: [https://hub.docker.com/r/hotio/mylar3](Docker) - debian host
 - Branch / commit: Version: v0.3.3 ( master) 

**Additional information**

The files have correct permissions within the container, and the destination folder has correct permissions. 
```
root@9eba4a3bf964:/# ls -l /virtual/media/comics/downloads/
total 16
drwxrwxrwx 2 hotio hotio 4096 Mar 21 16:34 Once.Future.001.2019.digital.Son.of.Ultron-Empire
drwxrwxrwx 2 hotio hotio 4096 Mar 21 16:33 Once.Future.002.2019.digital.Son.of.Ultron-Empire
drwxrwxrwx 2 hotio hotio 4096 Mar 21 16:33 Once.Future.003.2019.digital.Son.of.Ultron-Empire
drwxrwxrwx 2 hotio hotio 4096 Mar 21 16:33 Once.Future.005.2019.digital.Son.of.Ultron-Empire
```

I had the same issue with mylar2

**Comment by barbequesauce** [comment]
likely it's the naming convention - is this meant to match "Once & Future"? If so, try setting your Alternate File-Naming to "Once.Future"...

**Comment by crobibero** [comment]
Yes, this was meant to match `Once & Future`. I didn't have any luck after adding the Alternate File-Naming.

I switched to testing with Wonder Woman so I don't have any special characters.

[wonder_woman_222.log](https://github.com/mylar3/mylar3/files/4364399/wonder_woman_222.log)



Folder contents:
```
root@6384fd44593e:/# ls -l  /data/completed/comics/Wonder.Woman.222.2005.digital-Empire
total 29576
-rw-rw-rw- 1 hotio hotio     3244 Mar 21 18:41 '[3+4] '\''75ffe6a1f0fec699d1806878443c9252d56fbf61'\'' yEnc (1+1)'
-rw-rw-rw- 1 hotio hotio 30278437 Jan  5 05:55  75ffe6a1f0fec699d1806878443c9252d56fbf61.cbz
```

Manual Run:
```
21-Mar-2020 18:49:10 - INFO    :: mylar.post_process.819 : CP Server Thread-8 : Starting postprocessing for : Manual Run
21-Mar-2020 18:49:10 - DEBUG   :: mylar.Process.364 : Thread-15 : [POST-PROCESSING] nzb name: Manual Run
21-Mar-2020 18:49:10 - DEBUG   :: mylar.Process.365 : Thread-15 : [POST-PROCESSING] nzb folder: /data/completed/comics
21-Mar-2020 18:49:10 - DEBUG   :: mylar.Process.373 : Thread-15 : [POST-PROCESSING] Manual Run Post-Processing enabled.
21-Mar-2020 18:49:10 - DEBUG   :: mylar.Process.405 : Thread-15 : [POST-PROCESSING] Manual Run initiated
21-Mar-2020 18:49:10 - INFO    :: mylar.traverse_directories.1492 : Thread-15 : there are 1 files.
21-Mar-2020 18:49:10 - DEBUG   :: mylar.listFiles.144 : Thread-15 : [FILENAME]: 75ffe6a1f0fec699d1806878443c9252d56fbf61.cbz
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.225 : Thread-15 : [CORRECTION] Sub-directory found. Altering path configuration.
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.227 : Thread-15 : [SUB-PATH] Checking Folder Name for more information.
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.229 : Thread-15 : [SUB-PATH] Original Path : /data/completed/comics
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.230 : Thread-15 : [SUB-PATH] Sub-directory : /data/completed/comics/Wonder.Woman.222.2005.digital-Empire
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.243 : Thread-15 : [SUB-PATH] subpath set to : Wonder.Woman.222.2005.digital-Empire
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.365 : Thread-15 : Improperly formatted filename - there is no seperation using appropriate characters between wording.
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.368 : Thread-15 : NEW split_file3: ['75ffe6a1f0fec699d1806878443c9252d56fbf61']
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.436 : Thread-15 : NEWLY SPLIT REORGD: ['75', 'ffe6a1f0fec699d1806878443c9252d56fbf61']
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.802 : Thread-15 : datecheck: []
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.853 : Thread-15 : No year present within title - ignoring as a variable.
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.856 : Thread-15 : highest_series_position: 2
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.954 : Thread-15 : issue_position: 2
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.979 : Thread-15 : No issue number present in filename.
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.1116 : Thread-15 : sf_highest_series_pos: ['75', 'ffe6a1f0fec699d1806878443c9252d56fbf61']
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.1168 : Thread-15 : series title possibly: 75 ffe6a1f0fec699d1806878443c9252d56fbf61
21-Mar-2020 18:49:10 - DEBUG   :: mylar.parseit.1207 : Thread-15 : Possible UNKNOWN TPB/GN detected - no issue number present, no clarification in filename, but volume present with series title
21-Mar-2020 18:49:10 - INFO    :: mylar.Process.415 : Thread-15 : I have located 1 files that I should be able to post-process. Continuing...
21-Mar-2020 18:49:10 - DEBUG   :: mylar.Process.1336 : Thread-15 : [POST-PROCESSING] There are 0 files found that match on your watchlist, 0 files are considered one-off's, and 1 files do not match anything
21-Mar-2020 18:49:10 - INFO    :: mylar.Process.1624 : Thread-15 : [POST-PROCESSING] No matches for Manual Run ... exiting.
```

**Comment by evilhero** [comment]
I believe @barbequesauce meant Alternate Search Name. In order to match search/post-processing titles that are different than what the series title is, you need to put something in that field on the series detail page. Once you do that, if it matches to that name it will be able to post-process it properly.

Also, as an FYI, ``75ffe6a1f0fec699d1806878443c9252d56fbf61'`` is not a valid filename for Mylar to be able to parse, so even if you had it in the right field above it wouldn't match anyways. Your download client is screwing up the filenames after it downloads it (ie. it's not renaming the obfuscated names) - I'm guessing it's from an nzb client of some sort.

**Comment by crobibero** [comment]
@evilhero - Thanks for the renaming tip, I'm very new to nzb. I now have the file being named correctly. It seems like the post processing is running before the rename is complete as the file is being imported correctly when manually running the post processor or enabling folder monitoring but not through `AUTO-COMPLETE-NZB`.

**Comment by evilhero** [comment]
You cannot run manually post-processing at the same time you have CDH if they're both pointing to the same download location. You'll get a race condition where one will be in the middle of post-processing when the other starts, and they'll lock each other up/cause an error/go boom.

There's also no need to set Folder Monitor to monitor anything that your nzb client downloads into (that's what CDH does). If for some reason it doesn't post-process, then you'd do a manual post-proccessing against a temporary folder that is outside of the download location so you don't get dual runs happening.

**Comment by crobibero** [comment]
I think I found the issue- I'm trying to do something like the `ComicRN.py` post processing script, so the automatic post processing happens before the rename script runs. The folder watch process seems to be working, so I'll just have to run with that. 

Is it possible to have mylar always remove the folder- even if it's not empty?

**Comment by evilhero** [comment]
Yeah you can't have ComicRN and CDH enabled simultaneously - it's just not gonna work. They'll hammer each other and one will work partially, and the other will fail completely. 

For the most part, enabling just CDH is the better option for most people as it brings with it better issue recognition when post-processing and more reliability. ComicRN has to parse the filename for all the information which isn't as reliable as knowing in advance what the series/issue it is prior to initiating the post-processing.

CDH, like ComicRN, will remove the folders that SABnzbd/NZBget generates (since it usually drops the cbr/cbz file into a subdirectory called after the nzbname itself). Mylar will only remove the folder that has the given issue within it, it won't touch anything else.

**Comment by crobibero** [comment]
The issue I ran into is the file name is obfuscated so I have to run this script as a post processing script: 
https://github.com/sabnzbd/sabnzbd/blob/develop/scripts/Deobfuscate.py

I'm not sure how to best post process, but I know CDH attempts to process before the deobfucation is complete

Re: folder removal
I have a single leftover file that ends in `yEnc (1+1)` which is preventing Mylar from removing the folder.

**Comment by evilhero** [comment]
Sounds like your indexer is kinda buttugly. What indexer are you taking the nzbs from as normally most quality indexers would do the obfuscation for you so you shouldn't have to run anything thereafter (that's kinda why they should be asking for $$$).

The CDH wouldn't adhere to the pre/post scripts for obvious reasons, at least for post Processing. I'll look into letting pre-processing attempt to work but not sure how that'll work as them we have to intercept information instead of just passing it thru. In that particular case if you're running a pre script, then comicRN would be your best bet yes, and it should remove any empty folders thereafter (if it can't its probably due to permissions)

**Comment by Otsdarva68** [comment]
I'm having this same issue, but it's with all books. Occasionally, post-processing occurs as it's supposed to, but I can't determine what makes the difference. Let me know if I should start a new issue, and any additional info to add.

[Care Package](https://1drv.ms/u/s!AjMssK4Zom7kgbI0iEyNtOs60cqMsw?e=mSQxJc)

Environment
OS: Archlinux
Branch: v0.3.3 (master)

**Comment by barbequesauce** [comment]
There's a lot going on in your logs @Otsdarva68 - I'll move yours to a new issue with an ask...

**Comment by DrSeussFreak** [comment]
I am having this issue as well, I have a path "/torrents/done" where I have been dropping files for auto-import, and it has always worked UNTIL I enabled deluge.  It is set as Deluge Move to Path, but it is not finding files I put there.

**Comment by DrSeussFreak** [comment]
Here is a carepackage

[carepackage.zip](https://github.com/mylar3/mylar3/files/4393974/carepackage.zip)

Did you get rid of logs in the UI?  I cannot find it

Version: 848a6e040f9083f6dc60d2984b2fd5080ec5ee8b (python3-dev)

**Comment by barbequesauce** [comment]
@DrSeussFreak are you ok here? Can we close the issue?

**Comment by DrSeussFreak** [comment]
yes, we are, thanks!
