### ISSUE TITLE
PP not functional

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#212]
I'm having this same issue, but it's with all books. Occasionally, post-processing occurs as it's supposed to, but I can't determine what makes the difference. Let me know if I should start a new issue, and any additional info to add.

[Care Package](https://1drv.ms/u/s!AjMssK4Zom7kgbI0iEyNtOs60cqMsw?e=mSQxJc)

Environment
OS: Archlinux, github repo
Branch: v0.3.3 (master)

_Originally posted by @Otsdarva68 in https://github.com/mylar3/mylar3/issues/210#issuecomment-602232898_

**Comment by barbequesauce** [comment]
Can you please try manually pp'ing one issue, then post a clean carepackage and tell us the filename... right now it's a needle in a haystack.

Also - how many issues are on your wanted list / how many files are in your directory waiting to get pp'd? Both of these have an impact...

**Comment by Otsdarva68** [comment]
So I tried it with one issue and then 3 issues and they all worked fine. It was when I tried 20 issues at once that the PP did not kick in once the downloads were done. N.B. there is also some mismatching in these issues of black panther, not worried about that right now.

[Fresh care package](https://1drv.ms/u/s!AjMssK4Zom7kgbI1lTfxC9oqNLlMdw?e=YHP0Dt)

Currently have 25 issues on my wanted list. 

There are currently 151 files in the completed download directory. The majority of them were postprocessed successfully by the previous version of mylar.

Will reducing that number improve performance? I'm noticing high cpu usage.


Successes:
The Last God 002 (2020) (Digital) (Zone-Empire).cbr >

The Last God 003 (2020) (Digital) (Oracle-SWA).cbr >
The Last God 004 (2020) (Digital) (Oracle-SWA).cbr >
The Last God 005 (2020) (Digital) (Zone-Empire).cbr >

Not PP'd:
Black Panther ([001-021]) ([2018-2020]) (Digital) (Zone-Empire).cbr

**Comment by evilhero** [comment]
```Black Panther ([001-021]) ([2018-2020]) (Digital) (Zone-Empire).cbr``` is not a valid filename. If it's meant to be a collection/tpb then it has to be labelled as such so as to correspond to the series on your watchlist. Mylar expects to either have a singular issue number, or no issue number. Having multiples will throw off the file parser and it will end up just ignoring it due to the parsing failure.

Haven't looked at the carepackage just yet - that's just from that excerpt you provided above.

**Comment by Otsdarva68** [comment]
I'm sorry, that wasn't meant to be a single filename. It's a range of filenames, I was just too lazy to paste them all out.

**Comment by barbequesauce** [comment]
Can you give a filename that's failing? I'm sifting through a beach looking for a blue grain of sand...

**Comment by Otsdarva68** [comment]
Black Panther (001) (2018) (Digital) (Zone-Empire).cbr

**Comment by evilhero** [comment]
Having ```(001)``` in brackets is throwing off the parser as its not a recognizable naming format. Not sure if it will be t one point as being able to parse that will probably throw off other aspects of the parser. If that's how your files are named, you're going to have to manually  remove the brackets around the issue number if you want mylar to post-process / manage those issues.

**Comment by Otsdarva68** [comment]
[Fresh care package](https://1drv.ms/u/s!AjMssK4Zom7kgbI2zfN9dFIJnLBF0Q?e=4uAQum) (pressed all the clear buttons in history, then cleared web logs, hoping that's fresh).

For this one I added "Ironheart" to my library and let Sabnzbd download all the issues (1 failed, but that's not a mylar problem). They downloaded successfully, but postprocessing did not occur. If I go to manual post processing and point it to my download directory, everything works totally fine, copying the files to the mylar directory and renaming them. Here are the filenames of the issues that were successfully downloaded but not postprocessed:

`
Ironheart 002 (2019) (Digital) (Zone-Empire).cbr
Ironheart 003 (2019) (Digital) (Zone-Empire).cbr
Ironheart 004 (2019) (Digital) (Zone-Empire).cbr
Ironheart 005 (2019) (Digital) (Zone-Empire).cbr
Ironheart 006 (2019) (Digital) (Zone-Empire).cbr
Ironheart 007 (2019) (Digital) (Zone-Empire).cbr
Ironheart 008 (2019) (Digital) (Zone-Empire).cbr
Ironheart 009 (2019) (Digital) (Zone-Empire).cbr
Ironheart 010 (2019) (Digital) (Zone-Empire).cbr
Ironheart 011 (2019) (Digital) (Zone-Empire).cbr
Ironheart 012 (2020) (Digital) (Zone-Empire).cbr
`

**Comment by barbequesauce** [comment]
Yeah - in general we're guiding people to use CDH instead of ComicRN - it's far more stable. Try switching over and see what happens...

**Comment by Otsdarva68** [comment]
I'm sorry; I was unclear yet again. I'm using CDH now. ComicRN was what I was using on the old platform.

**Comment by Serneum** [comment]
I'm thinking I'm having a similar issue even after the help in #217. Last night, I had quite a few issues download, and then no post-processing occurred, even when using CDH. Running a manual post-process on the issues did work. I have a new issue that did it 5:51:24, but an issue at 5:51:39 post-processed just fine. I'm including my [carepackage-first.zip](https://github.com/mylar3/mylar3/files/4387475/carepackage.zip). Debug logging was on overnight, so there will be a lot in there. The filename for the unprocessed comic is `Hidden Society 002 (2020) (digital) (Son of Ultron-Empire).cbr`, which looks fine. I ran another post-process with debug logging on just to be safe, and here is that file: [carepackage-second.zip](https://github.com/mylar3/mylar3/files/4387514/carepackage.zip)


Interestingly, python3 is also using 100% of my CPU right now as well, and Mylar is running very slowly because of it. Not sure if it's related but I figured it was worth mentioning just in case.
![image](https://user-images.githubusercontent.com/1091716/77652750-2442b700-6f45-11ea-9722-cb429958b383.png)

**Comment by Otsdarva68** [comment]
I've also noted high CPU usage and slow mylar performance as well.

**Comment by evilhero** [comment]
@Serneum , I don't see any CDH logging going on in that first log. and the 2nd log is the same as the first save for the post-process of the single item that was successful. I would guess based off of that the CDH experienced an error somewhere prior to the log starting, and as a result couldn't restart and all the subsequent monitors it does (basically monitors the history of SAB for completed items) never happened, so the items got sent but not processed.

In order to help out more, we'd have to capture the traceback that caused the CDH queue to completely die on you (the only fix atm for a dead queue is to restart the application). 

It's possible that this could account for high CPU usage as well if the items are being sent to it and it's locked up, they'll just keep on being sent to nowhere when they're expecting something back (or continuously looping looking for something).

**Comment by Serneum** [comment]
@evilhero Is that traceback something that will definitely be in the log if it happens again? If so, I'll leave debug logging on overnight and look through them in the morning if anything seems off. Just trying to figure out what myself and @Otsdarva68 can do to help get the appropriate logs if we're seeing the same issue

**Comment by Otsdarva68** [comment]
I cleared my logs and restarted the application. I'll take a look and post a care package the next time mylar pulls some issues

**Comment by Otsdarva68** [comment]
I cleared my logs and restarted the application, then tried adding a book to the watchlist. Looking at the logs, it looks like post-processing is never initiated on completed downloads, although I know absolutely nothing about reading logs. Here's the relevant chunk of time in a pastebin so you don't have to sort through that giant mess again: https://pastebin.com/KxGQZDHf

I did see an error pop up a couple of times, though I can't make heads or tails of it.

```
26-Mar-2020 16:12:06 - ERROR   :: mylar.excepthook.315 : Thread-15 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mylar3/mylar/search.py", line 1929, in searchIssueIDList
    foundNZB, prov = search_init(comic['ComicName'], issue['Issue_Number'], str(IssueYear), comic['ComicYear'], Publisher, issue['IssueDate'], issue['ReleaseDate'], issue['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, ComicID=issue['ComicID'], filesafe=comic['ComicName_Filesafe'], allow_packs=AllowPacks, torrentid_32p=TorrentID_32p, digitaldate=issue['DigitalDate'], booktype=booktype)
  File "/opt/mylar3/mylar/search.py", line 360, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/opt/mylar3/mylar/search.py", line 1538, in NZB_SEARCH
    if mylar.COMICINFO[0]['pack'] is True:
IndexError: list index out of range
```

**Comment by evilhero** [comment]
The ```mylar.COMICINFO``` thing is a remnant of when the manual select from a list of available downloads was introduced in Mylar, but then had to be subsequently removed due to some display issues. It's not being used now for anything related to the manual selection, but it is the core of how Mylar moves the relevant issue information back and forth amongst the different modules, so I can't remove it entirely (plus the manual selection option is coming back at some point).

I did realise something tho in looking more at the log, and the code - if you have a bunch of issues that are queued up to be searched (ie. force search, manually searching for issues via the magnifying glass, auto-searches via scheduler) those will fire off fine. Until such time as one starts manually adding items by: 
- marking several issues as Wanted via checkboxes on the series page and choosing Wanted as a Status via the series list
- manually checking for issues via the button on the pull-list page
- using the skipped2wanted option on the seriesdetaill page) 
When this happens 2 searches are running simultaneously, which isn't suppose to happen. This deadlocks the mylar.COMICINFO variable so it can't read the required information when it occurs and well yeah, search goes boom - which freezes the CDH from working from the looks of it, as well as the search, and probably various other things I haven't figured out yet.

So yeah, short version - working thru this tonight and gonna see if I can push something out that hopefully will stop this from happening while not breaking anything else in doing so...

**Comment by evilhero** [comment]
@Otsdarva68 , @Serneum  - can you guys update to the latest python3-dev branch and try the latest fix when you get a chance? Your issues might be resolved with it, but based on your issues you're going to have to test it before we'll know for sure.

**Comment by Serneum** [comment]
Done. I'll keep you posted

**Comment by Otsdarva68** [comment]
ran `git checkout python3-dev`
rebooted machine
Let mylar run its automatic startup scan. The results look unchanged to me; mylar found issues and downloaded them with sabnzbd, but they did not post process, except for one issue which did eventually: `Amazing Spider-Man 042 (2020) (Digital) (Zone-Empire).cbr`

[Here is the care package](https://1drv.ms/u/s!AjMssK4Zom7kgbJD91-rmKX9SNPL7A?e=hrhaMy)

**Comment by evilhero** [comment]
@Otsdarva68 Did you do a git pull after the checkout? Did you change the git_branch in the config.ini to the python3-dev branch so it knows what to check against for updates (with mylar not running when editing the ini)?

**Comment by Otsdarva68** [comment]
I did `git pull` after checkout, yes. my config.ini had `git_branch = None`, I changed it to `git_branch = python3-dev` and did another git pull which returned `Already up to date.`

**Comment by evilhero** [comment]
@Otsdarva68 you're getting db errors in the logs now - do you have the mylar.db file open in another application/command line while Mylar is still running ?

**Comment by Otsdarva68** [comment]
Not intentionally, not as far as I know. But I do still have the old mylar directory, even though it's not running. Should I remove that and see if it helps?

**Comment by evilhero** [comment]
Unless your mylar3 is pointing to the old mylar db it shouldn't matter at all. If you copied the db over to the new installation there shouldn't be any points to the old one (unless you're starting it up via daemon and manually forcing the data_dir option).

**Comment by Otsdarva68** [comment]
I *am* starting it up via daemon, but not forcing the data_dir option. Below is the systemd file. I'm going to archive the old directory just in case I missed something. If it breaks mylar, we should have an answer

```
# Mylar.service to run as $USER with config in $DATA_DIR

[Unit]
Description=starts instance of Mylar
After=network-online.target

[Service]
User=hari
Group=hari
ExecStart=/usr/bin/python /opt/mylar3/Mylar.py -v --daemon --nolaunch
GuessMainPID=no
Type=forking
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by Otsdarva68** [comment]
Unsurprisingly, moving the old directory didn't break the install. I also just remembered that the webui already told me the data directory was properly located at `/opt/mylar3`

**Comment by evilhero** [comment]
@Otsdarva68 do you have any scripts running on your SABnzbd client either based on download location or by the comics category  - or any scripts running after something downloads ? (ie. do you still have ComicRN or nzb2mylar or something attached to the category). I see the start of the download monitor but then when it goes to reference the download in the history of the download client it's not returning anything and dying for some reason (which Mylar doesn't log since it's outside of Mylar).

**Comment by Otsdarva68** [comment]
I removed any references to ComicRN in sab when I migrated to the new mylar. In the category settings in sab, 'Priority', 'Processing', and 'Script' are all set to "Default".

**Comment by evilhero** [comment]
Can you try to set your SABnzbd download directory location to the location where your SABnzbd client downloads comics to ? (ie. what you have in your sabnzbd client for the folder/path location basically) And then save the configuration, and see if that does anything? It shouldn't matter, but at this point it's worth a shot...

**Comment by Otsdarva68** [comment]
Sure. Just so I do it correctly: my current sab download directory is /drive/download, and the category setting has it download anything with a comics category to /drive/download/comics. You want me to make the entire download path /drive/download/comics, and remove the category setting? Or is there some setting in mylar you want me to change?

**Comment by evilhero** [comment]
If you could just update the sabnzbd download directory location within Mylar (under the SABnzbd configuration section) so that it points to ```/drive/downloads/comics``` that's all that's needed. 

You don't have to change anything in your SABnzbd client as long as the download location there for comics is identical to the sabnzbd download directory location within Mylar (this is all just for testing purposes, obviously it shouldn't matter if the option is used or not in this particular case)

**Comment by Otsdarva68** [comment]
I don't have that option enabled in settings because sab and mylar are on the same machine. All that's in my sab settings are host, username & password, API, and category (set to comics), then I have "Enable Completed Download Handling" checked.

**Comment by barbequesauce** [comment]
Can you grab a fresh log of the problem in action please, preferably through carepackage?

**Comment by Otsdarva68** [comment]
Added some books to my watchlist, then waited for an automatic search (didn't run the search by marking them as watched like I did before). Looks like the issues the first two issues that got snatched were PP'd, and none of the others did. [https://1drv.ms/u/s!AjMssK4Zom7kgbI0iEyNtOs60cqMsw?e=sVsUxB](Here's the carepackage.)

Files downloaded and PP'd:
Deadpool 004 (2020) (Digital) (Zone-Empire).cbr
Superman's Pal Jimmy Olsen 009 (2020) (digital) (Son of Ultron-Empire).cbr
Files downloaded and NOT PP'd:
Deadpool 001 (2020) (Digital-Empire).cbz
Deadpool 002 (2020) (Digital) (Zone-Empire).cbr
Deadpool 003 (2020) (Digital) (Zone-Empire).cbr
Doctor Doom 001 (2019) (Digital) (Zone-Empire).cbr
Doctor Doom 002 (2020) (Oroboros-DCP).cbr
Doctor Doom 003 (2020) (digital) (St Nicholas-DCP).cbr
Doctor Doom 004 (2020) (Digital) (Zone-Empire).cbr
Doctor Doom 005 (2020) (Digital) (Zone-Empire).cbr
Doctor Doom 006 (2020) (Digital) (Zone-Empire).cbr
Dr. Strange - Surgeon Supreme 001 (2020) (Digital) (Zone-Empire).cbr
Dr. Strange - Surgeon Supreme 002 (2020) (Digital) (Zone-Empire).cbr
Dr. Strange - Surgeon Supreme 003 (2020) (Digital) (Zone-Empire).cbr
Dr. Strange - Surgeon Supreme 004 (2020) (Digital) (Zone-Empire).cbr
Spider-Man Noir 001 (2020) (Digital) (Zone-Empire).cbr
Superman's Pal, Jimmy Olsen 001 (DC) (Sep-Oct 1954) (c2c) (Superscan).cbr
Superman's Pal Jimmy Olsen 02 (of 012) (2019) (Webrip) (The Last Kryptonian-DCP).cbr
Superman's Pal Jimmy Olsen 003 (2019) (digital) (Son of Ultron-Empire).cbr
Supermans Pal Jimmy Olsen 04 (of 012) (2019) (Webrip) (The Last Kryptonian-DCP).cbr
Superman's Pal Jimmy Olsen 005 (2020) (digital) (Son of Ultron-Empire).cbr
Superman's Pal Jimmy Olsen 06 (of 012) (2020) (Webrip) (The Last Kryptonian-DCP).cbr
Superman's Pal Jimmy Olsen 007 (2020) (digital) (Son of Ultron-Empire).cbr
Superman's Pal Jimmy Olsen 008 (2020) (digital) (Son of Ultron-Empire).cbr

**Comment by barbequesauce** [comment]
> If you could just update the sabnzbd download directory location within Mylar (under the SABnzbd configuration section) so that it points to `/drive/downloads/comics` that's all that's needed.

@Otsdarva68 did you see this comment? Wondering if this helped? Logs show that this change should fix it...

**Comment by Otsdarva68** [comment]
@barbequesauce I saw that comment and replied to it. I don't have a setting for sab's download directory, just a category setting which is set to 'comics'. [Please see this screenshot for exactly what the configuration looks like.](https://ptpimg.me/lx3z13.png)

If mylar is looking for `/drive/downloads/comics` then I would like to change the directory its looking for, not send the downloads to a different drive.

**Comment by Nargath** [comment]
> @barbequesauce I saw that comment and replied to it. I don't have a setting for sab's download directory, just a category setting which is set to 'comics'. [Please see this screenshot for exactly what the configuration looks like.](https://ptpimg.me/lx3z13.png)

For what its worth, my PP isn't working either, nor is this setting appearing for me.
There is a download directory that appears when you ticket "Are Mylar / SABnzbd on separate machines. But the alert is pretty specific that its not needed if they're on the same box.

**Comment by Nargath** [comment]
Just for the sake of more data, I've also uploaded my care package.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4619446/carepackage.zip)

I cleared the log, readded a new series (X-Men/Fantastic Four), marked them all as Wanted, and then forced the Auto Search job to run.
The files are still sitting in my SABnzbd complete folder (D:\Usenet\complete\Comics-Mylar), which is the same folder that is set in Mylar as my SABnzbd Download Directory.

**Comment by evilhero** [comment]
Can you confirm something - within your SABnzbd instance, do you have the option called ```Detect Duplicate Downloads``` or ```Check before download``` enabled ?(both are in Configuration / Switches)

It looks like SABnzbd is returning 2 different nzo_id's at different points in the post-processing. When Mylar submit's one, it gets the 1st nzo_id. It then tries to reference this nzo_id throughout the monitoring process to check for completion. However once it's completed, the nzo_id looks like it's been changed to something else - so it never matches.

The ```Detect Duplicate Downloads``` switch was causing problems for a heavy user years ago - and we determined that enabling/disabling that switch was that catalyst to the entire process for him at least. The ```Check before download``` switch was brought up in their forums but again, that was years ago. Just want to clarify your settings on that side if possible.

**Comment by Nargath** [comment]
> Can you confirm something - within your SABnzbd instance, do you have the option called `Detect Duplicate Downloads` or `Check before download` enabled ?(both are in Configuration / Switches)

Unfortunately both of those switches in my SABnzbd are currently Off/Unticked :(

**Comment by Otsdarva68** [comment]
They are off on my machine as well

**Comment by Nargath** [comment]
So I've upgraded to SABnzbd, just in case it was due to an incompatibility with Python37, and I saw something.
The file that Mylar is grabbing from NZBGeek has periods instead of spaces. Yet when SAB finishes downloading the NZB and puts it in its completed folder, those periods are now spaces.

Could it be that somewhere a rename is happening, so that Mylar is expecting something with a particular name, but its dumping out with a different name, therefore it can't find it for post processing?

I've ensured that Mylar's "Replace Spaces" option isn't selected, and that SAB's "Replace spaces in folder name" and "Use tags from indexer"

**Comment by Nargath** [comment]
Just for sake of completeness, this is my media-grabbing system now:
I've ripped out Python27 and installed 37 in its place.
Upgraded Mylar to 3 Development
Upgraded SABnzbd to 3.0.0 Alpha 2 (was failing previously on 2.3.9)
Sonarr and Radarr have not had significant updates that I'm aware of.

Sonarr and Radarr still function correctly, in both using their CDH and then bringing the file back, renaming it and placing it into the correct folders.

**Comment by Nargath** [comment]
Sorry for flooding a bit, but I've been digging into the SAB logs overnight
I've run a single comic through, and captured a clean SAB log for it.
its definitely building a placeholder NZO, and then removing the original one from Mylar.

Specifically line 73, just after it receives the api call to download the nzb from Mylar:
`2020-05-14 10:56:31,284::DEBUG::[nzbqueue:225] Creating placeholder NZO`
[sabnzbd.log](https://github.com/mylar3/mylar3/files/4625466/sabnzbd.log)

It could still be a config item, although I've defaulted everything I can think of back to defaults

**Comment by evilhero** [comment]
Under the switches tab in SABnzbd - do you have history retention set to something other than ```keep all jobs``` ?

I see this in your sab log:
```2020-05-14 10:56:53,895::INFO::[nzbstuff:1537] [sabnzbd\postproc.py.process_job] Purging data for job Avengers.of.the.Wastelands.001.2020.Digital.Zone-Empire (delete_all_data=True)```
Which says it's purging the item from your history and all traces there of. 

If this is true, Mylar will never be able to find any jobs that download since they're being wiped from your history the moment they're done. (Mylar literally checks the history 2seconds after the purge, and obviously can't find the nzo_id reference any longer).

**Comment by Nargath** [comment]
> Under the switches tab in SABnzbd - do you have history retention set to something other than `keep all jobs` ?

Nope, History Retention is set to 'Keep all jobs'

Going to try it again and see if that line appears in a new instance.

**Comment by evilhero** [comment]
I'm running 2.3.9 - and a quick check of my sabnbzd logs show how it handles it when it's working (I'm guessing?):
```
2020-01-31 21:59:32,081::INFO::[nzbstuff:1759] [N/A] Purging data for job SomeComic.087.2020.Digital.Zone-Empire (keep_basic=False, del_files=False)
2020-01-31 21:59:32,139::INFO::[database:272] Added job SomeComic.087.2020.Digital.Zone-Empire to history
```
and yours:
```
2020-05-14 15:47:11,635::INFO::[nzbstuff:1537] [sabnzbd\postproc.py.process_job] Purging data for job SomeComic.001.2020.Digital.Zone-Empire (delete_all_data=True)
2020-05-14 15:47:11,635::DEBUG::[filesystem:759] Removing dir recursively \\?\D:\Usenet\incomplete\SomeComic.Digital.Z
2020-05-14 15:47:11,637::DEBUG::[sorting:209] Found TV Show (SomeComic.001.2020.Digital.Zone-Empire)
2020-05-14 15:47:11,663::INFO::[database:290] Added job SomeComic.001.2020.Digital.Zone-Empire to history
2020-05-14 15:47:11,663::INFO::[postproc:123] Saving postproc queue
```
Not sure why your TV Sort is getting hit as well - but it looks like possibly the ```delete_all_data=True``` line on the version of sabnzbd you're running is doing something it shouldn't based on your settings.

**Comment by Nargath** [comment]
And the even weirder thing?
I uninstalled SAB completely and went back to 2.3.9, completely fresh and reconfigured from scratch.
AND IT STILL DOES IT.
I have to be doing something wrong.

**Comment by barbequesauce** [comment]
Any news here?

**Comment by barbequesauce** [comment]
Please reopen when you have news.
