### ISSUE TITLE
Intermittent Post-Processing Issues

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#217]
**Describe the bug**
Post-processing sometimes fails. I'm not sure if it's the same as #210 or #212, but I've seen this happen with Star Wars (2020) issue 4 (DDL), Lucifer (2018) issue 17 (nzb), and Ragnarok: The Breaking of Helheim (2019) issue 4 (DDL). 

**CarePackage**
I can't include my full care package because my db is huge (170mb), but I've removed that and uploaded the rest.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4378398/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - Branch / commit: master/9a04132

**Additional information**
The logs likely only include the Ragnarok attempt as I frequently need to restart my server (it seems to get stuck after processing a lot)

**Comment by barbequesauce** [comment]
Sorry - none of those examples show up in the logfiles.

Can you try a manual postprocess from the Manage screen please, while in debug?

**Comment by barbequesauce** [comment]
Also - as evilhero pointed out in 210 - what's the filename format that's failing?

**Comment by Serneum** [comment]
Downloading it myself, it looks like the Ragnarok comic has special characters in the name: `Ragnarök - The Breaking of Helheim 004 (2020) (digital) (Son of Ultron-Empire)` so a failure there wouldn't surprise me.
Star Wars is `Star Wars (2020-) 004 (2020) (Digital) (BlackManta-Empire)`, and I can see where that would fail on the `(2020-)` before the issue number as well.
Lucifer was `Lucifer 017 (2020) (digital) (Son of Ultron-Empire).cbr` which seems pretty normal.

Let me see if I can force Lucifer to be handled again with debug logging on and get back to you. I know I manually moved that one into the comics directory, rescanned, and then renamed and it worked fine.

**Comment by evilhero** [comment]
I'm seeing this in some of the logs: 
```24-Mar-2020 20:05:49 - WARNING :: mylar.downloadit.361 : DDL-QUEUE : [WARNING] Unable to retrieve remote file size - this is usually due to the page being behind a different click-bait/ad page. Error returned as : 'content-length'``` which basically means that it's linking to one of those ad-based sites that Mylar will not traverse on purpose. Usually in the past I've found that these exist for older issues (unless they changed things up again), but I'll re-run a few tests on my side to make sure the parser is working as expected.

I say 'as expected' because I also noticed in your logs that the download portion is failing on trying to retrieve the proper url from the link - so something else to look into (note both of these would only affect DDL downloads).

**Comment by Serneum** [comment]
It's very likely that that popped up on older issues as I recently lost my whole collection and I've been having to go manually grab them all and deal with those pages myself.

**Comment by Serneum** [comment]
Quick note, I ran `ps aux | grep ComicRN` and got

```
python ~/.sabnzbd/scripts/ComicRN.py ~/Downloads/complete/comics/Lucifer.017.2020.digital.Son.of.Ultron-Empire Lucifer.017.2020.digital.Son.of.Ultron-Empire.nzb Lucifer.017.2020.digital.Son.of.Ultron-Empire  comics alt.binaries.comics.dcp 0
```

I ran that and got
```
Traceback (most recent call last):
  File "~/.sabnzbd/scripts/ComicRN.py", line 22, in <module>
    sys.exit(autoProcessComics.processIssue(sys.argv[1], sys.argv[3], sys.argv[7], comicrn_version=comicrn_version))
IndexError: list index out of range
```
Manually searching after that failed

I switched to letting Mylar handle completed downloads and I'll see if that changes anything. The Lucifer comic is from an nzb and the files seem to be cleaned up even though it never shows up in the list of downloaded comics in Mylar's interface

**Comment by Serneum** [comment]
It may be a fluke, but allowing Mylar to handle the post-processing directly seems to have worked

**Comment by evilhero** [comment]
Yeah the ComicRN isn't a very reliable method - it works sure, but there are instances where it will trip on something really simple and can't recover. The CDH method is the method we've been telling everyone to use first if at all possible, as it's also more accurate since it can pass everything directly to the post-processor ahead of time without having to parse the information and do quirky db lookups based on the filename.

It looks like getcomics decided to change their urls again...*sigh*...I'll see if I can get this working again since now they've split it off a bunch of times and we have to account for all of them as a just in case method.

**Comment by Serneum** [comment]
Cool, I think ComicRN is just what I set up years ago and never got around to migrating over to letting Mylar handle it. I'll close this for now as it seems like part of the issue was file names, part of the issue with older comics was the ad-driven pages, and part of the issue was using ComicRN.

**Comment by evilhero** [comment]
FYI: I have this fixed now in my local repo - will push to python3-dev shortly. I updated the ddl parsing so that it will work with the new links, the main benefit being is that it will be able to successfully download + post-process packs again (which is what it was trying to download in your issue).
