### ISSUE TITLE
StoryArcs and Serie-Annual integration don't play nice

### ISSUE THREAD

**Issue by mvanlijden** [mylar3/mylar3#243]
**Describe the bug**
When you have enabled Serie-Annual integration, the StoryArc doesn't find annuals that are part of that StoryArc. For example the story arc of Shattered Grid from Power Rangers. It does not find the 2018 annual, even though it is collected in the series. 
When i still had the Annual as a separate comic the StoryArc would find it without any issue.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4437259/carepackage.zip)

**Environment (please complete the following information):**
 - OS: UnRaid with docker hotio/mylar3
 - Branch / commit: master [v0.3.3 - Double-crossed by Two-Face] 

**Additional information**
This bug was also present in mylar pre 3

**Comment by evilhero** [comment]
You make no distinction as to what it is that you're trying to do. Are you importing an existing arc into Mylar? Are you searching for an annual and you're saying it's not being picked up properly during post-processing? Where is it supposed to be finding the annual exactly ? 

If you're inquiring as to why Mylar cannot figure out why an annual to a series that doesn't exist already on your watchlist is not being picked up as an arc issue, it's fairly simple. In order for annual-integration to work properly with story arcs, the series has to exist on your watchlist with the annuals already tied to that given series (ie. they have to show up). It's like anything else, if the data isn't present for the item, Mylar has no way of knowing where something belongs, and it can't continually poll CV to figure out each & every item of an arc. And since CV doesn't attach annuals to series (annuals are considered separate volumes), the reliance on the annual-integration working properly falls entirely on Mylar.

Now if above statement is not what you were inquring about - you'll need to provide debug logs. The current logs provided are INFO level logs, which aren't helpful at all in figuring out what is going on.

**Comment by barbequesauce** [comment]
Any word on this, @mvanlijden ?
