### ISSUE TITLE
Unable to Tick "Enable Metadata Tagging"

### ISSUE THREAD

**Issue by Nargath** [mylar3/mylar3#281]
[carepackage-GUI.zip](https://github.com/mylar3/mylar3/files/4615946/carepackage-GUI.zip)
[Mylar - Manual Metadata.zip](https://github.com/mylar3/mylar3/files/4615952/Mylar.-.Manual.Metadata.zip)

I'm unable to have Save Changes accept my ticking the "Enable Metadata Tagging" on the Quality and Post Processing tab.
When I tick that option, then click Save Changes, it tells me "There was an error".

And if I force the option in config once Mylar is shut down, it refuses to start up again until I revert the config setting

**CarePackage**
I have1 CarePackage and a log.
One from just trying to save the option in the GUI - (CarePackage-GUI.zip)
The log and config is when I try and set the option in the config file (Mylar - Manual Metadata.zip)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: 26c9d786a3f3a597c55287d943758525ae732b7e (python3-dev)

**Comment by evilhero** [comment]
This is due to not having a valid ct_settingspath that is writable by the user running Mylar - basically Windows is blocking the creation of the default path. This has been discussed in #274, as well as resolved. Basically, set your ```ct_settingspath``` within the config.ini to ```D:\your path to mylar\.ComicTagger``` .

Also, there's no need to double post items on both here AND the forums within a short time frame of each other.

**Comment by Nargath** [comment]
Ah, not a problem
I'd tried searching for this, but obviously didn't choose the right wording for it!

And the forum post was my initial attempt to reaching out, until I released I wasn't able to attach files, logs, etc. Which is when I decided to post it here.
I'll delete the forum post now.
