### ISSUE TITLE
API getWanted returns 500 error

### ISSUE THREAD

**Issue by SenorSmartyPants** [mylar3/mylar3#282]
**Describe the bug**
http://host:8090/mylar/api?apikey=XXX&cmd=getWanted returns a 500 error.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/4624095/carepackage.zip)

**Environment (please complete the following information):**
 - OS: ARM Docker
 - Branch / commit: build 26c9d786a3f3a597c55287d943758525ae732b7e

**Additional information**
getUpcoming works

**Comment by evilhero** [comment]
Looks like there's some bytes objects being returned in the dict response and then it can't convert it to json because of the bytes. It's the Issue Name field that's causing problems, and I've seen this in the db where it's even displayed as ```b'this is the issue title.'``` - have to track down the culprit and then run a db conversion on the bytes column....

**Comment by SenorSmartyPants** [comment]
pulled from python3-dev today and API is working again.

**Comment by SenorSmartyPants** [comment]
And the problem is back again.
[carepackage.zip](https://github.com/mylar3/mylar3/files/4690256/carepackage.zip)

**Comment by evilhero** [comment]
Yep, was never meant to be totally fixed in PR #305 - was a partial attempt to stop the Issue Name field in the issues table from being written in the incorrect format going forward. In order to completely address this issue, everyone's DB has to have the Issue Name field converted properly so that the API can properly return the json response (amongst other things).  Should be in the python3-dev branch by the end of week barring any unforseen problems with the testing aspect (code is done, just testing variations now).

**Comment by barbequesauce** [comment]
Still an issue?
