### ISSUE TITLE
forked repo help

### ISSUE THREAD

**Issue by sukhysall** [mylar3/mylar3#290]
Created new issue rather then capture in an enhancement thread

@evilhero 
@barbequesauce 

So i cloned via the command:

git clone https://github.com/mylar3/mylar3.git --branch dark-theme mylar

And install from dark-theme branch has been fine.

However, having made a few changes so far (still need to do the data_table.css) I'm finding an error when trying to git push:

"remote: Permission to mylar3/mylar3.git denied to sukhysall.
fatal: unable to access 'https://github.com/mylar3/mylar3/': The requested URL returned error: 403"

Have I missed a step when initially doing the git clone?

**Comment by evilhero** [comment]
That's a normal response as you don't have the right permissions to post to the mylar3 repo (repo's are usually locked down on a per-person basis as opposed to an open one to limit things). 

What you need to do is actually fork the mylar3 repo first, and not clone it. You can fork it by going to the mylar3 repo page (https://github.com/mylar3/mylar3) and clicking on the fork icon in the upper right hand corner. This will create a mylar3 repo under your git user name (you'll have a link under your name pointing to your repo ie. ```https://github.com/sukhysall/mylar3```). 

At this point you should delete your previous git clone directory entirely (there are hidden files in the root that will muck up the next step otherwise). Then what you need to do is to do a git clone but pointing to your newly created forked repo (ie. ```git clone https://github.com/sukhysall/mylar3 -b dark-theme mylar```).  This will then allow you to push stuff to your repo without it affecting the main one. You do have to remember though to keep up with the mylar3 main repo by syncing it ([more info here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)), but doing Pull Requests become as simple as a few clicks via the github web interface after doing this.

**Comment by sukhysall** [comment]
Thanks for that. 

So you're above intructions I carried out with no issue and did another git clone (making sure to back up my changes so far - Phew!)

I following the link you pasted and I've so far been successful with the following:

1. Executed "git remote -v" and got the following output:

origin  https://github.com/sukhysall/mylar3 (fetch)
origin  https://github.com/sukhysall/mylar3 (push)

2. Executed"git remote add upstream https://github.com/mylar3/mylar3.git" and all good.

3. Executed "git remote -v" and got the following output

origin  https://github.com/sukhysall/mylar3 (fetch)
origin  https://github.com/sukhysall/mylar3 (push)
upstream        https://github.com/mylar3/mylar3.git (fetch)
upstream        https://github.com/mylar3/mylar3.git (push)

So far so good.

**Comment by barbequesauce** [comment]
@sukhysall Thanks again for your work on the carbon theme - it looks great!

**Comment by sukhysall** [comment]
@barbequesauce you're very welcome mate!

Ill keep an eye out for anything I might have missed. If you see anything just send us a screenshot and I'll fix it. 

Next steps is to look into good practice guides for color blindness and dark theme  so watch this space :)

**Comment by sukhysall** [comment]
Now I've figured out how to girl add commit and push, I can close off this issue.

@evilhero @barbequesauce 

Thanks again guys.
