### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by paulr24** [mylar3/mylar3#296]
So I am running Windows 10 and started to try to install Mylar3 but ran into issues and realized that it says "Python version 3.8+ of Mylar will not work on Windows due to some dependency issues." If I were to use Python 3.7.2+, should it work? Just want to check before I go down that rabbit hole and end up trying to troubleshoot for hours haha. Thanks!

**Comment by evilhero** [comment]
Python 3.8+ won't work due to the unrar-cffi dependency that is required by ComicTagger at the moment. The dev for CT also is the dev for unrar-cffi, but the unrar-cffi builds have stopped at 3.7x for Windows for some reason. I've been debating removing the requirement for unrar-cffi, or at least making it an optional component, as all it does is just speed up unrar'ing files abit.

So yeah, short story - if you use 3.7.5+ you'll be perfectly fine. I'm not 100% sure how 3.7.2 would work as I can't recall testing that exact version - most of the Windows tests thus far has been against a slightly higher python version (3.7.4+ if I recall) on Windows 10.

**Comment by paulr24** [comment]
Ah I see, thanks for the info!

While I have you here, I seem to be having issues after installing. I ran "py -m pip install -r requirements.txt" and everything came back "Requirement already satisfied" but it then said:

"WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command."

I ran the command and here is what I got in return:

C:\mylar3-0.3.6>python -m pip install --upgrade pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: pip in c:\python27\lib\site-packages (20.1.1)

When I run "python3 Mylar.py" it just returns me to "C:\mylar3-0.3.6>" without saying anything else, but then when I try going to http://localhost:8090/ it says that site can't be reached. One thing to note is that I do have Python 2.7 also installed (for other software) but I entered "py -3" so this should have run with version 3.7.2.

**Comment by evilhero** [comment]
If you have both py2 and py3 on your system, then you have 2 separate pip commands for each. It looks like just ```pip``` is pointing to your python2 installation. So anything run using ```pip``` will install it against the python2.7 branch. So you need to install the requirements.txt file against the correct pip version, which normally is ```pip3``` if you have another non-python3 version on your system.

Odds are using ```python3``` on the command line won't run anything since that command isn't tied to anything, I'm not sure what you ran with the command ```py -3```, if you're meaning your pip install it possibly could have been something like ```python3 -m pip3 install -r requirements.txt```.

Ie. Whatever command you use to access python from the command line (```python3```, ```py3```, etc), is the command you use when running Mylar (```python3 Mylar.py```) AND when doing the pip install as mentioned above.

**Comment by paulr24** [comment]
Thank you so much for being so responsive, I got Mylar up and running the other day! Still playing around with settings and such but loving it so far, your work is much appreciated!

**Comment by psychogun** [comment]
@paulr24, you could edit your environment variables so that the command `python3` from the command prompt leads to your python3 executable, regardless of your working directory: https://docs.python.org/3/using/windows.html#excursus-setting-environment-variables

Quick tip: start `mylar.py` with the `-v` option, which enables more aggressive logging (DEBUG): `python3 Mylar.py -v`. If you run into any problems, these guys would love to have DEBUG logs of everything- but sometimes you can use it to figure things out yourself (permissions issues, etc.)

Good luck!

**Comment by barbequesauce** [comment]
Hi @paulr24 - we good to close this?

**Comment by paulr24** [comment]
> @paulr24, you could edit your environment variables so that the command `python3` from the command prompt leads to your python3 executable, regardless of your working directory: https://docs.python.org/3/using/windows.html#excursus-setting-environment-variables
> 
> Quick tip: start `mylar.py` with the `-v` option, which enables more aggressive logging (DEBUG): `python3 Mylar.py -v`. If you run into any problems, these guys would love to have DEBUG logs of everything- but sometimes you can use it to figure things out yourself (permissions issues, etc.)
> 
> Good luck!

Got it, I will give that a try. Thanks!
