### ISSUE TITLE
encode('utf-8') should be removed

### ISSUE THREAD

**Issue by Micket** [mylar3/mylar3#328]
Trying to use opds, i see
1. Issue titles render as ugly str-converted byte-strings `b'some title'`meaning there has been a str-conversion of a encoded string.
2. cherrypy complains about byte strings and expects str, e.g. here
https://github.com/mylar3/mylar3/blob/master/mylar/opds.py#L92
which definitely must drop the encoding.

It's difficult to trigger all code paths, but, considering it's python3 now, encode'ing should probably all be removed (unless there are some cases where it's necessary for DB-interactions?)

**Comment by evilhero** [comment]
Thanks for bringing this to light, the OPDS section was probably missed during some testing. The culprit in all of this is the IssueName field in the dB itself - it has been encoded incorrectly resulting in it being stored as the wrong datatype  within the db.

Currently the only way to get rid of the encodings is on refresh on a per series basis. New adds (and refreshes) aren't affected by this as code was introduced to stop it from happening a week or so ago. 

Doing this for each series tho is tedious at best, so there's a db conversion on the way to do it automatically however because it deals with the data, it still needs further testing to ensure it doesn't bork things right up.

That being said removing the utf-8 encoding from OPDS needs to be done regardless. I mentioned the above aspect in case just removing the encodings does not solve the situation.

I can look into this after I fully wake up.

**Comment by SenorSmartyPants** [comment]
I'm seeing some possibly related stuff in the logs. byte-strings
`ct_check: b'ComicTagger 1.3.3 [ninjas.walk.alone / SHURIKEN]\nCopyright (c) 2012-2020 ComicTagger Team\nDistributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)\n'`

And my custom post processing script throws an error, I think just because of str concat method. My script runs fine from the CLI.

`Uncaught exception: Traceback (most recent call last):
File "/app/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar/PostProcessor.py", line 1688, in Process
self.Process_next(comicid, issueid, issuenumOG, ml, stat)
File "/app/mylar/PostProcessor.py", line 2790, in Process_next
self._run_extra_scripts(nzbn, self.nzb_folder, filen, folderp, seriesmetadata)
File "/app/mylar/PostProcessor.py", line 193, in _run_extra_scripts
logger.fdebug("Script result: " + out)
TypeError: can only concatenate str (not "bytes") to str`
