### ISSUE TITLE
Search is blocked after exception in search

### ISSUE THREAD

**Issue by miracle152005** [mylar3/mylar3#343]
**Describe the bug**
After getting an exception in the search process I am unable to do any other search processes.
"A search is currently in progress....queueing this up again to try in a bit."
Could you please take a look.

Thanks.
Best regards
miracle152005

**CarePackage**
Exception can be found in this log at 08-Jun-2020 13:18:55
[mylar.log](https://github.com/mylar3/mylar3/files/4746152/mylar.log)

**Environment (please complete the following information):**
 - OS: docker container on ubuntu 18.04
 - Branch / commit: c2771d4fc923e6520054fd144d1aa0c0f3277135

**Additional information**
I think there are two problems in the issue.
First the exception: The search seems to have encountered a video file which says its 1.7G in size.
Secondly: Even if the error happens. The automated search should just skip the current element (maybe even only the current indexer) and pick the next item, instead of blocking the search queque until the service is restarted.

**Comment by evilhero** [comment]
It's failing due to the conversion of 1.7GB instead of 1.7G. You excluded the pertinent section from the logs that indicate where you're retrieving the search results from however so at best guess I would say DDL but without confirmation it's hard to know for sure.

Also the idea behind a ```traceback``` error is that it's an unhandled exception that causes things to break. This is, for the most part at least, unavoidable as the results are never the same so we can't code for every single aspect. We code for the best guess/scenario and work from that point. The bug reports that people send in is what we use to then fine-tune the aspects that aren't working so that future tracebacks are minimal. Thus why sending in reports with full debug logs is essential to improving the program.

**Comment by miracle152005** [comment]
@evilhero: that is the whole log.
I deleted the log, activated debug logging and reproduced the issue.

**Comment by miracle152005** [comment]
This is the result which should be failing.
2020.06.03 Weekly Pack

DDL is activated, as well as experimental search.
If it is the dll Package which is failing it could be because the size on the UI is defined as such:

2020.06.03 Weekly Pack
Year : 2020 | Size : 1.7 GB//742 MB

**Comment by miracle152005** [comment]
line 919-920 in search.py are this:
                                elif entry['site'] == 'DDL':
                                    comsize_b = helpers.human2bytes(entry['size'])

So it should be the ddl search.

**Comment by miracle152005** [comment]
I am currently testing a fix.
Will let you know how it goes.

**Comment by miracle152005** [comment]
I created a pull request, which resolved the issue.

**Comment by barbequesauce** [comment]
Thanks for the submission!

**Comment by barbequesauce** [comment]
we good here?

**Comment by miracle152005** [comment]
Yeah this fix works and I no longer get the exception.
