### ISSUE TITLE
How to update from Mylar3 0.3.6 to 0.4.0? Wasn't sure where to ask...

### ISSUE THREAD

**Issue by paulr24** [mylar3/mylar3#344]
I attempted to update Mylar3 from 0.3.6 to 0.4.0 but wasn't sure of the procedure so I ran into some issues. What is the official procedure? I apologize if this is clearly stated somewhere, but I haven't found it and clicking "check for new version" in Mylar3 did not work for me. Thanks!

 - OS: Windows 10

**Comment by evilhero** [comment]
There was a problem in the 0.4.0 build that we addressed immediately after it was pushed - but we haven't pushed out the new master release. It's due to having annual integration enabled and not being able to poll the data properly.  There's nothing to be done on your end unfortunately, just need to wait for us to push it to master which should be soon (I'll try to do it tomorrow pending free time).

**Comment by barbequesauce** [comment]
Did you try 0.4.1 as evilhero recommended?

**Comment by barbequesauce** [comment]
Feel free to reopen if this is still an issue.
