### ISSUE TITLE
Issue while upgrading from previous version

### ISSUE THREAD

**Issue by TheOttoman2012** [mylar3/mylar3#379]
I have the previous version of Mylar, and I created a new folder "mylar3" and copied over my cache folder, db and config.ini. I adjusted the two entries to point to the new location of mylar3 and changed the git location as per instructions.

I then attempted to load mylar and got this error:

29-Jun-2020 10:57:44 - INFO    :: mylar.configure.1016 : MainThread : [COMICTAGGER] Version detected: 1.3.3
29-Jun-2020 10:57:44 - ERROR   :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\mylar3\Mylar.py", line 386, in <module>
    main()
  File "C:\mylar3\Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\mylar3\mylar\__init__.py", line 180, in initialize
    CONFIG = cc.read(startup=True)
  File "C:\mylar3\mylar\config.py", line 569, in read
    self.configure(startup=startup)
  File "C:\mylar3\mylar\config.py", line 1056, in configure
    if not os.path.exists(self.CT_SETTINGSPATH):
  File "C:\Program Files\Python37\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by evilhero** [comment]
The fix for this is in the python3-dev branch atm, we'll be pushing the merge to the main branch hopefully today (was supposed to be this weekend, but life).

If you can't wait, you can get around this error, by setting the value manually in the config.ini. With Mylar shutdown, open up the config.ini, and find the ```[metatagging]``` section. Then find the ct_settingspath field and set it to the full path location to your Mylar3 installation but append a ```.ComicTagger``` directory to the end  ( ie. ```ct_settingspath = C:\mylar3\.ComicTagger``` ). This will create a hidden directory in your mylar3 directory where ComicTagger will store it's ini files and the like.

*note* if you have more than one ct_settingspath in your config.ini, it will break things. You can check if the extra entry exists in the ```[General]``` section of the config.ini. If it does, just delete the entire line containing the ct_settingspath entry. That way the only ct_settingspath entry that should exist in the .ini is in the ```[metatagging]``` section.

**Comment by TheOttoman2012** [comment]
very cool... I can wait.
Thanks!

**Comment by waltermaldonado** [comment]
That does not work for the linuxserver.io Dockerized version, I still cannot add comics, it keeps hanging on loading comic data, with None values on the table fields...

**Comment by evilhero** [comment]
@waltermaldonado, this is a closed issue. 5+ months old and doesn't even involve a docker install. You say you still cannot add, when this is your first post indicating a problem... 

The docker version works fine, odds are you didn't change the relevant info from your old ini file as per the readme.

If you have an issue, and want assistance - make a new issue with the needed information included.

**Comment by waltermaldonado** [comment]
> The fix for this is in the python3-dev branch atm, we'll be pushing the merge to the main branch hopefully today (was supposed to be this weekend, but life).
> 
> If you can't wait, you can get around this error, by setting the value manually in the config.ini. With Mylar shutdown, open up the config.ini, and find the `[metatagging]` section. Then find the ct_settingspath field and set it to the full path location to your Mylar3 installation but append a `.ComicTagger` directory to the end ( ie. `ct_settingspath = C:\mylar3\.ComicTagger` ). This will create a hidden directory in your mylar3 directory where ComicTagger will store it's ini files and the like.
> 
> _note_ if you have more than one ct_settingspath in your config.ini, it will break things. You can check if the extra entry exists in the `[General]` section of the config.ini. If it does, just delete the entire line containing the ct_settingspath entry. That way the only ct_settingspath entry that should exist in the .ini is in the `[metatagging]` section.

I was referring to this workaround, and as I stated, I was referring to the same error, but with the Docker version from linuxserver.io. This is my first install, there is no old .ini file.

I did not see any reason to open a new issue because I though this would be the same.

Also, I think you could be less aggressive and more helpful with the community, but nevermind, I will not bother you again.
Regards.

**Comment by evilhero** [comment]
LOL aggressive? That's cute. I've been called alot over the years, but being called not helpful is not one. 

You realize this is a hobby project right? Myself and others do this for fun. I don't get paid if someone uses it - any donations made go back into costs associated with development. I could care less if you use the program or don't - I don't know you. Trust me when I say, my response above was anything but hostile.

You tried to reopen a 6-month old closed issue that isn't even of the same install build. Let alone you provided no other additional information other than just stating it doesn't work. 

We have guidelines for people to post issues about, and we deal with each of them. Follow them if you want assistance - or don't, and well  don't.
