### ISSUE TITLE
Mass Import fails

### ISSUE THREAD

**Issue by Infi-St** [mylar3/mylar3#399]
**Describe the bug**
First attempt to import library into mylar3.  Tried latest and unstable docker images.

**CarePackage**
[carepackage (3).zip](https://github.com/mylar3/mylar3/files/4943826/carepackage.3.zip)

**Environment (please complete the following information):**
 - OS: Unraid
 - Branch / commit: hotio/mylar3:latest

**Additional information**
19-Jul-2020 10:22:13 - INFO    :: mylar.scanLibrary.644 : LibraryScan : [IMPORT] Parsing/Reading of files completed!
19-Jul-2020 10:22:13 - INFO    :: mylar.scanLibrary.645 : LibraryScan : [IMPORT] Attempting to import 221 files into your watchlist.
19-Jul-2020 10:22:13 - INFO    :: mylar.scanLibrary.646 : LibraryScan : [IMPORT-BREAKDOWN] Files with ComicIDs successfully extracted: 0
19-Jul-2020 10:22:13 - INFO    :: mylar.scanLibrary.647 : LibraryScan : [IMPORT-BREAKDOWN] Files that had to be parsed: 221
19-Jul-2020 10:22:13 - INFO    :: mylar.scanLibrary.648 : LibraryScan : [IMPORT-BREAKDOWN] Files that were unable to be parsed: 0
19-Jul-2020 10:22:13 - INFO    :: mylar.scanLibrary.649 : LibraryScan : [IMPORT-BREAKDOWN] Files that caused errors during the import: 0
19-Jul-2020 10:22:16 - INFO    :: mylar.ThreadcomicScan.4396 : CP Server Thread-8 : Successfully scanned in directory. Enabling the importResults button now.
19-Jul-2020 10:22:22 - INFO    :: mylar.markImports.2834 : CP Server Thread-4 : Initiating mass import.
19-Jul-2020 10:22:22 - INFO    :: mylar.markImports.2849 : CP Server Thread-4 : 209 series will be attempted to be imported.
19-Jul-2020 10:22:22 - INFO    :: mylar.preSearchit.4564 : Thread-12 : [IMPORT][A Girl on the Shore (Umibe no Onnanoko) (v1)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
19-Jul-2020 10:22:22 - ERROR   :: mylar.excepthook.315 : Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar/webserve.py", line 4622, in preSearchit
    if 'annual' in getiss.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by barbequesauce** [comment]
Couple of things there - the ini file is set up for python3-dev, but the logfile indicates you're running master (and the traceback above comes from master as well). Also, the logfile in your carepackage does not have the error above (and isnt in debug). 

Can you restart with the `-v` flag so it's in debug from the start, and rerun the import? Then resubmit the carepackage pelase...

**Comment by Infi-St** [comment]
Thanks for the feedback. Here is the carepackage with -v:

[carepackage (4).zip](https://github.com/mylar3/mylar3/files/4943885/carepackage.4.zip)

**Comment by evilhero** [comment]
Yeah, as @barbequesauce mentioned briefly, Mylar will not be able to import any type of Manga unless it's named exactly as per CV unfortunately. That means the fact that in the above traceback error, the included Japanese translation title will be assumed to be part of the overall title ```A Girl on the Shore (Umibe no Onnanoko)``` - which makes matching near impossible since Mylar isn't built to handle manga filenaming.

Also, as an aside and part of this I suppose, the current importer will not be able to import anything that does not have an issue number present. So if you're importing Trade PaperBacks, Graphic Novels, Compilations or just files that don't have an issue number present for whatever reason, Mylar will not be able to even do a comparison. However, Mylar can and will search for these types of issues, as well as post-process and monitor existing directories - it's just the importer that hasn't caught up to the rest of the application as of yet.

Hopefully this last part will be addressed when the new version of the importer hits Mylar 'soon-ish', however the manga-related aspect will not be addressed..

**Comment by Infi-St** [comment]
Thank you for the detailed response.
