### ISSUE TITLE
No cover.jpg file is created to move into folders

### ISSUE THREAD

**Issue by Frankthetankk** [mylar3/mylar3#412]
**Describe the bug**
Mylar 3 does not create a "cover.jpg" file for each of my folders. I have the option checkmarked "Place cover.jpg into Comic Directory for each comic". Also, I do not see "cover" ever mentioned in the logs. It feels like the checkmark isn't getting detected/saved.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5079399/carepackage.zip)

**Environment:**
- OS: Windows10 VM
- Branch master
- git (build 3af6bb19fec0d2426d076ae574a3523a7a12ad6e)
- Python Version : 3.7.6
- Language : en_US.cp1252
- installed via [Install Mylar Windows for Usenet Comics](https://www.htpcguides.com/install-mylar-windows-usenet-comics/) but changed info to mylar3. Recently updated, and I believe I now have the latest update.

**Additional information**
This has been an ongoing issue. My cache folder is full with numbered jpg files. The option "Write cvinfo into each comic directory" appears to be working as intended. As I have a cvinfo file in each folder. Other than mylar's Web Interface > Permissions, I have not changed any permissions, nor do I know how to on a Windows VM.

**Comment by Frankthetankk** [comment]
Also, Why does mylar 3 always display the last issue and not the first issue within the series that are added? Is there an option to download first issues from comicvine instead?

**Comment by evilhero** [comment]
It's getting detected, however the code has changed for the negative I believe. I tried it last night, and couldn't get the cover to save, albeit I'm also using the primary / secondary directories so that was my main problem. I fixed some of it up, so it should be able to save properly now once I push the commit.

As far as your last point - mylar will display the most current issue cover if the ini option is enabled, by default it is set to disabled so it should be showing the first issue cover of the given series on a refresh series / add series. If this is not the case (haven't checked recently), then I can investigate it further, but you make no mention of covers in your last comment - so I'm just assuming that's what you meant.

**Comment by Frankthetankk** [comment]
Yeah, I was referring to the cover images in mylar 3 displaying the latest issue of a series instead the first issue. 

I want to report what I've found. I believe after I made some changes, I may have fix the some of issue. My mylar now creates a cover.jpg in a comic folder when I "refresh" or add a new series. At the same time mylar will download a brand new cover.jpg as the first issue (which is what I want) instead of the latest issue as it did before.

The first change is I went into the config.ini and changed this from True to False.
ignore_covers = False
Second change I made was to uncheck mark Advanced Settings > Alternate Series Covers

Sidenote. I feel the wording in "Alternate Series Covers" is a bit confusing and misleading after I've discovered what its intent is for. I was never sure exactly what this option did so I always keep it checkmarked. I thought the option was referring to allowing of variant covers of each issue of a series. May I suggest changing the wording to something else that makes it more clear what it does. I do not yet have a better idea, but something to the effect of "Download the latest cover image issue of a series" 
 
A problem I have now, Series folders that already have a cover.jpg file and it shows up as the latest issue, does not redownload and redisplay as a image of the first issue of a series when I "refresh" a series. I have to physically go and delete the cover.jpg file so that it'll redownload with the first issue image.

[carepackage (2).zip](https://github.com/mylar3/mylar3/files/5082549/carepackage.2.zip)

**Comment by Frankthetankk** [comment]
This may be an update to the 'Alternate Series Covers'. My database now has a mix of series displaying images of first issues and last issues. Some series show the last issue and others the first issue images. This is also reflected to the cover.jpg images. This is because I had 'Alternate Series Covers' checked and unchecked marked at different times while adding a bunch of new series to my mylar, not knowing what this option did. What I want is for all the series to display the first issue. These are the steps I used to "reset" a series so that it will display and download the cover.jpg of the first issue of a series.

First, I have to get the ComicID number. The two ways I know how to is to either open the 'cvinfo' file and grabbing the last numbers or by going to mylar and selecting/searching the series, selecting it and grabbing it from the url. For example my Marvel - Ironheart (2018) displays issue 12's image, same with its cover.jpg. This series's ComicID is 115575.
Next, I have to go to the cache folder and find the ComicID numbered file and delete it. Deleting just the cover.jpg and 'refreshing' a series is not enough. It has to be the file in the cache folder.
Next, is to 'refresh' the series. For example I 'refreshed' Ironheart and after a few seconds the first issue populates within mylar.
Next, looking in the Ironheart folder, the cover,jpg still displays the last issue of the series. 
Finally, the way I fix the cover.jpg image is to simply delete it and 'refresh' the series again.

This is a doable process to 'reset' a series instead of just deleting a series and starting over, but does take some time to do. I am wondering is there a better way to do this that I am missing? I don't see any option in mylar to do this automatically. 

Is it ever safe to just delete the cache folder and start over?
In the config.ini file, what does "cleanup_cache = False" do? 
Also, what does "comic_cover_local = True" do? I was wondering if these were related to my issue.

**Comment by evilhero** [comment]
Do not delete the .jpg's from the cache folder. The cache folder holds the images that you see when you view the series detail page. If you wipe all of those out, you'll just have blank image holders in lieu of the actual images for every series on your watchlist.

```comic_cover_local``` is the setting to drop the cover.jpg file into given the series directory.

Keep in mind that if you do use the ```Alternate Series Covers``` option, that it will also apply to the cover.jpg file that gets dropped into the series folders. This is an unintended side-effect so we don't hammer CV requesting image covers constantly. I'll see if I can come up with a way to keep the cover.jpg pointing to the 1st issue, and if ```Alternate Series Covers``` is enabled that it doesn't hammer the cover.jpg with an alternate issue image.

Also, I just pushed a fix for the cover problem you were experiencing - however it is in the python3-dev branch and not the master, so you'll have to wait a few days before it gets into master due to testing. Now it will respect the setting regardless of the image present - so if you have a series with the latest issue showing, but you have ```Alternate Series Covers``` disabled - refreshing the series will force it to load in the first issue image again.  Alternatively if you have the first image showing, and you have ```Alternate Series Covers``` enabled, refreshing the series will force it to load in the latest issue cover. However, as noted above this will hammer your existing cover.jpg file so that it's the latest (might not be a problem if you want the 1st issue to be the cover.jpg and you have the option disabled).

Side-note: the ```ignore_covers``` option in the config.ini is for searches to not consider filenames that have the word 'covers' in the filename as a valid search result (nothing to do with the issue covers that you're talking about).

**Comment by barbequesauce** [comment]
@Frankthetankk are we ok to close this?

**Comment by Frankthetankk** [comment]
I believe it's okay to close. After updating and setting the config as above, Mylar now puts cover.jpg into my series folders. This happen only when I add a new series or clicking the "Refresh Comic" button within a series. I also have to make sure `comic_cover_local = True` is set to true.
