### ISSUE TITLE
$Type Folder Format not working when adding new comics

### ISSUE THREAD

**Issue by Frankthetankk** [mylar3/mylar3#460]
**Describe the bug**
Might be similar to #421. My folder format is set to "$Publisher - $Series ($Year) $Type". When I add a new series it doesn't add the edition anymore. For example, "Action Lab - Chainsaw Reindeer (2019)" is a one-shot, and it doesn't create a "One-Shot" in place of $Type. Back in git (build 3af6bb19fec0d2426d076ae574a3523a7a12ad6e) this feature used to work.

[carepackage.zip](https://github.com/mylar3/mylar3/files/5223512/carepackage.zip)

**Environment:**
- OS: Windows10 VM
- Branch master
- git (build b67e1d393c612bea479be722faedb8a053726d42)
- Mylar Version: master [v0.4.5 - Gaze into the fist of Dredd] 
- Python Version : 3.7.6
- Language : en_US.cp1252
- installed via [Install Mylar Windows for Usenet Comics](https://www.htpcguides.com/install-mylar-windows-usenet-comics/) but changed info to mylar3.

**Additional information**
#421 is still ongoing.

**Comment by evilhero** [comment]
In order to use the ```$Type``` variable in the Folder Format, you need to enable the ```format_booktype``` option in the config.ini (set it to ```True``` with Mylar not running).  There was some problems initially with how it was setting the $Type field, so to minimize it screwing up everyone's directories we disabled it by default and put in the config.ini as 'hidden option' kinda thing.
Lately tho, it seems to be working far better - so we're going to make it a GUI option sooner rather than later.

Once it's enabled, any change on the Edit Settings tab will also cause a rename of the existing folder. (ie. If you have a series called SuperHero (2016), and your folder format is ```[$Type] $Series $(Year)``` and you update the settings via the Edit Settings dropdown - either with some other change, or just clicking on it with no change - it will rename the existing folder to ```[One-Shot] SuperHero (2016)```).

**Comment by Frankthetankk** [comment]
You were right, I changed ```format_booktype``` to ```True``` and adding a new series adds the edition. 

> and you update the settings via the Edit Settings dropdown - either with some other change, or just clicking on it with no change - it will rename the existing folder

I could not repeat this part. What worked for me is to change ```Force-Type (original:One-Shot)``` to something else like ```Digital```, for example. Save it and change it back to ```One-Shot``` , save it. Then the folder name will update. Anything else in the ```Edit Settings``` didn't update for me.

Is there a readme file that list every config.ini option and the details on what each one does? I am wondering what other 'hidden options' I am missing.

**Comment by barbequesauce** [comment]
There isnt, no - that said, we accept PRs :)

**Comment by Frankthetankk** [comment]
If I can figure out how to do a pull request, I will share data that I've found on the config.ini options.

**Comment by evilhero** [comment]
Closing as I believe this has been fixed in recent builds, this well over a year old and is probably stale. So if it's still problem, open up a new issue with the relevant information so it gets proper attention.
