### ISSUE TITLE
Upcoming issue not being searched

### ISSUE THREAD

**Issue by phairplay** [mylar3/mylar3#494]
**Describe the bug**
Upcoming issues

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit:  8ac95d9e3b45959ebd54058016fdadb20c91e5f6 (python3-dev)

**Additional information**
when I manually search for this week's upcoming issues I notice they are already available for downloading, yet Mylar doesn't isn't searching for them until several days later. is there any way to change this?

**Comment by barbequesauce** [comment]
Can you provide some specific examples?

When we dig in, I expect the issue will be delayed updating of the metadata on ComicVine - oftentimes their updates can take two or three days (and over the summer the delay sometimes goes into the following week). We can't (confidently) match an issue on the pull to the file names unless the metadata is available.

While there is something cooking to reduce the reliance on the metadata to match issues for download, it still has a lot of work...

**Comment by phairplay** [comment]
sorry what info do you require

here is a screen shot of the upcoming titles
![Screenshot 2020-10-16 130834](https://user-images.githubusercontent.com/9025847/96257043-9e09c300-0fb1-11eb-9b6f-1d175a2545c4.png)
here are screenshots showing they are available 
![Screenshot 2020-10-16 130929](https://user-images.githubusercontent.com/9025847/96257108-b679dd80-0fb1-11eb-9ecc-33461d82cb50.png)
![Screenshot 2020-10-16 131038](https://user-images.githubusercontent.com/9025847/96257121-bb3e9180-0fb1-11eb-8a4c-985d7fa37ace.png)

**Comment by BRTPOB** [comment]
That's exactly what barbequesauce was pointing to. Mylar uses a couple of services to figure out what's coming out every given week, but is reliant upon ComicVine to update to actually confirm a release is available. The person who updates ComicVine has gotten slower over the years, specifically with Marvel releases being days after the actual release date getting all of the required information added to their DB so that Mylar can use it.

**Comment by evilhero** [comment]
Yep this is normal behaviour. Just because an issue is available to download somewhere doesn't mean Mylar can download it. 

Anything listed in the Upcoming section of Mylar does not have any information on CV associated with it, yet. Once the information is available on CV, then Mylar will update itself, and move the item from the Upcoming section to the Wanted table, and then it can be searched for. 

An issue can only be searched for if it appears in a Wanted status, and a status can only be assigned when issue information is present.

**Comment by phairplay** [comment]
Okay I fully understand this was more a curiosity than an issue.
Thank you guys
