### ISSUE TITLE
Process and import without Comicvine update

### ISSUE THREAD

**Issue by omgthegreenranger** [mylar3/mylar3#512]
**Describe the request**
Currently, without a Comicvine entry, Mylar will not download an issue. This is understandable. However, if the comic is listed in the "Wanted" section, it would be helpful if Mylar could process and import the comic if we download it manually and add it to the monitored folder. This would allow us to read it while we wait for (primarly Marvel) comics to show up.

**How did you come up with the idea?**
Mostly because I'm annoyed that Comicvine is taking so long updating Marvel listings, and there is no function to pull the data from the Marvel Developers API through ComicTagger.

**Environment (please complete the following information):**
All of them, i suppose.

**Additional information**
I can understand the lack of data that would go in to the tagging, but I'd like to be able to access my comics on release day, not a week later, via Mylar or another library system that picks up on Mylar's awesome processing and organizing. I'm not sure where Mylar grabs the weekly pull listings, but would that data be sufficient to at least important and organize the issues?

**Comment by evilhero** [comment]
No - it's not as simple as just that. The reason why Mylar has processing and organizing is due to being able to properly link up the issues to the correct series. Take away that power, and it's going to be a crapshoot at best most of the time. It'd be like if you have an unmarked key to a storage locker that's located in a room full of a thousand lockers. 

Mylar pulls from a different site that has no linking to CV - it's all down via name parsing and logistics behind the scenes. Having it download & post-process would then lead to meta-tagging problems, let alone matching problems due to not having the correct data to verify against. Even if it were to download it without CV, then you'd have tonnes of issues with no metatagging, possibly linking to the incorrect series and no way of knowing what goes to where leaving alot of manual intervention.

CT will not link up to the Marvel API due, well it being CT. I don't plan on adding it - so unless it gets into the main fork then it's probably not going to happen (plus then that leaves out other publishers, so why do it only for one vs all approach).

Now all that being said, and having burst some of the bubble on a good idea that's been brought up lots in the past - let me try to add something positive.

I have had something to solve this cooking for the last year almost now I guess. It does allow for downloading issues from the weekly pull (only - so new issues that don't have CV info), and posts them into the given series directory. It also establishes a metatagging queue that keeps track of the issues that have been downloaded that don't have any CV data yet. The queue just keeps on getting monitored and when CV data becomes available, it tags it appropriately without the need for any manual intevention. There's some other bells & whistles in there, but tbh I can't recall atm. 

It's about 80%-85% done, mainly due to various factors that testing has brought up and having to try to work through them all - in addition to the daily grind of maintaining Mylar and answering things, etc (@barbequesauce helps out immensely in all of these aspects + codes as well). So yeah, something is coming - just not sure exactly of the timeframe when obviously due to a lot of factors (plus the new storyarc system, and a rebooted import system)....

**Comment by omgthegreenranger** [comment]
Appreciate it! I did think there was an issue being able to organize without the same metadata that you'd have in the structure itself, so I completely understand. It's not really Mylar's problem or fault, I was just thinking about workarounds.

Having the two sources for pull list and Comicvine does run in to a bit of an incompatibility here and there - it's still trying to find Champions V3 #1 instead of Champions V4#1, and the new Iron Man series is being linked to one from the 1990s - I doubt very much that that's a Mylar-specific thing, so it's good to bear that in mind.

On that note - have you seen the Anansi Project initiative (https://github.com/anansi-project/rfcs) to unify metadata and incorporate multiple "Sources of Truth" into a consistent framework. It's the developer of Komga, and it looks like ComicTagger is interested in the project, too. Not sure if that would help as Comicvine keeps dragging their heels or it it's even relevant.

**Comment by evilhero** [comment]
Both Iron Man and Champions should be corrected at this point. If one is pointing to the incorrect series, then you need to do a ```Recreate Pullist``` from the weekly page when you're on that specific week. Mylar will only keep polling for the current date - it will not poll for issues weeks in the past as that gets problematic. 

So if you have something from week 40 that isn't pointing to the correct series, you need to go to the Weekly tab and use the arrows in the GUI to move the appropriate week and then do a ```Recreate Pullist``` when you're on that specific week so that Mylar will update that week.

**Comment by omgthegreenranger** [comment]
I figured that'd do it, but I tried it a couple of times and Iron Man Issue 2 was still pointing to series.

**Comment by evilhero** [comment]
It's refreshing fine on my side - try shutting Mylar down and starting it up again to see if it clears it up. The issue data isn't present on CV as of yet, but it should still link to the proper series (do you have the new series on your watchlist) ?

**Comment by barbequesauce** [comment]
how is this looking? ok to close?

**Comment by HypKin** [comment]
> 
> **How did you come up with the idea?**
> Mostly because I'm annoyed that Comicvine is taking so long updating Marvel listings, and there is no function to pull the data from the Marvel Developers API through ComicTagger.
> 


just a heads up, in CV I think theres only a few people actually inputting all the new issues. but you as a user can also add data. sometimes its a very quick fix on comicvine and a few minutes later its correct on mylar. so instead of waiting, just add the issues you're missing, and it will be helpful to everyone.

**Comment by omgthegreenranger** [comment]
> how is this looking? ok to close?

Unless there's anything else, everything is answered pretty effectively.
