### ISSUE TITLE
Wanted search error

### ISSUE THREAD

**Issue by tctx79** [mylar3/mylar3#534]
**Describe the bug**
When DDL is enabled and a Wanted search is done I get an error in my logs referencing Cloudflare.  It also happens on a container restart.
[carepackage.zip](https://github.com/mylar3/mylar3/files/5488942/carepackage.zip)

**CarePackage**
Uploaded

**Environment (please complete the following information):**
 - OS: Windows 10 running latest Docker for Windows
 - hotio/mylar3
- linuxserver/mylar3

**Additional information**
I have tried both latest and nightly builds on this and continue to get the error.

**EDIT: My apologies, I uploaded the care package twice.  The carepackage (1).zip is with the linuxserver/mylar3 container.
[carepackage (1).zip](https://github.com/mylar3/mylar3/files/5489090/carepackage.1.zip)

**Comment by evilhero** [comment]
Yeah this is out of our hands as it's due to CF changing the challenges on their end, which breaks cfscrape. Unfortunately there's no update for cfscrape that addresses this as of yet.

Odds are if you try later in the day, or on a day other than Wednesday - the CF might not be on and you can use the site with Mylar as per normal. 

ATM tho, I'm about to push something to python3-dev that will at least make it so that if the challenge error occurs, it will not kill the entire search queue, but it will not fix anything about the DDL error itself.

**Comment by tctx79** [comment]
> Yeah this is out of our hands as it's due to CF changing the challenges on their end, which breaks cfscrape. Unfortunately there's no update for cfscrape that addresses this as of yet.
> 
> Odds are if you try later in the day, or on a day other than Wednesday - the CF might not be on and you can use the site with Mylar as per normal.
> 
> ATM tho, I'm about to push something to python3-dev that will at least make it so that if the challenge error occurs, it will not kill the entire search queue, but it will not fix anything about the DDL error itself.

Gotcha.  So since I'm in a hotio/mylar3 docker container, if I appended hotio/mylar3:python3-dav would that download your update?

**Comment by evilhero** [comment]
It should? I honestly have no idea how that particular docker updates against the python3-dev branch. The PR is awaiting merge to the python3-dev branch, so should be in there at some point today.

**Comment by tctx79** [comment]
Awesome thank you very much.
