### ISSUE TITLE
Queue/manual request management

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#538]
**Describe the bug**
Impatient with CV being slow to update, I manually found some new issues last night.  They're not all post-processing in, but also trying to have Mylar automatically grab the missing issues once CV updated is not working.  I've tried to add them via setting them to 'wanted' (toggled) as well as clicking the manual search icon.  In the logs, I am seeing that the manual search is being queued, but not running anytime soon.  I tried updating/restarting, as I know sometimes a restart can free up the queues, but it has made no difference.  

**CarePackage**
See attached.  Logs show no tracebacks on the new UI element.
[carepackage(6).zip](https://github.com/mylar3/mylar3/files/5504358/carepackage.6.zip)

**Environment (please complete the following information):**
 - OS: Win10 20H2
 - Branch / commit:  fcad62b67a1759de8cb6bccdcad26ea609def6ba (python3-dev) 

**Additional information**
Mylar routes searches through NZBHydra2, and the logs in there show no search results are coming through on the comic category that Mylar usually uses.  Via API, anyway - the manual searches I made yesterday still show (to clarify, I can see one API hit this morning for Mylar that I guess is basically the RSS feed type action - searching for all new comics to scan for wanted titles - but nothing grabbed.  Including comics on my wanted list like Horizon Zero Dawn #3)

I'm not sure if this is a systems issue per se, or if the tagging of already downloaded comics, and reliance on CV data, have poorly coded data that Mylar isn't able to react to correctly.  But I'd expect to at least see the search being made and coming back fruitless (or coming back with, er, fruit, but not being able to PP properly)

**Comment by professionaltart** [comment]
[carepackage(7).zip](https://github.com/mylar3/mylar3/files/5521132/carepackage.7.zip)
Haven't seen anything download in sab this week that wasn't manually downloaded, both before and after I enabled and then disabled DDL.

Logs look like it keeps searching the RSS feed - which from memory Hydra creates by doing a search for all recent comics - but I'm seeing no backfill for what came out almost a week ago.

**Comment by evilhero** [comment]
The RSS Feed only gets tagged every 20 minutes (or whatever your rss interval setting is set to). When you see it saying sending RSS request to w/e - that's only checking the cache of mylar's rss entries for anything. When the RSS Feed fires off the designated interval, then it would update the db-cache with the changes so that when rss searches are done it's able to find it in the cache.

In looking at your rss cache in the db, I don't see any rss entrires for the last 3 days, and sporadically for the past week plus. I'm wondering if something is going on with nzbhydra and how it's polling the results. Would you be able to disable your nzbhydra instance within Mylar, and manually add in one (or more) of your providers into Mylar? 

At this point I'm thinking that something is broken between the Mylar & RSS aspect when used with nzbhydra, albeit with what I wouldn't know unless this test comes back positive. 

As a side-note, I used your db file and started up Mylar. It began snatching stuff from a pulled down RSS feed off a non-newznab indexer (I don't use nzbhydra).

**Comment by evilhero** [comment]
This should be fixed in #538 when it goes into python3-dev. There might still be some caching issue that might need to be addressed (ie. I'm not sure why you're missing days of rss feeds if the feed was actually updated), as this patch will not fix that if it's an issue. What the patch will fix is the problem of having the items in the RSS cache and not being able to be matched against (only affected those providers that have the [nzbhydra] or [localhost] tags from the looks of it.

**Comment by professionaltart** [comment]
Thanks - I've added NZB.su manually into Mylar, will see how that plays out this afternoon.  My RSS feed is set to do its work every 300 minutes, from memory due to issues a year or two back with a large wanted list never actually completing.

Also, Hydra have pushed out a few updates lately, but I don't recall anything in patch notes standing out as obvious breakers (not that I necessarily would notice those).

**Comment by professionaltart** [comment]
[carepackage(8).zip](https://github.com/mylar3/mylar3/files/5553669/carepackage.8.zip)
After the latest update, I left nzb.su manually enabled in mylar for a while before going back to hydra only.  

Still no comics downloading.

**Comment by evilhero** [comment]
So you have some search errors I saw in your db file, but I can't figure out where they're from as the logs rolled over prior to the carepackage (and thus are gone). 

However, in the latest builds the exceptions are snapshotted with the relevant info mostly. In your logs directory you should see log files labelled as **specific_#.log**. There should be several. I need to see at least one of those specific log files as they should all be the same error (I'm guessing).

You could also go into _History_, _View Logs,_ _Exceptions/Tracebacks_ you'll see an entry there with 9 occurrences. Clicking on the icon with 4 lines will bring up a log snippet viewer where you can get the hopefully relevant information by just copying & pasting it into here. (the log snippet viewer just calls up the specific log file to display).

**Comment by professionaltart** [comment]
I'm not too surprised the logs churned too hard, given how many millions of lines there were on the log page after not very long at all, after restarting Mylar.

[specific_carepackage.zip](https://github.com/mylar3/mylar3/files/5558404/specific_carepackage.zip)

**Comment by evilhero** [comment]
So the error in the specific log files was pertaining to not being able to search for issues with an issue date of 1970 or less (basically epoch time). Normally Mylar's is able to handle the conversion, even to before 1970 so things don't go south - however in your case for some reason, it is not liking the conversion method. I tried on my Windows 10 HC2 box, same series and issue you tried, thru an nzbhydra instance and it was snatched up immediately. 

So now I'm at a loss as to why it's happening. I mean the error is trapped, and doesn't break anything so subsequent searches occur, but it really shouldn't be doing that. Odds are this particular problem has nothing to do with your problem of not downloading anything, but in some regards if it's crapping on something like this, odds are it's crapping elsewhere and just not getting logged for whatever reason - especially since it worked for me and the only difference really is the timezone.

If it's queuing the search items, but not sending them to be searched then there's a problem with the search queue, or something has locked it up previously. Given that it happens almost immediately, it's probably in the logs but they roll over too quickly to catch on startup. Do you have any other errors in the exception/traceback popup box aside from the one you attached above ?  Can you increase the size of your logs, save Mylar and then restart it and then do a force check on the Wanted page and see if anything blows up ?

**Comment by BRTPOB** [comment]
MAKE LOGS BIGGER! ADD MOAR!

**Comment by professionaltart** [comment]
If I check for tracebacks etc in the logs page, I see this:
![image](https://user-images.githubusercontent.com/28383689/99634223-36550500-2a94-11eb-85a0-689373d6895b.png)
I set logs to 50MB each isntead of 10MB this morning and I... think they're still getting rotated out, so I'm increasing that again, enabling a manual indexer rather than solely Hydra, and doing another  restart

Care package before restart:
[carepackage(9).zip](https://github.com/mylar3/mylar3/files/5565059/carepackage.9.zip)

Care package after restart:
[carepackage(10).zip](https://github.com/mylar3/mylar3/files/5565310/carepackage.10.zip)

Looks like it didn't spam out a million or so checks after the restart, and finally grabbed some comics!  Also, I can see API hits going through to Hydra again!

I've hit manual search on a few things I already had, and I added a new series, and that all seems to be playing nicely.  It looks like it's automatically starting to backfill some things from the past few weeks on its own.

**Comment by professionaltart** [comment]
Carepackage: https://www.dropbox.com/s/kszqwtqzdfrdjio/carepackage%2811%29.zip?dl=0
[specific_carepackage.zip](https://github.com/mylar3/mylar3/files/5579384/specific_carepackage.zip)

Started not grabbing stuff again - or rather, since last week.

**Comment by barbequesauce** [comment]
evilhero - do we need another try/except around line 1646?

**Comment by evilhero** [comment]
Yeah we do, but we need to try an alternative way to get the store date so that the result can still be verified properly (and not just chucked out for failing to convert on a timestamp that's valid).

I have something ready, just not sure if it will work for @professionaltart, but only one way to find out. I'll get a PR up shortly to see if he can test it...

**Comment by professionaltart** [comment]
[carepackage(12.1).zip](https://github.com/mylar3/mylar3/files/5610081/carepackage.12.1.zip)
[carepackage(12.2).zip](https://github.com/mylar3/mylar3/files/5610082/carepackage.12.2.zip)

Still no bueno with the latest update

**Comment by evilhero** [comment]
Fix for the previous fix is now in the #559 PR.

I was going blind with the variables prior as I couldn't replicate your error - turns out, I picked the wrong variable to use. Tested against some mocked up data from the db included in the carepackage and seems to not error, but you'll have to test to confirm when it gets merged.

**Comment by barbequesauce** [comment]
Is merged. Good now. you try, you like.

**Comment by professionaltart** [comment]
Updated, let it run for a bit to make a mess of the logs, just tried to manually queue/search some things and....  they are now queued for manual search.  Will see whether it picks anything up over the next day or two, I guess.  

If I broke it, do I gotta bought it?

**Comment by professionaltart** [comment]
[carepackage(13.1).zip](https://github.com/mylar3/mylar3/files/5640052/carepackage.13.1.zip)
[carepackage(13.2).zip](https://github.com/mylar3/mylar3/files/5640054/carepackage.13.2.zip)
[specific_carepackage.zip](https://github.com/mylar3/mylar3/files/5640055/specific_carepackage.zip)

No traceback errors since the update/restart, but also still not finding comics.  I added for eg The Boys/Dear Becky #6 as a manual search, and it appears exactly once in the logs in the past 12 hrs.  3 times since then it has tried to find #7, the next issue out this week/on the watchlist.

**Comment by evilhero** [comment]
Well manual search doesn't change the status or anything - it literally does a one-off type of search to find the given comic. If it finds it, great it does the normal download stuff. If it can't, it doesn't change the status from what it was prior to initiating the manual search. If you want it to search continually until found, you'd have to change the status of the given issue to Wanted and then it will appear in your Wanted list (whereas Manual Searches do not appear unless their current status is already set to Wanted).

Will look over the logs in a bit - but coffee first!

**Comment by professionaltart** [comment]
Disabled RSS feed, and manual searches now hit the API request and are handled properly.
In the past 5 minutes it's also grabbing items from this week's and last week's pull lists.

**Comment by professionaltart** [comment]
Mylar had a busy night.  Busy enough it didn't do any post-processing, leaving Sab to have to auto-pause because the temp disk filled up.  I paused queue processing so it'd manually PP, then took this log snapshot.
[carepackage(14.1).zip](https://github.com/mylar3/mylar3/files/5646775/carepackage.14.1.zip)
[carepackage(14.2).zip](https://github.com/mylar3/mylar3/files/5646777/carepackage.14.2.zip)
[carepackage(14.3).zip](https://github.com/mylar3/mylar3/files/5646778/carepackage.14.3.zip)

**Comment by evilhero** [comment]
Better late than nevah - just took a look at the logs, saw the tracebacks in the specific log files and was able to replicate it locally. Fixed it, tested it works and will push up momentarily. Note that the error repeating over and over, while not killing the search queue, would not allow that specific issue to download. Your Origins issue in the logs - the volume in your watchlist is incorrect (it's in Mylar as 14, when it should be blank). This is due to some CV parsing problems that I need to figure out, but in addition to that I also fixed the actual search related issue with this particular one.  

Still going thru the logs to see about the post-processing thing...

**Comment by professionaltart** [comment]
[carepackage(15.1).zip](https://github.com/mylar3/mylar3/files/5759880/carepackage.15.1.zip)
[carepackage(15.2).zip](https://github.com/mylar3/mylar3/files/5759882/carepackage.15.2.zip)
[carepackage(15.3).zip](https://github.com/mylar3/mylar3/files/5759883/carepackage.15.3.zip)
[carepackage(15.4).zip](https://github.com/mylar3/mylar3/files/5759885/carepackage.15.4.zip)

I think the issues currently happening are unrelated to this ticket now.  If these latest logs show this is the case, I'm happy for this to be closed.
