### ISSUE TITLE
Post-processing failing, auto-search seems to be skipped

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#541]
**Describe the bug**
The last few times I've logged into Mylar, I've noticed that the server has gone _days_ without downloads, and a lot of issues have been snatched but not processed. I also noticed this set of messages in my logs tonight, but I do not know if it is related.
```
2020-11-11 22:13:35 | INFO | Download SABnzbd_nzo_qx_tg9_f failed. Requeue NZB to check later...
2020-11-11 22:13:35 | WARNING | error string indices must be integers
2020-11-11 22:13:35 | INFO | nzo_id: SABnzbd_nzo_qx_tg9_f --- SABnzbd_nzo_qx_tg9_f [Failed]
2020-11-11 22:13:35 | INFO | nzo_id: SABnzbd_nzo_7o395xhy --- SABnzbd_nzo_qx_tg9_f [Completed]
```

Here is a good time to look for in the logs:
![image](https://user-images.githubusercontent.com/1091716/98891996-5a4d9080-246d-11eb-9801-e3d363bac98f.png)

And here's proof that the one that wasn't from DDL downloaded:
![image](https://user-images.githubusercontent.com/1091716/98892030-6a657000-246d-11eb-936e-6b63b0ae97e3.png)

Here's an image showing an 11 day gap in my downloads:
![image](https://user-images.githubusercontent.com/1091716/98892084-89640200-246d-11eb-8bda-81450f805350.png)

To solve the issue, I restarted Mylar and manually went through and told it to look for comics it had previously snatched, plus any that had come out that it had not yet found.

I've attached my Care Package, minus the database since it is well over 150mb, and I plan to turn on Debug logging tonight.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5528092/carepackage.zip)
[mylar.db](https://chrisrees.dev/files/mylar-db.zip), hosted on my server as it seems like it may be important for this issue

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Branch / commit: python3-dev / fcad62b67a1759de8cb6bccdcad26ea609def6ba 

**Additional Information**
My completed downloads folder from Sabnzbd is loaded with unprocessed comics. When trying to run Manual Post-Processing in Mylar, I get an error that Manual Post-Processing cannot be run at this time. A restart of Mylar solves the issue with the Manual Post-Processing.

**Comment by evilhero** [comment]
Honestly, all I'm seeing in the logs are just Failed downloads being returned by SABnzbd. I don't see any failure directly within Mylar itself, but it keeps on looping over the same failed download repeatedly (probably cause it's failing in SAB for some reason).

I notice that you're running an ancient version of SABnzbd (2.3.6 beta 1 which is from early 2019 or even before that). I would suggest upgrading to a newer version of SABnzbd and seeing if the downloads are working that way.

I would also suggest that prior to starting up Mylar next time (or anytime you need to get the logs), you put Mylar into verbose mode so that full debug logs are gathered. The logs you attached are INFO level, which leave out a whole lot of information and don't really give any indication as to what is happening.

Another thing to check, in the last few versions of Mylar there has been an Exception / Traceback GUI option available. If you go into the History tab, View Logs, then Exception/Traceback logging you might be able to see any tracebacks that occurred recently (provided they were search related as that's the only thing that it's tracking atm).

**Comment by Serneum** [comment]
I was under the impression that turning on debug logging was only for any new messages, so I turned them on last night immediately after posting this just in case it happened again. Is that not the case?

I'll go ahead and update SAB, but SAB has been downloading the comics just fine (they're in my completed folder, history in SAB looks fine). All I can think of is there's some incompatibility after that, so I'll go ahead and rule it out.

Thanks for the tip on the Exception/Traceback logging. If I see anything odd, I'll look there next time as well

**Comment by evilhero** [comment]
I guess you probably haven't done a test connection for SABnzbd within Mylar - the version it says in the mylar config is 2.3.6 beta 1, which is why I mentioned it.

And yes, debug logging will only affect logs from after the point of turning on the option. It can't go back in time and verbosely enhance previous logging. All of the logs provided in the carepackage were at INFO level only, so it looks like it wasn't enabled at the point the logs were taken from at least.

There were some search errors in your logs, but due to the new exception handling, it didn't stop anything subsequent from being searched.

**Comment by Serneum** [comment]
Cool. I figured the other option was the logs were always verbose, but only rendering the specific level. I've updated SAB to 3.1.1 and will leave verbose logging on for a while. I suspect I may not see anything odd until next week when the new issues come out, but we will see

**Comment by Serneum** [comment]
Ok, checking back in. It looks like a bunch of comics were snatched two days ago (11/13/20) and were never processed. I'm also back to getting an error when trying to run manual post-processing, but nothing shows up in the Traceback or the Debug logs.

Traceback has errors from 11/11/20:
![image](https://user-images.githubusercontent.com/1091716/99202042-de5c8c80-277b-11eb-9f12-f4e5c257b7f6.png)

Downloads in Sabnzbd:
![image](https://user-images.githubusercontent.com/1091716/99202065-f0d6c600-277b-11eb-92ac-53c4874442fd.png)

Snatched comics, showing a mix of DDL and Sab downloads:
![image](https://user-images.githubusercontent.com/1091716/99202436-292ad400-277d-11eb-9a5e-49f7a17deb81.png)

I noticed that I have some red dots next to some providers, though tests work fine:
![image](https://user-images.githubusercontent.com/1091716/99202131-28457280-277c-11eb-8069-e1dfd4c62af2.png)

Care Package (minus DB), though the logs only seem to go back to 11/14/20, so I retried Strange Academy #5 which downloaded and failed to process. Should be toward the beginning of the logs.
[carepackage.zip](https://github.com/mylar3/mylar3/files/5543474/carepackage.zip)

**Comment by evilhero** [comment]
It looks like you haven't restarted Mylar since the at least the logs were intially generated. Since it's looking for the exact same nzo_id in your SABnzbd instance, I'm just going to assume you haven't restarted since then as well (since nzo_id's are unique).

You must have had a failed download in your SABnzbd at some point, or it got flagged as being Failed - the status being reported by Mylar is a copy-pasta from the SABnzbd history so somewhere in SABnzbd a particular download got flagged as failed and it looks like it's constantly retrying it - so your CDH never gets recognised as completed and post-processing never initiates.

At this point, I'd suggest doing a restart of Mylar to clear out all the locks that seem to be happening in regards to post-processing and CDH. With any luck, the failed download won't get re-initiated again (it shouldn't unless it downloads again and then fails somehow), and you'll see downloads start being post-processed.

The 'X's by the providers at the bottom of each page indicate if the provider was last accessible - if it was, then they get the green checkmark. If for some reason it failed, or is just not online, it gets the X which means it's not responsive. You 'might' have a blocked provider or 2 - so you might need to check the Blocked Providers portion to see if anything is in there (configuration page / Blocked Providers - just click on the indexer to remove them from the list).

As far as the 2 exceptions you pasted, both are dealing with the search and aren't stopping subsequent searches from occuring - just the issues that are being referenced in those searches are being ignored. It looks like one is from the DDL and due to a parsing problem (the parenthesis one), and I believe the other one is possibly related to an nzb provider being offline. I'll have to check more into those two particular errors tomorrow when I have more time.

**Comment by Serneum** [comment]
Makes sense. I'll restart Mylar. I do have a failed download for an issue 0 of a comic. That one seems to have tried several times before and after my last restart (from right around when I filed this issue). I've marked that issue as Ignored and we'll see if that helps as well

**Comment by Serneum** [comment]
It looks like your last tips did the trick. It's downloaded at least one issue almost every day this week. I'm going to mark this as closed. Thanks!
