### ISSUE TITLE
Manual Post-Processing does nothing and shows exception in logs

### ISSUE THREAD

**Issue by iammortimer** [mylar3/mylar3#544]
**Describe the bug**
Doing a manual post-processing does nothing and shows an exception error in the logs

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5537992/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Windows 10 2004 (19041.572)
 - Branch / commit: master [v0.4.6]
 - Python: 3.7.6

**Comment by evilhero** [comment]
Yeah, there's no traceback / exception error in the logs that pertain to a manual post-process. Only thing is involving something regarding the story arcs

Unfortunately, your logs are at an INFO level, which means they are pretty much useless when it comes to trying to figure out what it is that you're having a problem with.

I suggest you update your version of Mylar (you're 3 versions behind), put Mylar into debug/verbose mode, and then try the manual post-processing again. If you still get an exception, then create a new care-package and post that.

Note that in v0.4.9 (the latest build), under History, View Logs, View Exceptions/Tracebacks you can see at a glance any exceptions that were triggered recently - you can also view a brief log snippet that might save pasting in a carepackage depending on what the issue presented is.

**Comment by iammortimer** [comment]
Updated, but still results in the same exception (that isn't showing up in your exception screen btw)

2020-11-13 17:50:49 | ERROR | Uncaught exception: Traceback (most recent call last):File "C:\Mylar3\mylar\logger.py", line 337, in new_runold_run(*args, **kwargs)File "C:\Users\solidbeheer\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in runself._target(*self._args, **self._kwargs)File "C:\Mylar3\mylar\PostProcessor.py", line 421, in Processfilelist = flc.listFiles()File "C:\Mylar3\mylar\filechecker.py", line 136, in listFilesfilelist = self.traverse_directories(self.dir)File "C:\Mylar3\mylar\filechecker.py", line 1486, in traverse_directoriestcrc = helpers.crc(os.path.join(dirname, fname))File "C:\Mylar3\mylar\helpers.py", line 2414, in crcfilename = filename.encode(mylar.SYS_ENCODING)File "C:\Users\solidbeheer\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 12, in encodereturn codecs.charmap_encode(input,errors,encoding_table)UnicodeEncodeError: 'charmap' codec can't encode character '\u014d' in position 122: character maps to
-- | -- | --
2020-11-13 17:50:43 | DEBUG | [POST-PROCESSING] Manual Run initiated
2020-11-13 17:50:43 | DEBUG | [POST-PROCESSING] Manual Run Post-Processing enabled.
2020-11-13 17:50:43 | DEBUG | [POST-PROCESSING] nzb folder: \\MyNAS\Qdownload
2020-11-13 17:50:43 | DEBUG | [POST-PROCESSING] nzb name: Manual Run

If you need a new carepackage let me know

**Comment by evilhero** [comment]
The problem, I think at least, is that because you're on a Windows machine and you're referencing a mounted directory, it's interpreting the first ```\``` as a control character, and then using the remaining ```\``` as the actual value so it can't actually locate it (as I'm assuming it's suppose to be ```\\``` instead of '''\''')

I believe you have to either double escape the double escape with 4 slashes (so '''\\\\'''') , or just mount it as a network share then reference the drive lettered mount point instead of using the slashes (ie. ```H:\MyNas\Qdownload```).

Mylar should be able to auto-figure things out, but the last time I tried to circumvent the slash things it was a disaster (this was in the python2 version mind you). Might be worth looking at again, but not sure of a time frame ( at least for my time )...

**Comment by iammortimer** [comment]
Ok, using a mapped drive doesn't throw the exception anymore, but it doesn't seem to traverse any subdirectories.

**Comment by iammortimer** [comment]
No worries, I'll debug it through vscode and see if I can find a fix. 

If you need a hand testing windows stuff I can help out if you want. I code quite a bit in python myself, so should be able to give you some decent feedback.

**Comment by iammortimer** [comment]
so it was actually some funky filenames that caused it to throw the exception, putting a little try/except around it let it run through

**Comment by evilhero** [comment]
That's good to know - thanks for testing that out. 

The encoding crap part is a straggler from the py2 days due to how py2 handled utf-8 (or didn't as the case was I guess).

Odds are, and if you wanted to try, you can just comment out or remove that entire encoding portion and it shouldn't bomb:
```crcfilename = filename.encode(mylar.SYS_ENCODING)```
to just:
```crcfiflename = filename```

**Comment by iammortimer** [comment]
unfortunately that doesn't seem to work, if i comment out the encoding in crc in helpers.py it throws:
Exception has occurred: TypeError
Unicode-objects must be encoded before hashing

**Comment by evilhero** [comment]
Would you happen to have a few of the filenames that were causing the error ? 

I'm running thru it on my laptop now (windows 10, networked share mount to comics folder), but I'm not seeing any errors in the logs during a manual post-processing even with a normal H:\Comics kind of pathing (and with nested folders being picked up therein like 3 levels deep ). I'm getting errors during post-processing during metatagging that are problematic, but nothing involving the scanning portion.

So either my system is ultra-unique, or there's something else not being passed thru that's being missed somewhere.  My Windows system is set to the normal encoding of cp1252 - is yours set to something different ? 

Maybe if you can add:
```print('sys_encoding is: %s' % mylar.SYS_ENCODING)```
to the Mylar.py file at line 97, it will show it on Mylar startup.

**Comment by iammortimer** [comment]
Here's a one that throws the exception:
'\\\\MyNAS\\Qdownload\\@Recycle\\Complete 0-Day-Week Collection of 2019 (C0C) Pt1 [DRI]\\0-Day Week of 2019.03.13\\Little Bird 001\uf009(2019) (Digital) (Mephisto-Empire).cbr'

It's really just some very funky characters, looks like japanese encoding that throws it. No changes to encoding on my system.

**Comment by evilhero** [comment]
Is the filename on your NAS literally with the control character ```\uf009```? Does it show in your directory listing on the NAS as being exactly that, or is the ```\uf009``` decoded properly so that just the character itself is showing? 

That would be interpreted as a directory path on a nix-based system given that it's not double-escaped if it's like that, but interpreted as a control-character escape on Windows based systems. Either your system should be able to handle the UTF-8 encoded filenames and display them as such, or it doesn't and well shows something along those lines. Albeit that particular filename looks like it somehow got mangled to have the ```\uf009``` control character in there, which would lead me to think that your NAS is storing the actual control character in the filename as part of the filename instead of decoding it so the display character is presented (ie. not system UTF-8).

**Comment by iammortimer** [comment]
this is how it's showing up in explorer:
![Screenshot 2020-11-27 112339](https://user-images.githubusercontent.com/44798984/100438871-0cf33500-30a3-11eb-9f6e-f41851da3193.png)

**Comment by barbequesauce** [comment]
I believe I speak on behalf of @evilhero when I say, what the heck is that thing

**Comment by evilhero** [comment]
Yeah, that honestly looks like a corrupted filename of some sort. 

The filename, according to some quick searches, should be without the dash with the x hiding underneath it (?) - so like, normal-type. Which if that's the case and cleansing never happened, then the try/except PR that was done would definitely ignore this during a scan as opposed to erroring on it.
