### ISSUE TITLE
'dict' object has no attribute 'enclosures'

### ISSUE THREAD

**Issue by KesselRogue** [mylar3/mylar3#561]
**Describe the bug**
When doing a DDL search after the last update there is an error in NZB_Search.  The specific title that I think it's erroring on is Batman/Catwoman (2020) and it *may* have something to do with the slash in the title.
[carepackage.zip](https://github.com/mylar3/mylar3/files/5639201/carepackage.zip)

Also, ComicVine sucks.  I hope you can find a way to download issues faster than it takes the ComicVine dude to publish new issue meta because he takes his time and it's apparently "too important" for anyone else to help with.  ComicCollectorLive has a similar feature that might be of use...

**Environment (please complete the following information):**
 - OS: UnRaid 6.8.3
 - Branch / commit: Version: v0.4.9.1 (master)

**Comment by evilhero** [comment]
Looks like it's not a problem with the series you indicated, but actually with the pack that was in the search result (as that was the result prior to the actual series). The GC guys put ```- MB``` instead of, you know, an actual size or something numeric which causes the thing to barf. I'll have to scope it out when I can get to a machine later on and get it going past that.

Never even heard of ComicCollectorLive, but looks like that's all manually entered metadata for sales items ?

I've had something on the back-burner for awhile which would allow Mylar to download issues without having any relevant information on CV (ie. using the pull-list as a guide mainly), and then have the given issues in a holding queue of sorts whereby when the information becomes updated on CV, it would automatically post-process (& metatag) accordingly. Unfortunately there are alot of logistics to how the workflows all interact given different scenarios using this process and it's been painstakingly fun (/s) to work thru them, only to get tripped up on something else, while also doing all the other stuff that comes with maintaining the program. It's coming, just not sure of an ETA at this point - but for time capsule sake it's somewhere around 80-85% complete.

**Comment by KessleRogue** [comment]
CCL does both.  They have a catalog nearly identical to CV but they use that catalog to fund the store front for various sellers to peddle their wares.  The contributors there are also very anal about the meta data but they are much faster at getting information up because the seller want to sell their books.  Call it an incentive.  They have an API like CV called http://www.comicblaze.com/ where you register for a key just like CV.  I thought it might be useful/interesting to you...or not.  Just thought I'd would offer a possible alternative.

Anyway, thanks for taking a look at this problem.  I appreciate it.

**Comment by barbequesauce** [comment]
Where do you see access to the api?

**Comment by KessleRogue** [comment]
You have to contact Steve@midtenmedia.com or joe@midtenmedia.com to get the GUID.  At least that's what I had to do years ago when I wrote the Android and WindowsPhone apps for it.

**Comment by alpe12** [comment]
Same error here with Attack on Titan.

**Comment by KesselRogue** [comment]
Thanks for the fix on this, looking forward to seeing it work on my queue!

**Comment by evilhero** [comment]
Closing as should be resolved now. If not, please open a new ticket with the relevant information to get fresh eyes on it.
