### ISSUE TITLE
Moved to mylar3 - experimental no longer working

### ISSUE THREAD

**Issue by pipieye** [mylar3/mylar3#568]
Since moving to mylar3, experimental has been iffy, a few books here and there per week, but lately nothing is being downloaded automatically with experimental. Any adjustment in the parsing section to fix this? 32pag.es seems they won't be back.

**Environment (please complete the following information):**
 - OS: Mac Mojave
 - Branch / commit: master [v0.4.9, python3-dev]

**Additional information**
Currently posters have been using the format:
YYYY-MM-DD-Marvel [nn/nn] - "<comic title>.cbr" yENC
YYYY-MM-DD-DC  [nn/nn] - "<comic title>.cbr" yENC
YYYY-MM-DD-Indie [nn/nn] - "<comic title>.cbr" yENC
e.g. 2020-12-09-Marvel [15/16] - "Venom 031 (2021) (Digital) (Zone-Empire).cbr" yEnc

**Comment by evilhero** [comment]
The #573 PR should address Mylar missing those items that have the headers formatted like mentioned.

Also, fixed the iteration problem - whereby experimental and ddl would search multiple times for the same thing instead of stopping after the first run due to checking for issue number padding (1, 01 001) which is needed for nzb providers, but not for those two in particular.
