### ISSUE TITLE
DDL cant find comic on first page of GetComics

### ISSUE THREAD

**Issue by KesselRogue** [mylar3/mylar3#569]
**Describe the bug**
Zero Tolerance 1-4 is on the first page of GetComics but as a package so mylar can't get them because they are not individual issues.
[carepackage (1).zip](https://github.com/mylar3/mylar3/files/5683625/carepackage.1.zip)

**Environment (please complete the following information):**
OS: UnRaid 6.8.3
Branch / commit: Version: v0.4.9.1 (master)]

**Additional information**
Seems like this should be supported.  Comic Vine has the issues in its database so that shouldn't be a problem.  If mylar were able to pull down packages based on name and date it seems like it should be able to unzip and extract the individual issues similar to the post-processing and align them with the snatched/wanted CV records.

**Comment by evilhero** [comment]
This is already baked in, and has been since the og version of Mylar. Mylar will snatch the pack if it's available (usually first even before the individual issues) and post-process accordingly. 

I can't get to a machine to view your carepackage, but I'm betting it crapped out somewhere and stalled the search queue. Try restarting Mylar and trying the search again to see if that helps. I should be able to check your logs tomorrow hopefully.

**Comment by KesselRogue** [comment]
Wow, ok yeah, thank you.  I just checked my queue again after a few hours and sure enough its been downloaded.  I guess I wasnt patient enough.  I hit force check and restarted which usually does the trick when things sit wanted for a while bit I wasnt seeing any progress when I posted.  Sorry about the chatter.



On Dec 12, 2020, at 8:08 PM, evilhero <notifications@github.com> wrote:

﻿

This is already baked in, and has been since the og version of Mylar. Mylar will snatch the pack if it's available (usually first even before the individual issues) and post-process accordingly.

I can't get to a machine to view your carepackage, but I'm betting it crapped out somewhere and stalled the search queue. Try restarting Mylar and trying the search again to see if that helps. I should be able to check your logs tomorrow hopefully.
