### ISSUE TITLE
Mylar searches, finds, downloads best after a restart

### ISSUE THREAD

**Issue by 11001010111111101011101010111110** [mylar3/mylar3#577]
**Describe the bug**
My Mylar hasn’t worked 100% ever. It works ok but it never downloads as well as when I restart it, after which it downloads a bunch of comics. Normally it only does so very episodically, maybe a few times a month. For example, I just restarted it manually and it downloaded 13 issues. Prior to that manual restart, nothing had been downloaded in 18 days.

Can anyone help diagnose?

**CarePackage**
Carepackage was too big because of the 153MB databse. I created a smaller package with logs, ini and running env.

[Carepackage.zip](https://github.com/mylar3/mylar3/files/5731040/Carepackage.zip)

**Environment (please complete the following information):**

hotio/mylar3:latest docker image

**Comment by Budlyte** [comment]
I had this problem with the Python2.7 version, on Win7.  To bandaid it, I had scheduled a couple of scripts for every couple of days, one to kill Mylar and another to start it 1 second after.

Mylar3 is running much better, but it does seem to get backed up with stuff missing in NZBget and I still restart it once every week or so.

**Comment by evilhero** [comment]
@11001010111111101011101010111110 , you have several repeated errors in your logs all pertaining to two things: 

Error 1:
```
ERROR @ path: /volume1/downloads/comics/Sweet Tooth The Return (2020)/Sweet Tooth - The Return 02 (of 06) (2021) (Digital) (Zone-Empire).cbr] [Errno 1] Operation not permitted: '/volume1/downloads/comics/Sweet Tooth The Return (2020)/Sweet Tooth - The Return 02 (of 06) (2021) (Digital) (Zone-Empire).cbr'. Exiting...
```
And this is repeated for almost every series in the log you provided - so you have some permissions problems that you might need to work out (note that if you have enforce permissions on and your folders are on another mount / system - you should turn off the enforce permissions within Mylar as it cannot change permissions on non-local mounts).

Error 2:
```
MAIN : [ERROR] Port -REDACTED- is in use on 8090.
```
So either something is already on use on port 8090, or the system isn't properly killing the existing Mylar process in order for the new process to start up - and because of that nothing actually gets restarted, it just links the new session to the existing session so any locked queues, problems don't get restarted fresh, and remain locked. Not sure if this is a docker-type of problem or something else, as normally you would just shutdown Mylar and start it up again and any existing Mylar instances would be killed on the shutdown.

**Comment by psychogun** [comment]
Without having investigated this issue further with my installation, I have also noticed the same behaviour. 

Mylar "works" best after a restart, which I occasionally do- to get DDL fired up again. Although, DDL has not been working as expected in the last month. 

Nothing new has been snatched. I'll chime in after I have found the time to do so.

**Comment by evilhero** [comment]
@psychogun, DDL has been failing primarly to CF changing it's algorithms and making cfscrape, the 3rd party module that Mylar uses (and alot of other applications) pretty much useless as it can't decipher the keys. The author of that module has gone the way of the Dodo bird according to most, so there probably isn't going to be any update for a while in order to decipher the new CF techniques. So when CF is up on the DDL site, Mylar can't search or retrieve any results - thereby rendering the option unusable while the CF protection is active. Once the CF has been turned off (usually it's up on Wednesdays like clockwork), the DDL's will work as per normal.

I have a workaround coming for the CF thing, but it requires the use of a proxy server that's setup locally (has to reside on the same machine as the Mylar instance from my understanding) in order to help bypass CF protection. However the proxy-server can be setup via docker and is used as an optional installation by Jackett already (so if you have Jackett, you might have had to install it depending on your site usage).

**Comment by psychogun** [comment]
@evilhero , thank you for a thorough explanation.

I have not used proxy-server with Jackett, and I do not think I need to, yet,  anyway - everything seems to be working normal in that regard.

I'll be looking forward to DDL coming back to Mylar :)
