### ISSUE TITLE
Timeout when searching StoryArc for “Infinity”

### ISSUE THREAD

**Issue by RyanRadly** [mylar3/mylar3#580]
**Describe the bug**
When searching StoryArc for “Infinity” eventually mylar3 times out (nginx throws a 504 for the domain).  Does not persist with any other qualifier added - “Infinity War” “Infinity Gauntlet” etc. search fine.

**CarePackage**
CarePackage.zip attached: [carepackage.zip](https://github.com/mylar3/mylar3/files/5740267/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Host Debian 10 running hotio/mylar 3 Docker container (Alpine 3.12)
 - Branch / commit: ea82fbe71d1f3719f15f8db8dc9e2da08b9fd92f (python3-dev)

**Additional information**
Nothing constructive; just love and appreciate your work.

**Comment by evilhero** [comment]
I'm guessing it's probably due to the sheer volume of the issues it has to pull down - when Mylar retrieves arc information from CV, it pulls down the data for each series associated with it - so it can take a few seconds per arc for it to gather all the relevant info to display.

I just tried it, and it did eventually display - but it took a full minute and about 15s to retrieve the results, which isn't great - but it's not timing out from CV at least. 

By default nginx defaults to a timeout of 60 seconds, which would put the response beyond that limit - can you try increasing the timeout in your nginx for the mylar url like the snippet below (note that I'm thinking it's the read that needs the increase, but send might be a part of the call as well) and see if that helps in the interm at least:
```
   location /mylar {
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
   }
```

**Comment by RyanRadly** [comment]
D'oh. Of course that's what it was.  Thank you for the nudge.  nginx is Docker-fied as well so I just went ahead and threw an extra config into /conf.d and sure enough.
