### ISSUE TITLE
'Internal Server Error' reported when trying to view the cover of a downloaded comic

### ISSUE THREAD

**Issue by holdeni** [mylar3/mylar3#585]
**Describe the bug**
For a comic that I have downloaded, when I click the orange I button, instead of the cover image (which I believe it was to show), I get the HTML for an error returned by the Mylar3 code instead. The relevant text of the page is as follows:
[carepackage.zip](https://github.com/mylar3/mylar3/files/5744842/carepackage.zip)

        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/henry/Applications/git/mylar3/mylar/webserve.py", line 5904, in IssueInfo
    issuedetails = helpers.IssueDetails(filelocation, IssueID=issueid)
  File "/Users/henry/Applications/git/mylar3/mylar/helpers.py", line 1530, in IssueDetails
    file_info = getimage.extract_image(filelocation, single=True, imquality='issue', comicname=comicname)
  File "/Users/henry/Applications/git/mylar3/mylar/getimage.py", line 183, in extract_image
    return {'ComicImage': ComicImage, 'metadata': metadata, 'rawImage': RawImage}
UnboundLocalError: local variable 'RawImage' referenced before assignment

**CarePackage**
Attached

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - Branch / commit: python3-dev/d1d6989

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Orange icon would mean it's a cbr with no attached metadata (usually). In order to figure it out tho, I'd need to actually have the cbr file you're trying to view - is there anyway you can link it somewhere so that I can test it out to see what's happening?

**Comment by holdeni** [comment]
I’ll see if I can figure out a way to provide the .cbr/.cbz file.

——-
Sent from my Big & Wide iPad
... Ian

**Comment by holdeni** [comment]
I haven't found a convenient way to share a .cbr file. I have some technical abilities so can you tell me what you are looking for in the .cbr/.cbz archive as metadata? I'll see if that is present in the file or not to at least help whether this is a true error (though even if metadata isn't present, the UI presentation should be better spewing the error into the modal window) or a different issue.

**Comment by evilhero** [comment]
Well since, the cbr should not have any metadata in it, that's not the stumbling block in this case. Yes people do store metadata in cbr's, but it's not the defacto-standard that's been around for years - which is to store the metadata in a zip. I have a feeling it might be something to do with being on a MAC or possibly trying to use CBL tags in a cbr (not saying that's the case, but guessing). 

The UI will display with a large hazard sign with some warnings if it can't read the file properly - however in this case it's a traceback error so it never gets to the UI aspect to draw it.

The reason why I'm asking for the file is so that I can run it thru tests on non-MAC systems and see what it spits out in regards to errors (or anything) and then code in the corrections as needed.

You can email me the cbr here: EH @ mylarcomics.com

**Comment by evilhero** [comment]
Assuming resolved since the great merge of 2021 and 2022. 

If not, please open a new issue with the relevant information.
