### ISSUE TITLE
Parent Folder Directory CHMOD Not Respected

### ISSUE THREAD

**Issue by undaunt** [mylar3/mylar3#607]
**Describe the bug**
If I have my directory structure setup as, for example, $Publisher/$Series ($Year), my CHMOD setting of 775 is properly applied to the comic folder, but not the parent publisher folder. As an example, I just added Rick & Morty, published by Oni Press.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5823268/carepackage.zip)

**Environment (please complete the following information):**
 - OS: LSIO Docker on Ubuntu 20.04
 - Branch / commit: Master 0.4.9.3 (build ac29fdbac4acd054523290a5564d24b3720dd2f6)

**Additional information**
The parent folder is set to 777 (the default) instead of my custom setting of 775.

**Comment by evilhero** [comment]
Looks like this might be the case - I can confirm some 777 permissions on publisher folders in my setup (Ubuntu), but not quite sure if this is caused by the default umask (which would probably be 777 - not Mylar), or something different. 

So this will probably require a deeper look (since it doesn't individually create the folders, but the tree all at once using an internal python function).

Can you confirm what version of python you're running with Mylar ?

**Comment by undaunt** [comment]
@evilhero Both my host OS as well as the Linuxserver docker container are both on version 3.8.5 per a python3 --version.

**Comment by evilhero** [comment]
I'm having to redo the permissions aspect within Mylar as it seems to have broken on some systems (mainly ubuntu from the looks of it, but possibly more Linux-based systems) when we migrated to python3. This is due to the function that Mylar uses to create nested directories that sometimes doesn't adhere to the permissions (it's a known problem). 

It only applies to those that have a multi-directory folder format setup from the looks of it, and only to the parent folder - but it's still an issue that needs fixing. 

I have a fix almost done, just trying to get it to provide an option to do it retroactively so that it can fix previously created items if necessary.

**Comment by barbequesauce** [comment]
@undaunt I believe this is fixed, can you confirm please?
