### ISSUE TITLE
Ability to Ignore Issues - Remove from Issue Count

### ISSUE THREAD

**Issue by rutskiuk** [mylar3/mylar3#609]
Would it be possible to ignore issues and remove them from the issue count?

I have noticed that some of the comics I have in my library are complete runs but show as missing preview issues which in many cases are no more than a page of the first issue of the comic. These do not exist for collection and I could go and manually create it but I think it would make far more sense if I were able to ignore it. I have done this most recently with this comic:

https://comicvine.gamespot.com/destiny-a-chronicle-of-deaths-foretold/4050-5947/

However the episode doesn't seem to be ignored because I am still shown in the list of downloads that I am missing an issue, surely if I have ignored it then I have already chosen not to see it.

Windows 10
Version: 2100583ea0609c8c2c9243b2ff6dcfb42492e7de (master) 

Ignored issue
![image](https://user-images.githubusercontent.com/25068977/104821376-42aad380-5833-11eb-9602-1ef44ce7da04.png)

Still being counted (not ignored)
![image](https://user-images.githubusercontent.com/25068977/104821383-59e9c100-5833-11eb-9f2a-5aa2b39dd98d.png)

I wasn't sure if this counted as a bug or intentional design.

**Comment by evilhero** [comment]
There is 1 of 2 settings in the config.ini that would need to be changed (not both, one or the other) in order to get the ignore option to work as expected based on your requirements. This is due to how various users have differing expectations as to what they want to see when they use the ignore option.

```ignore_havetotal (True/False)```: Will keep the total issues of the series the same but will count the Ignored issue as if it were present (for counting sake only) - so in your example, it would show 4 / 4.

```ignore_total (True/False)```: Will reduce the total issues of a series by the number of ignored issues. It will not count the Ignored as part of the issues you have. So in the example above it would indicate 3 / 3.

Setting both values to True will do the same as having both set to False (meaning that it will show as you have it now 3/4). For the OCD types I would imagine the ```ignore_havetotal = True``` would be the option to use so that the true issue counts can be realised, while still ignoring the chosen issues.

**Comment by rutskiuk** [comment]
I have checked my config.ini and I have ignore_havetotal set to False and ignore_total set to True however my total still shows 3 / 4
I haven't changed the config file in a long time so I presume I set it this way a long time ago.

**Comment by evilhero** [comment]
Did you perform a Recheck Files and or Refresh Series?

I just tested both options on my end here and everything works as I indicated above. You have to do a Recheck / Refresh after you've changed the option (it only affects things going forward, it won't go back and update by itself unless told to do so).

**Comment by rutskiuk** [comment]
That has done it, thank you!
