### ISSUE TITLE
Issues that have been fulfilled still show as wanted in Weekly Pull section

### ISSUE THREAD

**Issue by edimusxero** [mylar3/mylar3#618]
**Describe the bug**
Various downloaded issues show as wanted under the weekly pull section.  I have tried to refresh and recreate the pull list but they still show as wanted.  They do not show as wanted under the "Wanted" section.  

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5843311/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu lts 20
 - Master

**Comment by evilhero** [comment]
What issues are you saying that are in the wrong state?

The pull is a seperate entity from the Wanted due to the fact that the pull is from a different source other than CV. 

If CV doesn't have data for the issue yet, Mylar will mark the given issue as Wanted on the pullist, and put it in the Upcoming section of the Wanted tab (at the very bottom of the page). At this point its just informational - it's telling you it knows there's an issue that's coming out (or is already out), but there is no information on CV available for it to link it to. So any issues that appear in this section, do not get searched for /post-processed against. 

Once the CV data is present and is loaded by Mylar, then it marks it as Wanted and it shows up in the Wanted section - meaning it can now be searched for / post-processed against.

I'm guessing you possibly downloaded a bunch of comics (a pack maybe), and mylar isn't picking them up due to not having any CV data yet for them? (haven't fully looked at the carepackage yet)

**Comment by evilhero** [comment]
question answered above -  closing
