### ISSUE TITLE
Mylar downloads Birthright v1-7 over and over again

### ISSUE THREAD

**Issue by KesselRogue** [mylar3/mylar3#619]
[carepackage.zip](https://github.com/mylar3/mylar3/files/5852390/carepackage.zip)

**Describe the bug**
I added the Birthright series (not the TPB's) to my queue as "Wanted" and Mylar snatched them all but then proceeded to start downloading the TPB's 1-7 in a loop over and over again.  I had to manually remove the completed TPB's from queue and then abort the download and restart to finally clear it out.

**Environment (please complete the following information):**
 - OS: Unraid 6.8.3
 - (build 813397ba3e70df7996909f04e009de91fae324b2)

**Comment by KesselRogue** [comment]
Also, the TPB's that were downloaded were ignored by post processing.

**Comment by evilhero** [comment]
So it looks like there are multiple problems going on with this:
- it matches the relevant issue number to being in a pack, marks all the issues as Snatched and tries to download them. This part is fine and works.
- problem 1 is that the links that are available for the pack that has issues 1-40 are non-existent, so it can't grab the actual issue ones. Mylar sees the TPB links that are available (which are 1-7 TPB volumes) so it attempts to download those (as it says in the logs: 
```[DDL-QUEUER] This pack has been broken up into 7 separate packs - queueing each in sequence for your enjoyment.``` The 7 packs it indicates are for the TPB's, since the pack with issues isn't available.
- The issues get queued to download (the TPBs 1-7 are individual downloads) and then the subsequent search starts for a subsequent issue in the Birthright series. 
- This is where problem 2 lies: we're apparently not checking the current status of the given issue at this point, which was set to Snatched as per above, so it finds the pack match (1 - 40 + TPBs) and proceeds to try to download the pack, again. Since the pack with the issues isn't available, it queues up the TPB's and off we go, again.
- Even tho it downloads the TPBs knowing they're part of the overall pack (it doesn't know until it downloads and extracts), the post-processing is smart enough to know that they're not right and ignores them during post-processing.

In the end, this really comes down to how the DDL option is basically at the whim of w/e direct option is provided to the users, which we have zero control over.  Mylar see's what's available, and picks the options it can grab, but they end up being the incorrect ones even tho there are other options presented for the main pack (that are crap).

I can try to build in some logic around the incorrect aspect, but it's really a crapshoot and luck if it will hold for other titles that may have the same problem. However, we definitely can build in something around the re-downloading however, as it should be checking the status prior to performing the actual search (and it was at one point, not sure what happened).

**Comment by barbequesauce** [comment]
tried this morning, can't reproduce - assuming fixes are in
