### ISSUE TITLE
Post process hangs when dealing with StoryArcs

### ISSUE THREAD

**Issue by phairplay** [mylar3/mylar3#631]
**Describe the bug**
processing hanging when trying to grab comics for storyarc

**CarePackage**
[mylar.log](https://github.com/mylar3/mylar3/files/5933031/mylar.log)
attached contain an error when trying to process a comic for King in Black
recent error 05-Feb-2021 14:14:00
carepackage was too big

**Environment (please complete the following information):**
 - OS:Windows10
 - Branch / commit: Version: v0.4.9.4 (master)

**Additional information**
normal comics are fine a process without issue

**Comment by evilhero** [comment]
You're going to have to get a debug log if you're going to attach just the log, as the INFO level logging just isn't enough information to gleem anything concrete from.

It has something to do with either your one-off directory not being set (do you have a value in your ini set for grabbag_dir), or something related to that aspect.

But yeah, we need the full debug log from the snatch of an arc issue to the failed post-processing attempt (it will throw a traceback error from the looks of it).

**Comment by phairplay** [comment]
sorry 
please see below
[mylar.log](https://github.com/mylar3/mylar3/files/5933604/mylar.log
thank you for looking into this

**Comment by evilhero** [comment]
The carepackage generated a clean-config.ini, can you paste that as well? (sorry should have asked to include that one earlier)

One of the config settings isn't being shown in the log and trying to narrow it down based on a best guess isn't the greatest way to figure things out.

**Comment by phairplay** [comment]
[clean_config.zip](https://github.com/mylar3/mylar3/files/5933892/clean_config.zip)
:)

**Comment by evilhero** [comment]
In your Story Arc Management page, is your Arc Folder Format set to None or does it display a value like below:

![](https://colder.thanyou.xyz/selif/7sg4llpq.png)

I thought we had setup a default value but from the looks of it, it was never set. Since you have ```StoryArc Directory``` enabled, Mylar needs to know the folder format so it can create it - this should be set to a default value which I'll fix shortly. 

But in the meantime, you can just set it to ```$arc ($spanyears)``` which would then create a StoryArc folder for the given arc under the StoryArc directory (shown just above that). So if you set it to that, a folder could be created like ```Massively Big StoryArc (2019-2020)```.

**Comment by phairplay** [comment]
Brilliant thank you 
Arc folder format was set to none
How do you automatically have it set story arcs to wanted?

**Comment by evilhero** [comment]
ATM, you can't currently do it automatically - mainly because the arcs don't update automatically like Mylar does with series. 

So to update an arc if it's not showing the latest issue, you'll have to use either the refresh icon listed beside each arc on the StoryArc Management page, or the ```Refresh Arc``` option located within each specific arc listing. 

This is one of the straggling points behind us eventually going to a new arc system, but in large part it's due to the inability of how StoryArcs are treated within the CV ecosystem and how they can mish-mash duplicate items in an arc. So it's all coming, just not atm obviously.

You can mark relevant issues to a Wanted state, and then once they're in that status Mylar will search for them (```upcoming_storyarcs = True```) and even display them on your Wanted list (```search_upcoming = True```).

**Comment by phairplay** [comment]
Great many thanks for your continued support.
