### ISSUE TITLE
Error running ComicRN.py for post processing

### ISSUE THREAD

**Issue by war3zlod3r** [mylar3/mylar3#639]
using Sabnzbd and Ubuntu 20.10

After the nzb get downloaded and the script tries to run I'm given this error:

Traceback (most recent call last):
File "/home/war3zlod3r/scripts/ComicRN.py", line 13, in <module>
import autoProcessComics
File "/home/war3zlod3r/scripts/autoProcessComics.py", line 4, in <module>
import urllib.request, urllib.error, urllib.parse
ImportError: No module named request

**Comment by evilhero** [comment]
I'm guessing you're running the python2 version of SABnzbd. The ComicRN scripts isn't run by Mylar, but it's run by SABnzbd and therefore uses its version of python.

If you're not wanting to update SABnzbd to a recent version for some reason, you would have to use the autoProcessComics.py and ComicRN.py scripts from the original Mylar repo (for python 2), with no guarantee that they would work since its from a prior version being used with the new version.

Or you could just enable Completed Download Handling and not bother with the scripts aspect, as another alternative.

**Comment by war3zlod3r** [comment]
Running sabnzbdplus, what’s the package name for the build I should be running?

**Comment by evilhero** [comment]
SABnzbd is the same as sabnzbdplus, everyone just shortens the name. The version is within the SAB program itself. 

You should be running the 3.x version of SAB if you want to use the Mylar scripts.

**Comment by war3zlod3r** [comment]
I just double checked and I'm running 3.1.1 with py 3.8.6 
![image](https://user-images.githubusercontent.com/33874111/107863365-83d5d980-6e19-11eb-8db9-0f6b019d50a7.png)

**Comment by evilhero** [comment]
Well if that's the case, I don't know what to tell you - urllib is a standard module bundled with every python version.

Either you have a urllib installed that's corrupt (which would mean other things are messed up I'm guessing), or its missing entirely for some reason.

Maybe check to see if you installed urllib via pip which would have installed something incorrectly possibly.

**Comment by war3zlod3r** [comment]
It does seem like its trying to run the ComicRN.py with py2.7 not sure why, whats the difference between using it and CDH?

**Comment by evilhero** [comment]
The diff? That you don't have to go thru all of the problems associated with setting up scripts that can occur really. CDH is literally just enabling the option in the Mylar GUI. 

CDH knows the exact issue and series that a given file is attached to prior to initiating post-processing. ComicRN on the other hand has no idea and has to parse the filename in order to try and figure out what it is (akin to manual post-processing).

We've tended to push people more towards using CDH vs the scripts with Mylar3 as it's more accurate, but there are some use cases for the script.

**Comment by war3zlod3r** [comment]
Great I'll just use that then thanks!
