### ISSUE TITLE
Comics not downloading? Cannot restart DDL queue.

### ISSUE THREAD

**Issue by daysonfeliz** [mylar3/mylar3#640]
I have about 380 comics that it is failing to find sources and download. When I look at the log, it says it found 12 sources for XYZ comic, but then it says it could not find any links DDL (api)... It was working fine last night and downloaded over 1,000 comics.
[carepackage.zip](https://github.com/mylar3/mylar3/files/5977110/carepackage.zip)

I tried restarting the DDL queue but I get an "error has occurred" notification. Any help?\

Attached is care package. 

**Environment (please complete the following information):**
 - OS: Unraid Server
 - Branch / commit: [latest]

**Comment by barbequesauce** [comment]
Your config shows that you've chosen SAB for an NZB grabber, but not configured it. As you have Experimental active you'll need something for Usenet, SAB or NZBGet or Black Hole.

It has been finding your issues on the experimental index, but due to the above it's been crashing - and killing the search queue.

**Comment by barbequesauce** [comment]
Please reopen if this is still occurring.
