### ISSUE TITLE
dognzb no working 

### ISSUE THREAD

**Issue by gibbe211** [mylar3/mylar3#643]
Hi Y'all im facing issues with dognzb api not approving when I test the connection 

Hope any can help me with that 

and another think I'm facing is that nbz.su is not grading any series but when I do a search on there main site I do get all the issues I'm looking for 

I'm running the python3-dev on my Mac mini Big Sur 

would love to here from anyone that can solve the issues I'm facing 

in regards

**Comment by evilhero** [comment]
Go to the configuration page in Mylar and generate a carepackage file. Attach that to this issue and we can see what's going on.

As far as searching, naming matters. If Mylar is searching for ```Big Dog```, and your nzb provider has all the results as ```Big As A Dog```, it will not match as they're considered different titles.

**Comment by gibbe211** [comment]
well dognzb seems to work successfully now but I'm still having issues regarding mylar not find any comics 

(Marvel) [Excalibur] 2020

**Comment by evilhero** [comment]
again. post. a. care. package.

**Comment by gibbe211** [comment]
ive did that and ive gotten 4 files in care package map

**Comment by gibbe211** [comment]
oh you mean the hole folder 


sorry but im really new to this kind of stuff

**Comment by evilhero** [comment]
you need to attach the carepackage.zip file to this issue using the paperclip button on github

**Comment by gibbe211** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/5997604/carepackage.zip)

**Comment by gibbe211** [comment]
but when you say that naming has to be the same as the nab indexer site how does a person know how to properly name the serie

**Comment by evilhero** [comment]
The title within Mylar has to match / be very close to the name found on the indexer. It also has to match other things, but the name matching is where it all starts. If you're searching for ```Excalibur 001 (2020)```, it won't match up to ```Excalibur v01 - The collection``` or the like - it has to contain the series title, the issue number if there is one and/or the issue year if it's possible. For the most part if it's a normal type of naming Mylar can find the issues just fine and there's nothing you can do to correct the naming of things on the indexer. The alternatives are usually finding other sources.

NZB posters are notorious for posting issues that don't follow a conventional naming pattern - let alone sometimes the people that actually scan in the comics. I don't see any matches to what you're searching for in your logs - so the issue isn't present on your indexer from the looks of it or it's some kind of messed up naming (dognzb sometimes has problems due to them removing all punctuations). Try enabling Experimental Search within Mylar (it uses a free nzb indexer), and try searching again - you should find a few on there.

Mylar did download a few issues, but you don't have post-processing enabled so the issues will never get moved/processed out of your sabnzbd completed directory.

**Comment by gibbe211** [comment]
okey so my understanding is 

1 enable experimental 

2 enable post prossecing 

if i understand you correctly

**Comment by gibbe211** [comment]
btw forgot to ask can you have both Sabnzbd and torrent client like ruttorent enabled at the same time 


since ddl offers .torrent file

**Comment by gibbe211** [comment]
and GetComics always have the new stuff first comparing to nzb indexers

**Comment by BRTPOB** [comment]
Yes. I have both enabled. You can't have two torrent or newsgroup downloaders enabled, but you can have DDL, torrents and NZBs all enabled at once.

**Comment by gibbe211** [comment]
okey ive done according to your suggestions and I did a restart just to be sure 

let met test if it finds what I'm looking for 


btw amongst nnz indexers which one would you say have the latest greatest issues

**Comment by gibbe211** [comment]
love GetComics since they always get it first

**Comment by gibbe211** [comment]
[carepackage-2.zip](https://github.com/mylar3/mylar3/files/5997775/carepackage-2.zip)


here a new care after enabling stuff

**Comment by evilhero** [comment]
DDL won't be set to your torrent client - it downloads it directly within the Mylar client. To use any torrent client with Mylar you'd need to use jackett.

**Comment by gibbe211** [comment]
I see thanks 

I almost sure I did run that command

**Comment by evilhero** [comment]
All the errors that are showing up in your logs are saying that you're not running the right versions of certain things - all of which are usually installed by installing the requirements.txt file.

**Comment by gibbe211** [comment]
okey sorry ive was almost curtain 

but boy was I wrong 


is it to late to run the command now by shutting down mylar first ?

**Comment by evilhero** [comment]
You shouldn't run that with Mylar running. I mean, you could - but it's probably not the best idea. 

And yeah, you can run it at anytime.

**Comment by gibbe211** [comment]
yeah ive thought it would be best not to change anything while running mylar


but I'm doing that now

**Comment by gibbe211** [comment]
btw evilhero can I make a feature request to you here and now or do you prefer me to do elsewhere

**Comment by evilhero** [comment]
It's best if it's a feature request to create a new issue so that things don't get lost in all of the posts in this issue.

**Comment by gibbe211** [comment]
I'm going nuts with naming the comics right 

I'm guessing that because I'm not having the same name as the site there for no results 

my issue is that I'm no sure how to name a series properly 

for example amazing x-men 

ive tried 

amazing x-men
amazing xmen
amazing x-men 2014  
amazing xmen  2014

but for some reasons it can find some and some not

**Comment by evilhero** [comment]
Where exactly are you changing the name ? You can't change the name that Mylar searches for - that's based on the actual name of the series (you can use Alternate SearchName, but that's not what you're using obviously).

Renaming your local files doesn't affect what it searches for - that affects the ```have``` file count that's listed within Mylar and whether a given issue shows as ```Downloaded``` or some other status.

**Comment by gibbe211** [comment]
<img width="1280" alt="Screenshot 2021-02-17 at 20 59 19" src="https://user-images.githubusercontent.com/79160522/108260841-17cddb00-7163-11eb-896b-ea45dbb43e00.png">

hmmm weird I thought I did do a alternate......

**Comment by evilhero** [comment]
There's no point in putting the same thing as is given for the series, as it's already being searched for by that name. I'm guessing the problem is the V2 aspect - if something is stated as a volume, it has to match or be presented as such in the search results. Odds are the titles you are searching for don't have the V2 or are labelled as a different volume and aren't matching up - I'd need to see a carepackage tho to see exactly.

Also, you probably want to enable debug/verbose logging by default to ensure that you get full logging - with Mylar not running set your ```log_level = 2``` in the config.ini (you can also use the ```-v``` switch on your startup command to set it that way as well if required).

**Comment by gibbe211** [comment]
great thanks will do 

give me a sec

**Comment by gibbe211** [comment]
[carepackage-3.zip](https://github.com/mylar3/mylar3/files/5998329/carepackage-3.zip)


here you go I really hope that you can find the issues and help me solve it since I REALLY do love your work and hard effort

**Comment by evilhero** [comment]
That's a certificates problem.

Go into your Applications folder, and then your python installation. 

In that directory you'll see a file called ```Certificate.command```. Either run that file by clicking (double-clicking?) on it, or via the command line: ```install Certificate.command```

Then try the search again and see what happens (note that you might want to make sure Mylar is either not running or you restart it after you do the above)

**Comment by gibbe211** [comment]
oh so that's may why I'm keep getting python traceback error


will do give me a sec

**Comment by gibbe211** [comment]
here's a new made care zip

I did run the command by dubble click it like you said 

and mylar did not run so I did shut it down before doing the steps 


still no luck 

[carepackage-4.zip](https://github.com/mylar3/mylar3/files/5998462/carepackage-4.zip)

**Comment by evilhero** [comment]
Your ```git_branch``` variable is set incorrectly in the config.ini - not sure how you installed it, but you either have to be on ```master``` or ```python3-dev```.

As far as the logs, there's no more ssl errors in the logs. It's searching but not finding anything as of yet.

**Comment by gibbe211** [comment]
ive changed to dev now 

I see so is it possible to make it find stuff would be great 

or I'm I missing sum out

**Comment by evilhero** [comment]
Just find something to download and keep on trying. It's going to be hit and miss depending on what it is that you're searching for in some cases, and/or it'll throw an error if something is amiss. Try adding a series from the weeklypull from last week (since this week's info isn't updated yet I believe), and then searching for the newest issue from that series - it should be able to find that at the very least.

**Comment by gibbe211** [comment]
okey thanks sos so much for your help

**Comment by gibbe211** [comment]
but one last question according to you what would be the best nab indexer for find the most comics and latest issues ?

**Comment by gibbe211** [comment]
and also what do you think of my feature request is it doable in the near future

**Comment by evilhero** [comment]
I'm not going to say one indexer is better or worse - there are several options available to be used and I'm not getting a cut from anyone as to promoting their sites, but nzbgeek, althub, and probably nzbsu (albeit with caution) are amongst the ones that seem to have a nice amount of comics.

As far as the feature request, doing something like that would require a massive overhaul of the existing Mylar code, and it's really (and I mean really) outside of the scope of my ability.
