### ISSUE TITLE
Check post process folder before snatching

### ISSUE THREAD

**Issue by smstarrant** [mylar3/mylar3#647]
**Describe the request**
I would like Mylar to check the post process/download directory before doing a normal search/snatch when adding new titles or changing status to "Wanted".

**How did you come up with the idea?**
Frequently when adding new comics I have already downloaded an issue and have it sitting in the directory to be processed, yet Mylar will go out and search for it, downloading it a second time.

**Environment (please complete the following information):**
 - Windows 7
 - Branch / commit: Master branch

**Comment by evilhero** [comment]
Only problem with doing this is that many users seed from the check folder directory which could contain hundreds if not thousands of files. Having to scan that folder on every search would be a massive waste of resources along with a very large time increase per search. 

I understand the reasoning and the requirements, just not sure how to correctly implement this so that it appeases everyone without loosing functionality.

**Comment by leaderdog** [comment]
I like this too.  Could be an option that is off by default for those that use torrents.  And for those that download it all in advance, or while looking for other books you grab issues you want and need to add, then we just toggle it on and everyone is happy? ;)

I would think, with an option to turn it on, Mylar would just issue the manual post process command before rss search?

**Comment by evilhero** [comment]
Since Mylar doesn't monitor torrent clients for completion, they need to have Mylar monitor the given completion directory. They do this by setting their torrent completion folder for comics to the Check Folder location within Mylar and setting the option to copy/hardlink. Mylar will not copy / move / delete / post-process anything that's still in the process of being written to, nor will it move/copy items out of that folder if those torrents have already been post-processed (it checks via stored file-hash).

Also any command in regards to post-process would have to be run before any searching regiment started.

But I'm not fond of penalising users who use torrents even more, since they also don't have CDH available to them. Which is why I said it'd have to be available without losing functionality.

**Comment by evilhero** [comment]
Use the ``folder_cache_location`` in the ``[Post-Process]`` section of the config.ini. Specify the directory location you want to be checked prior to each search being performed. Note that it caches the names of the files directory in the directory every 10 minutes, so it doesn't constantly have to check the same thing over and over.

Closing since this has been present for awhile now.
