### ISSUE TITLE
Unable to retrieve URL for volume.

### ISSUE THREAD

**Issue by ducky0518** [mylar3/mylar3#648]
**Describe the bug**
I'm using the new version you created 2 days ago with a super simple setup (only DDL configured).

Comicvine is working correctly, because I see the current list of comics under "This Week" and I can move between weeks. But once I "add" or "watch" a series, if you look at the logs, it says the following:

2021-02-21 21:53:23 | ERROR | Unable to add / refresh the series due to inablity to retrieve data from ComicVine. You might want to try abit later and/or make sure ComicVine is up.
-- | -- | --
2021-02-21 21:53:13 | WARNING | Unable to retrieve URL for volume. This is usually due to a timeout to CV, or going over the API. Retrying again in 10s.

**However, I'm CERTAIN that I'm not over the API limit for 2 reasons.**
1.) I can fetch the various weeks just fine, even new ones that I've never went back to, which obviously uses the same API and ..
2.) Here's what the Comicvine API states:

Current API Usage
You have used 10 requests in the last hour for API Path '/volume' (reset in 18 minutes)
You have used 10 requests in the last hour for API Path '/issues' (reset in 18 minutes)
You have used 21 requests in the last hour for API Path '/volumes' (reset in 18 minutes)
Your request rate is fine

**CarePackage**
See attached

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Branch / commit: 0.4.9.5

**Additional information**
This doesn't make any sense as to why it's failing especially since its working for some data. I've tried several different series to make sure it wasn't just one of them.
[carepackage.zip](https://github.com/mylar3/mylar3/files/6018477/carepackage.zip)

**Comment by evilhero** [comment]
The ```This Week``` listing doesn't use the CV API at all - your ability to retrieve data from CV when going between weeks and/or viewing a specific week doesn't impact it.

It is exactly what it's saying - the device you're running Mylar on cannot access CV. This could be due to going over the API limit, for hammering (if you use the same CV key in more than one application that's accessing it), or even a DNS-related issue specific to your system/location.

Are you sure you entered the CV API Key correctly (ie. no trailing spaces at start / end, the i's, o's, are all the correct captilization, etc) ?

**Comment by ducky0518** [comment]
Got it. I found the issue in the API key. That's my bad. Sorry to raise the flag and thanks for the quick response.
