### ISSUE TITLE
Takes for ever to snatch a issue 

### ISSUE THREAD

**Issue by gibbe211** [mylar3/mylar3#653]
**Describe the bug**
Im experiencing an issue regard snatching issues and takes a long time up to 1 day efter ive changed the comic to wanted and it started to search my nzb and ddl
[carepackage-5.zip](https://github.com/mylar3/mylar3/files/6036917/carepackage-5.zip)

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: Mac OS Big Sur
 - Branch / commit: latest python3-dev

**Additional information**
takes a long time up to a day until it snatches anything

**Comment by evilhero** [comment]
Well I mean you have around 2000 Wanted issues - the RSS fires off every 20 minutes, but since nothing old has been posted (majority of your issues are not weekly releases) during the given RSS capture, it never finds anything. 

So then you have to wait for the 6-hr search scan to kick off, and that submits a query to each of your providers in provider order sequence until it either finds a match, or cycles thru them all. It has to do that for each issue on your Wanted list. Going thru individual search queries over 2000 times can take more than a few minutes to say the least (do it in your head even - 2000 issues / 1 query to each indexer every minute, sometimes more than 1 query depending on the title).   Add on alternate search names and issue numbering (ie. 1, 01, 001 are all considered different when querying an indexer), and it increases the hits/time even more.

There's some issues I'm seeing and have been talking with some users about how often Mylar is querying an indexer's API (meaning that most times there isn't a pause between searches on the same provider, which is bad) - so if anything, future patches might increase the time frame so as to not get Mylar users in trouble with the indexers, or even a ban.

If you want a specific issue immediately, then you would use the magnifying glass icon on a series detail page for a given issue in order to force search for that one specific issue (which is the same thing as what the 6r search is doing, but it's only doing it for 1 issue as opposed to say 2000, of which the one that you're looking for is in the middle of the pack).

**Comment by gibbe211** [comment]
sorry for late reply, well fair enough 

but one thing ive noticed is that mylar snatches a lot of stuff which is very nice 

but for example lets say uncanny x-men 1981 has around 500 some issues and mylar find some issues and some not 

now im interested if there is a workaround so that mylar snatches all issue instead of some and some not

thanks in advance 

[carepackage-6.zip](https://github.com/mylar3/mylar3/files/6054733/carepackage-6.zip)

**Comment by barbequesauce** [comment]
If they are all available and the naming convention matches the snatched ones, it will get them eventually - remember that the search & download activity can be misconstrued as a ddos attack; we space out requests to protect ourselves...

**Comment by gibbe211** [comment]
great thank for letting me know 

but my sixth sense is telling me that its the name convention  that makes mylar not find some comics 


but lets say that its the naming that's failing how does one rename the comic so nzb indexer and mylar "talks the same lang"there for mylar can snatch it 

thanks

**Comment by evilhero** [comment]
Use the Alternate Search Name in the Edit Settings tab for a specific series.

Keep in kind that naming convention can be anything related to the series. It could have the nzb labelled as the incorrect volume (v2 vs a v3), improper issue year, or that the naming convention has other crap that screws up the parser or is just not a naming convention that mylar understands.

With older series, you'll tend to find ALOT of crappy named nzbs due to how usenet is in general.
