### ISSUE TITLE
Is the released .tar.gz changing?

### ISSUE THREAD

**Issue by fryfrog** [mylar3/mylar3#690]
Hi, I maintain the AUR package for [mylar3](https://aur.archlinux.org/packages/mylar3) and it seems like the source `.tar.gz` file is changing. You can see in the comments we've seen 3 different sha256sums. Is the source being updated somehow?

Edit: I realize I could have been a little more specific. We've gotten 3 different sha256sums for the v0.5.0 `.tar.gz`.

**Comment by barbequesauce** [comment]
Assuming you're using the master branch, we had a merge from dev two days ago and then 22 days prior to that... does that line up with your observations?

python3-dev branch sees merges almost daily... so that tar ball would be regenerated quite regularly...

**Comment by fryfrog** [comment]
Wait, so you release v0.5.0... and then keep changing *that* specific releases `.tar.gz`? Without changing the version?

**Comment by barbequesauce** [comment]
Negative - with each merge to master we create a new release... that happens every 2-3 weeks...

**Comment by evilhero** [comment]
We don't touch the tgz in any way after we generate the tag.

We did however have to do some ref changes within master I believe last week due to some merging problems.  

It might be that its pulling from a different HEAD than what was done when the tgz was created (I dunno how that all works, but I believe that's possibly what happened to make a diff to the md5).

We also, as a side note, removed some dependences from requirements.txt which, looking at your AUR packaging seems to have not been updated (not sure if that impacts anything, but just thought I'd mention it).

**Comment by fryfrog** [comment]
I'll get the deps matched up, thanks for pointing them out.

Next time it happens, I'll save both files and compare them. Will close for now and 🤞 it just never happens again. Thanks for confirming you're at least not sneaking updates/changes into them.
