### ISSUE TITLE
Convert to CBZ

### ISSUE THREAD

**Issue by mccorkled** [mylar3/mylar3#724]
**Describe the request**
Convert CBR to CBZ during post-processing.

**Environment (please complete the following information):**
 - OS: Docker
 - Version: v0.5.0 
 
**Additional information**
I saw a previous request to convert to CBZ ONLY, but it would be nice to have the option to do this and then meta tag the files.

**Comment by evilhero** [comment]
I don't understand what it is that you're asking for or inquiring about. 

Mylar will convert and metatag cbr and cbz during post-processing and you'll end up with a cbz as a final product.

The convert option only converts cbr to cbz but doesn't perform metatagging.

**Comment by mccorkled** [comment]
When I check the ONLY convert to CBZ, the files do not get meta tagged. I am asking to convert to CBZ and also meta tag.

**Comment by evilhero** [comment]
That's what the ONLY term would imply ;)

Enabling metatagging will convert cbr/cbz to cbz and metatag during the post-processing process. It's the default action, unless you enable the ONLY convert option.

**Comment by mccorkled** [comment]
Something is broken then because I just manually imported a folder full of comics and a bunch of them are CBR.

**Comment by evilhero** [comment]
Nothing is broken. 

Importing is not the same as post-processing. If you're importing a directory of files that do not belong in your watchlist, post-processing doesn't occur.

Post-Processing only occurs when an item is snatched and downloaded via Mylar, or you run a manual post-processing on a selected folder.

**Comment by mccorkled** [comment]
I meant manual post processing.

**Comment by mccorkled** [comment]
This is off topic, but I did notice today while messing around with this a bit, if I delete come comics, and rescan the files in Mylar, it sets the books as Archived. I then select them all and change them back to Wanted. When I go back to the home page, Mylar is still showing that I have x amount of book that I just deleted. So when it's searching those get skipped, and if I manual post process, they don't get processed because it says they already exist.

**Comment by evilhero** [comment]
If metatagging isn't working or its not converting then you'll have error messages in the logs indicating what the problem is. 

It could be anything from permissions, to not having unrar installed or in an accessible path for Mylar to use it.

**Comment by evilhero** [comment]
It is off topic and this is going way right of what we're taking about in this issue. If you'd like to discuss it more, please create a new issue and follow the existing issue template too. 

Setting items to Archived if they're not in the location any longer is a normal and expected behaviour. 

If you're doing file removals, adds etc - you probably should be doing a Recheck Files once you're finished so that the tallies line up. We don't initiate a Recheck after those types of actions as if you have a large series, it can take abut for the GUI to come back. 

As far as searching and getting skipped, that's not exactly how Mylar works. It checks the status of each issue prior to searching so if you marked them as Wanted then they would get searched. Manual post-processing only worries if a file exists if you have the duplication option enabled and it bases it off of that - otherwise it hammers any existing file.
