### ISSUE TITLE
Cable 10 2020 not showing up 

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#743]
![B9985CCB-D159-4844-9337-1D5B93D48C9E](https://user-images.githubusercontent.com/97095/116578571-67005c80-a8c6-11eb-834c-bfd7659a6e07.jpeg)
**Describe the bug**
Cable 10 has been out for a little bit but it’s not in Mylar.

**CarePackage**
[carepackage 6.zip](https://github.com/mylar3/mylar3/files/6399866/carepackage.6.zip)

**Environment (please complete the following information):**
 - OS: Win 10 Pro updated
 - Branch / commit: 6f89e83ba15b3ff80031c810c556dc6b4c7cb8dc (master)

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Issue 10 isn't on ComicVine yet, so Mylar doesn't know it exists. 

If it came out yesterday, don't expect CV to update their end until closer to Sunday the way things have been lately due to it being from Marvel. Once it's updated in CV, Mylar will update the info in your client and it will appear.

**Comment by DrSeussFreak** [comment]
Mylar pulls from comicvine, and if you check the series info on comicvine, you will see issue 10 is not there

https://comicvine.gamespot.com/cable/4050-125678/

**Comment by AtariBaby** [comment]
Ah right, forgot about that. Thanks fellas
