### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by jun6lee** [mylar3/mylar3#753]
So, I've had a bit of trouble with my qnap. 

Nothing to do with Mylar, but the result has meant I've lost the db history of all that I've added since December of last year.
That is, I have he files & they are in the designated comics folder, but Mylar doesn't know that.

Is t here a way I can have it scan the comic folder and re-add/add all the stuff that's there back into the db so that the gui is up to date with what I have and not?... or will I have to lose the lot & start over to do that?

**Comment by DrSeussFreak** [comment]
Click manage, enter your comics path and click "Save Changes and Scan".  Make sure you have "Auto-add new series" checked at a minimum.
 
![Screen Shot 2021-05-06 at 1 15 46 PM](https://user-images.githubusercontent.com/175500/117346377-49566880-ae6d-11eb-83b8-487cbaaee455.png)

**Comment by evilhero** [comment]
If you're just reimporting an existing collection, what @DrSeussFreak said is correct. However, if you don't want to move the files, you should uncheck the move option and then enable the option that appears in regards to directory location (can't recall atm what the exact naming is). Enabling that option will not move the files, but have mylar then monitor that location   as the series directories instead of basing it off your Comic Location folder.
