### ISSUE TITLE
Problem with series with same name and year

### ISSUE THREAD

**Issue by grumpington** [mylar3/mylar3#760]
I have a problem with the series silk (2015) as it has two series with the same name and year. When adding both of them they both end up in the same directory, and og I Try to import Ine it overwrites/skips issues as it can't differentiate between the series.

Would it be possible to add comicID to the folder structure?

**Comment by evilhero** [comment]
Try using the ```Vn``` (volume number) tag for Folder Format. The problem is that your directory assignments aren't unique enough so in some cases they can create the same folder for different series. Using ```Vy``` would not get around the problem, but ```Vn``` is unique due to voluming numeric. You just have to make sure thay both volumes have a volume number provided (or at least one that's not blank, None or a v1 as they're all the same value). 

The Comicid option is possible, but probably not right at this exact moment.

You can also just type in the full path to the Silk series you want changed in the directory field within the series making sure its slightly different than the other one (by adding the actual comicid at the end as an example)  and then clicking update so it can save and create the folder.

**Comment by grumpington** [comment]
Ising volumenumber seems to solve it for me
