### ISSUE TITLE
Files not being removed from cache

### ISSUE THREAD

**Issue by paulr24** [mylar3/mylar3#765]
**Describe the bug**
Cache filled with almost 10 TB. It seems that most of the cached files did make it to storage, but also stayed in cache indefinitely.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/6524583/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Synology NAS DSM (latest stable)
 - Branch / commit: mylar3/mylar3 v0.5.3

**Comment by burnshroom** [comment]
There is an "undocumented" feature in the config.ini called "cleanup_cache" (without the quotes).  If you stop mylar and change this to True it will clean the cache directory on each start.

**Comment by evilhero** [comment]
You seem to have a permissions problem - anytime post-processing occurs (whether manually or automated), it throws an error like the following:
```
[MOVE] error : [Errno 1] Operation not permitted: '/comics/Image/Monstress (2015)/Monstress 32 (2021).cbz
```
These errors are scattered all throughout your logs so that it never completes post-processing and leaves the files in the cache folder (so that they can be manually moved out as a secondary precaution).

Odds are the problem is due to you trying to enforce permissions, which with Synology because of the way permissions work on their systems, always seems to fail unless you do some really arcane, specific stuff (don't ask me what it is I haven't a clue). As such you need to let your OS handle the enforcement since it's most likey either ACL based on parent-child based. 

So the answer? Turn off the ```Enforce Permissions``` option within Mylar, save the config and you should be able to post-processes the any items fine thereafter (you can verify it in the logs - it will say post-processing successful).

Also what @burnshroom says - use the ```cleanup_cache``` option. It clears out any abandoned/failed/error'd post-processing files (amongst other things that aren't needed in the cache folder) whenever Mylar re/starts.

**Comment by paulr24** [comment]
Thanks @evilhero and @burnshroom, that did the trick!

**Comment by TwistedG** [comment]
I'm actually running into the same issue but on Unraid, I can't change the config.ini it says I don't have the right permissions for it

**Comment by evilhero** [comment]
@TwistedG, it's your setup - if it can't write to the config it can't save the settings from the GUI.

Make sure the user running Mylar is the user with permissions to the Mylar directory - odds are you're running Mylar as a user without enough privileges.
