### ISSUE TITLE
Error During Manual Metatagging

### ISSUE THREAD

**Issue by mccorkled** [mylar3/mylar3#768]
Mylar would not manually post process a comic. I renamed the file to the correct name and placed it into the finished comic directory. I then went into the comic within Mylar to manually metatag it. This is when the error occurred.

[carepackage.zip](https://github.com/mylar3/mylar3/files/6553733/carepackage.zip)

Docker
Version: v0.5.3 (master) 

This was working previously on version 0.5.0. No settings have changed.

**Comment by evilhero** [comment]
It's definitely still a permissions issue - you need to ensure that permissions on your /Comics directory mount has the proper full permissions for the user running Mylar, so that Mylar can overwrite/hammer/delete/write to any directory therein. In your case, Mylar is trying to copy the file back onto itself (same name but with new metatagging) and it is encountering the error at the OS level due to not having sufficient privileges to .

If you created directories recently (ie. added new series) and the metatagging error is occurring with those particular series, then there's a chance that your default permissions are being inherited from the parent folder and they're too restrictive. 

Nothing has been altered in regards to metatagging within the last few months as far as it being related to any recent code changes that might affect things.

As an added test - I just loaded up a standard LSIO docker - and encountered no errors when performing a manual metatagging.

**Comment by mccorkled** [comment]
I didn't add any new series. My user "automation" has read/write privileges for the entire comic directory. I am not sure what to make of this since all of my other containers run fine with the same permissions. 

![1](https://user-images.githubusercontent.com/13697804/119866972-6077fb80-beeb-11eb-9c04-a1142a3dfd5b.png)
![2](https://user-images.githubusercontent.com/13697804/119866983-640b8280-beeb-11eb-9f35-7f0f8c1ff3f4.png)

**Comment by evilhero** [comment]
Check the directories themselves to see that the permissions are correct on the directories/files. 

I don't know what container that's for or what all that pretty GUI stuff is telling me - but what I do know is that it's encountering some kind of permissions issue when it goes to copy the file from the cache folder to your /Comics folder (and it goes to overwrite the existing file). 

There's only so much we can do on this end as far as troubleshooting your particular system unfortunately - but like I said above, tested on a bare bones LSIO docker and it worked fine. At this piont it's pointing to something specific with your particular setup, albeit what it is exactly is up in the air atm.

**Comment by mccorkled** [comment]
The sub folders have the same permissions as the main /Comics directory. The GUI is showing you all of the paths I have mapped as well as their privileges for the user "automation". I am running the LSIO build.

**Comment by evilhero** [comment]
Check the individual files within one of the directories that's causing the problem - make sure that the user ```automation``` is included in the correct group required for access to said files (assuming it's not ```automation:automation```).

**Comment by mccorkled** [comment]
User automation has RW permissions.

**Comment by mccorkled** [comment]
Talked with the LSIO guys and got the problem solved. Because I was having to manually move comics that were not being picked up for whatever reason during post processing, they were being moved as user admin rather than user automation. This was easier to view via SSH.
