### ISSUE TITLE
Comic exists in library but not in StoryArc

### ISSUE THREAD

**Issue by war3zlod3r** [mylar3/mylar3#770]
I have several story's where one series of issues isn't picked up by the storyarc for whatever reason, examples include: Infinite Crisis not tracking already downloaded issues of Adventures of Superman, Spider-Women tracking issue #8 of Silk V2 but not #7. I've tried refreshing or deleting an readding them but get the same behavior.

**Comment by evilhero** [comment]
Please follow the issue template.

Have you tried doing a ```Search for Watchlist matches/Recheck Files``` or a ```Refresh StoryArc``` from the specific storyarc page? 

If the above doesn't work, we need debug logs in the carepackage to see what's happening (and make sure to include the dB since that holds the storyarc data).

**Comment by war3zlod3r** [comment]
I have and this solved the problem for most of the issues but still exists for Silk V2 and Teen Titans Annual V2 (2006)


[mylar.log](https://github.com/mylar3/mylar3/files/6592781/mylar.log)
[specific_25412.log](https://github.com/mylar3/mylar3/files/6592782/specific_25412.log)
[https://drive.google.com/file/d/18TuLuVEoMWdv5SzLRJ2xXx5fVpC4euJA/view?usp=sharing](url) <-CarePackage

**Comment by evilhero** [comment]
Silk is due to it being rebooted in the same year basically (v2 started and ended in 2015, v3 started in 2015) - so Mylar's confused as to which one it belongs to and pumps it into the v2 one since that's the first match. I have this fixed and working on my local system, so that one should be in the python3-dev branch soon.

Teen Titans looks like it's due to how CV has f'd up their description naming, again. So with CV, there is no specific indicator in the API to denote a volume - it's either in the description field, or in the deck field (kinda like the header). Unfortunately there is no rhyme or reason behind using one or the other with CV, and as such we have to test for both and then go from there. In this particular case with the annual, in the deck they have ```Teen Titans Annual (Volume 2)```, but in the description they have ```Teen Titans Annual (Volume 3)```. Because Mylar by default tests the deck value first and if it's not found, then go to the description field - it never hits the Volume 3 line and assumes Volume 2 (which is incorrect since it belongs to the V3 series).

So umm...I think if you blow away the volume in the annual in your watchlist (since you don't have annual integration enabled), and then delete the storyac & re-add it, it should match up. Keep in mind that the Volume in the story arcs will say the incorrect version though (since those values get parsed directly from CV and it's the wrong volume being picked up). It's still monitoring the correct series however (you should be able to click on the series name for an issue while in the Story Arc page and it will bring you to the relevant series page on your watchlist).

**Comment by war3zlod3r** [comment]
I do have annual integration enabled

![image](https://user-images.githubusercontent.com/33874111/120698570-d85a9e80-c474-11eb-9f14-c644ea2ee84a.png)

maybe it could be due to the fact that there are two annuals for that volume of Teen Titans both listed as issue #1

**Comment by evilhero** [comment]
Haven't forgotten about this - been trying to work thru it based on CV having the entirely wrong volume declared, which makes it difficult to figure things out if you're automatically assuming it's wrong.

**Comment by war3zlod3r** [comment]
No worries man, good things take time

**Comment by evilhero** [comment]
PR #792 should fix this problem now that I've had some time to test things out abit more.

**Note** that when viewing the detail page for a given arc, the annual will not be shown as having a direct link to the correlated series (with annual integration enabled) - however the status will be linked & shown correctly. It's all linked up _under the hood_, but the display on that particular page is giving me some problems in getting it to show that it's linked up to the parent series properly.

**Comment by evilhero** [comment]
Assuming this is fixed - as I remember testing this and was working. Plus this is now almost a year old, stale, and the carepackage would have incorrect references anyways due to code change.

If it's still an issue, please open a new issue with a fresh carepackage and relevant information.
