### ISSUE TITLE
Future State comics not importing/post-processing

### ISSUE THREAD

**Issue by SenorSmartyPants** [mylar3/mylar3#804]
**Describe the bug**
Comics were snatched but are not importing.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/6750332/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Hotio mylar3:nightly
 - Branch / commit: 00210b6156e4deb8e76b3600b7dd844d155bae73

**Additional information**
I tried adding "Future State - The Next Batman" as Alternate File-Naming, but this did not help.

**Comment by evilhero** [comment]
#805 should fix this problem - hopefully for good as this type of post-processing issue has been somewhat frequent the last few weeks due to some additional checks that were put in place in order to ensure that series were being matched correctly to the new issues on the pull-list.

_note: tested against indicated series and didn't encounter the problems mentioned in the issue with the fix applied._

**Comment by SenorSmartyPants** [comment]
This fix worked for me. 
Thanks
