### ISSUE TITLE
DC 2021 Annuals not matching on search

### ISSUE THREAD

**Issue by SenorSmartyPants** [mylar3/mylar3#812]
**Describe the bug**
Mylar doesn't match the DC 2021 annuals to the series when searching

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/6817859/carepackage.zip)

**Environment (please complete the following information):**
 - OS: [ARM64 Docker]
 - Branch / commit: [d6ab2884ce4eabca9d952c32379ea4594e7b3e77]

**Comment by evilhero** [comment]
Can you verify that the annuals are actually listed on the given series page under the annuals section? 

I believe what's happening with the DC titles is that they've changed the name from ```series Annual``` to ```series Annual 2021``` which is throwing off the parsers for both the backend and in the clients.  

Doesn't help that CV is having problems at the moment either I'd imagine. What worked for me just now - is if you do a Refresh Series for that particular series the annual should show up. I believe the pull-list would show it then as Wanted, but it would link to the annual comicid, and not the series id that it's linked to. Doing a Recreate Pull-list would match them back up (I'm pretty sure).

I'm working on doing a fix to help, but due to CV being down the db updater can't update the titles in the background when they've been updated so the series won't see that they exist (what you're doing when you do the Refresh Series).

**Comment by SenorSmartyPants** [comment]
Annuals are listed on the series page. 
Annuals are marked as wanted and show up on the wanted page.

**Comment by evilhero** [comment]
Can you try recreating for the given week you're trying to post-process from (I'm assuming it's week 26, but it could be anything really) ? Recreating the pull will only recreate the week being currently viewed, unless you're recreating the current week in which case it recreates the pull for the current week in addition to the previous week only).

I just updated the backend to make sure they pointed to the correct titles (if it lists the annual as ```Series Annual 2021``` instead of ```Series 2021 Annual``` then it's not linking up correctly) - the annuals should appear as ```Series 2021 Annual``` and clicking on the title in the pull should flip you back to the respective series it's linked to. If it flips back to the index page instead of the series detail page, that's another way to tell if that it's incorrectly linked.

**Comment by SenorSmartyPants** [comment]
It's not post-processing that is the problem, doesn't even get that far. It's not snatching. Example of that was in my first carepackage.

Week 28
Recreated pull list. No change that I noticed.
![image](https://user-images.githubusercontent.com/991618/125881843-90b08eda-e3a2-42f5-b0d8-3a58d7662953.png)
Clicking series name doesn't do anything on pull list.

Wanted page
![image](https://user-images.githubusercontent.com/991618/125881681-2685bf4e-af2b-44e5-9a8e-994d27718adf.png)

Clicking on series from Wanted page goes to correct parent series `Action Comics` for example.
![image](https://user-images.githubusercontent.com/991618/125881778-5ecbec27-f4c0-4a45-b27b-9c3110e3ed97.png)

**Comment by evilhero** [comment]
Yeah the annuals not linking up on the weeklypull is/was an issue. This should be resolved now on the latest python3-dev commit.

It's been a bit of a war today with the whole process - between CV causing the updater to fail since yesterday (it would return an error and say that CV is down), WS failing to recognise the new annuals format and linking everything to the incorrect volumes, and then the clients not being able to read either...it's been just dandy lol.

In addition to some of the updates earlier tonight, PR #818 should be the last remnant of the PR's that should address all these outstanding issues related to annuals. The pull should show the correct title and link up accordingly at this point due to the WS update, however the PR mentioned above will fix the problem with the Flash not linking up. The PR will also correct the title on the Wanted table. 

Once the PR is merged, holler back and let me know if things are fixed.

**Comment by SenorSmartyPants** [comment]
Wanted page looks good. Clicks thru to correct series. Annuals are not listed in Upcoming.

![image](https://user-images.githubusercontent.com/991618/125980268-531fc42c-3d38-4d33-bcc7-a36b7546eb02.png)

But manual searching for missing Flash annual still returns no matches. Jackett returns a result, but then this shows up in the logs
`The Flash 2021 Annual 001 (2021) (Digital) (Zone-Empire).cbr was not a match to The Flash Annual (2016)`

[carepackage.zip](https://github.com/mylar3/mylar3/files/6832136/carepackage.zip)

**Comment by evilhero** [comment]
#819 should fix all the problems with searches, post-processing, and file-checks in regards to the bastardised annualised naming. 

It will also auto-search for ```series Annual``` in addition to ```series 2021 Annual``` since I've seen some files that aren't named as per CV naming.

**Comment by SenorSmartyPants** [comment]
Snatched and post-processed.

Thanks!
