### ISSUE TITLE
Still having trouble post processing.

### ISSUE THREAD

**Issue by mccorkled** [mylar3/mylar3#820]
I am still having trouble with manual post processing a ton of comics. Mylar starts with looking for Daredevil every time, and then when it finishes it states that manual post processing was completed for two comics. 

Version: v0.5.4 ( master) 
Docker

[carepackage.zip](https://github.com/mylar3/mylar3/files/6833468/carepackage.zip)

**Comment by evilhero** [comment]
Your dates are all wrong for the files that you're trying to manually post-process.

In the logs you can see several lines that are like this:
```[POST-PROCESSING][ISSUE-VERIFY] 1987-10-27 is before the issue year of 1988 that was discovered in the filename```.

When you reference that issue on comicvine the store date is 1987-10-27, and the cover date is January 1988 - so why is it that your filenames have the date as 1988 when it was released 2+ months earlier ?

You need to clean up the dates on your files if you want them to be post-processed or found by Mylar - if I recall this was something you brought up a few times before in other issues, and I mentioned the same thing.

You're going to have to go thru the logs to see which ones it's failing on - and then fix the dates. Every single one of the ones it doesn't post-process is due to the date in your filename being the incorrect value. I know I also mentioned that I might possibly fix the adjustment, but I'm still not 100% sure going several months outside of the existing 2 month window is the best course of option.

**Comment by mccorkled** [comment]
When these were not post processing, I manually went through to check the dates and they are right. One example from my log..

`[POST-PROCESSING][ISSUE-VERIFY] 1946-10-30 is before the issue year of 1947 that was discovered in the filename`

When I go into that comic within Mylar, I can see that the date for issue #60 is 1947. 

The next line in the log is...

`[POST-PROCESSING][NON-MATCH: Captain America Comics-1628] Incorrect series - not populating..continuing post-processing`

What would be the reason Mylar is looking under the wrong comic? There's only one "Captain America Comics" on my watch list.

**Comment by evilhero** [comment]
Those are the wrong dates. Mylar uses the store date over the cover date, unless there is no store date available. The ``1946-10-30`` is the store date, ``1947`` is the cover date. Your comics are all using the cover date which was normal for comics back then (ie. before the digital era), but the date in the filename is not when the comic was actually published / available.

**Comment by mccorkled** [comment]
Perhaps then it would be beneficial to show that date (or have the option to) when under the comic. I have been using the date that Mylar displays when I go into the comic's directory, and since that's not the date being used, it seems useless to display that information.

**Comment by evilhero** [comment]
What is the filename for the "Boink" one ? 

As far as pubdate aspect - unfortunately the entire comics industry uses the publication date with more regularity than the store date when talking about a specific issue. Mylar has to use the store date for verification / matching / etc due to how specific it is, and the fact that it's almost literally 2-3 months prior than the cover date. So when it does comparisons it uses the more accurate date if it's available. Perhaps in the future we'll try to allow for some customisation by the user as far as what is displayed.

Fun fact: the cover date was created by publishers for comic book shops / retailers - the cover date shown on the 'cover' of the comic tells retailers when they have to pull the unsold comics from the shelves and ship them back to the publisher in order to get reimbursed. There's really no other use for it other than the fact that it's literally on the front of the comic, but the actual store date is on average 2-3 months prior than the date listed on the cover (at least it used to be for the larger publishers)

**Comment by mccorkled** [comment]
The filename is `Scientific Progress Goes Boink` since Windows does not allow certain characters.
