### ISSUE TITLE
Add volume number to Folder Format

### ISSUE THREAD

**Issue by Frankthetankk** [mylar3/mylar3#845]
**Describe the request**
Add an option to add volume number to the Folder Format. Similar to the volume number $VolumeN in the File Format.

**How did you come up with the idea?**
I've noticed that if there is different comic book series with the same name and year that mylar will only use one directory for each series. For example, there is two different Red Sonja 2016 series. When I use my Folder Format, $Publisher - $Series ($Year) [$Type], while adding these two series mylar creates only one folder. I then manually update each directory to include the volume number as shown below. I then have to check each issue to make sure each issue was in its correct directory.
Dynamite Entertainment - Red Sonja v3 (2016)
Dynamite Entertainment - Red Sonja v4 (2016)

**Environment (please complete the following information):**
 - OS: Windows10
 - Branch / commit: [85341995d0ac18bb719f76304e55bcd48b53c455]

**Additional information**
The following might be a separate issue in itself. I feel that Volume 1 format labels, v1, shouldn't be left out. Make sure mylar3 includes volume 1 (v1) while processing the above Folder Format request. I say this because, I've notice that the "Rename Files" option under comic book series that are a volume 1 won't rename with a v1 using $VolumeN, because under the "Edit Settings" for said series the "Volume Number" is labeled as "None". This is only for comic book series that are labeled as volume 1. Volume 2 and up are already labeled accordingly. I manually have to add a "v1" to each volume 1 that is known and rename those files so the directory and each issue has a "v1" within the name. For example. Dynamite Entertainment - Red Sonja v1 (2005)

**Comment by evilhero** [comment]
There already is a ``$VolumeN`` available for Folder Format (hold your mouse over the ``i`` icon beside the folder format and you'll see.

If you can want v1 to be labelled instead of it being blank, in the config.ini set the ``setdefaultvolume`` field to a value of ``True`` (the default is ``False`` which means it won't create a volume label of v1 during file/folder creation).

**Comment by Frankthetankk** [comment]
> There already is a `$VolumeN` available for Folder Format (hold your mouse over the `i` icon beside the folder format and you'll see.
Yes, you're correct. I see it and it indeed works when I tested it. When I use $VolumeN in the Folder Format it will always display uppercased. I want it to be lowercased. In File Format, the $VolumeN will display as lowercase. I would like to have an option to be able to choose from upper or lower case volume lettering. 

Also, I noticed a minor GUI display error when testing this. In the series "Directory" line, it will show a uppercased volume letter "V" when I added a new series that already exists in my and is already formatted as "Folder Format", but with a lowercased volume letter "v". For example, I already have a folder called, Dynamite Entertainment - Red Sonja v3 (2016) and in mylar3 when I search and add the series, under "Directory" it will show as Dynamite Entertainment - Red Sonja V3 (2016) when in fact that isnt true.

> If you want v1 to be labelled instead of it being blank, in the config.ini set the `setdefaultvolume` field to a value of `True` (the default is `False` which means it won't create a volume label of v1 during file/folder creation).
This sounds like just want I want. I would like to know. Will this create a v1 label for only series that are labeled in Comicvine
as volume 1 or will it create a v1 label for all series? I want to create a v1 label only if a volume 2 or more exists.

**Comment by barbequesauce** [comment]
@Frankthetankk is this still an open question?

**Comment by Frankthetankk** [comment]
Yes. Haven't tested it myself since initially writing it to see if it's still the same.

**Comment by evilhero** [comment]
lower-cased would be an enhancement request that may not happen based on your requirements.

As far as adding a series with different capitalisation of the ``V`` - it doesn't detect what your series are called. You tell it what they are. 

If when adding a series, the series does not exist (ie. capital-case) it will create it - since Windows doesn't care about case when it comes to matching it will display the same (ie. it will match to the lower case v, even tho it's upper-case).  There's pretty much no way for Mylar to determine this on windows-based systems without a huge overhaul of the detection process, which is one of the reasons why lower-casing the volume aspect might not happen.

If you want Mylar to recognise the lower-case v, you have to change the directory path so that it will be a lower-case v.
