### ISSUE TITLE
[Feature Request] Add basic bulk actions to ddl queue management page

### ISSUE THREAD

**Issue by max6166** [mylar3/mylar3#856]
Currently, users can only perform actions (retry, remove, etc.) upon an individual item.

This method quickly becomes tedious if a user needs to perform the same action upon 20 or more items.

The "checkbox with dropdown" system you use on the Import Management page and others seems like it would be very helpful here. The user could select the items then select an action from the dropdown list.

**Comment by evilhero** [comment]
There are upcoming changes to the series detail page that will improve things drastically - and after it's implemented, will be reiterated thru other pages that need updating - the DDL Queue Management page obviously being one of those pages. 

This will probably occur over the next few weeks (in order to try to not make massive sweeping changes and possible breakage) as the initial series detail change I have slated to go into python3-dev at some point this week.
