### ISSUE TITLE
Strange Issue

### ISSUE THREAD

**Issue by mccorkled** [mylar3/mylar3#858]
This isn't really a bug, but it's also not really a feature request. This may be only relevant to this single series, but [Human Torch (1940)](https://comicvine.gamespot.com/the-human-torch/4050-832/) has two #5 issues. Obviously Windows doesn't allow them to have the same file names so I'm not sure how this should be handled.

Docker
Version: v0.5.6 ( master) 

Thank you!

**Comment by kingfenix** [comment]
your file naming scheme just isnt specific enough....here is mine which handles it fine.

$Series $Annual - $Issue ($monthname $Year)

**Comment by mccorkled** [comment]
I see! Do you have this set for the series alone or all of them?

**Comment by evilhero** [comment]
Don't use Alternate File Naming with format conventions. Alternate File Naming will rename the series aspect of the filename to whatever you enter in that box.

You need to set it at the global level under Configuration or you have to manually rename those 2 series so that they include the month and year as @kingfenix mentioned.
