### ISSUE TITLE
Can't remove failed torznab downloads

### ISSUE THREAD

**Issue by garrettjones331** [mylar3/mylar3#869]
I was in the process of trying to debug why I wasn't able to get my deluge integration to work, and came across an issue in which I'm unable to clear failed torznab downloads.  

<html><body>

2021-08-28 20:37:10 | INFO | [FAILED-DOWNLOAD] Successfully marked as Failed.
-- | -- | --
2021-08-28 20:37:10 | INFO | [FAILED-DOWNLOAD] Marking as a Failed Download.
2021-08-28 20:37:10 | ERROR | Unable to send torrent to client. Assuming incomplete link - sending to Failed Handler and continuing search.
2021-08-28 20:37:10 | INFO | Torrent not added yet, trying to add it now!
2021-08-28 20:37:10 | INFO | Checking if Torrent Exists!
2021-08-28 20:37:10 | INFO | filepath to torrent file set to : /config/cache/Sabans_Go_Go_Power_Rangers_1_2017.torrent
2021-08-28 20:37:10 | INFO | Connected to Deluge! Will try to add torrent now!
2021-08-28 20:37:10 | INFO | matched on Saban's Go Go Power Rangers

</body>
</html>

This portion of my log shows the torrent being marked as failed (Which I may open another topic for, since it's a different issue).  But when I wanted to remove the failed download to debug a few things to see what was causing it to fail, it doesn't see the torrent anymore because it's marked as failed.  

I attempted to go to the manage failed links page to remove the them so they wouldn't be ignored, however when I select them and choose "clear failed locks" from the dropdown, they just deselect and remain there.  Originally when I did it there were some nzb files in there that were removed, so I know the selection button works.

![Capture](https://user-images.githubusercontent.com/1960790/131234540-9f1ddf4a-2976-4580-a69a-6c51c6ac14c3.PNG)

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/7071711/carepackage.zip)

**Environment:**
 - OS: Unraid 6.9.2
 - Branch / commit: v0.5.7

**Comment by evilhero** [comment]
PR(#870) will fix the problem with the failed downloads not being deleted. It looks like the reason why it wasn't able to delete them is because all of those items currently in your Failed list don't have a unique ID (they're all just ``` ```), which would mean that when they get flagged as being failed, they're not being written out correctly to the db.

All of your logs in your carepackage are in INFO level, but since you're primarly using torznab (and I don't) and if you're able and willing to of course - if you could change your logging to DEBUG level ( config.ini = ```logging_level = 2``` ).
Then the next time you get a few items that go into a Failed status, passing the logs again would help me narrow down the blank ID problem - as the IDs are used throughout the program in various places, so you might get further errors related to the blank IDs if it goes unaddressed.

**Comment by garrettjones331** [comment]
#870 fixed the issue.  Here's the relevant section with updated DEBUG level logs

29-Aug-2021 09:26:48 - DEBUG   :: mylar.searcher.4006 : SEARCH-QUEUE : Torrent Provider: torznab
29-Aug-2021 09:26:48 - INFO    :: mylar.torsend2client.971 : SEARCH-QUEUE : matched on Saban's Go Go Power Rangers
29-Aug-2021 09:26:48 - DEBUG   :: mylar.torsend2client.980 : SEARCH-QUEUE : filename for torrent set to : /config/cache/Sabans_Go_Go_Power_Rangers_1_2017.torrent
29-Aug-2021 09:26:48 - DEBUG   :: mylar.torsend2client.1202 : SEARCH-QUEUE : [torznab] Saved torrent file to : /config/cache/Sabans_Go_Go_Power_Rangers_1_2017.torrent
29-Aug-2021 09:26:48 - INFO    :: mylar.torsend2client.1259 : SEARCH-QUEUE : Connected to Deluge! Will try to add torrent now!
29-Aug-2021 09:26:48 - INFO    :: mylar.load_torrent.114 : SEARCH-QUEUE : filepath to torrent file set to : /config/cache/Sabans_Go_Go_Power_Rangers_1_2017.torrent
29-Aug-2021 09:26:48 - INFO    :: mylar.load_torrent.118 : SEARCH-QUEUE : Checking if Torrent Exists!
29-Aug-2021 09:26:48 - DEBUG   :: mylar.get_the_hash.208 : SEARCH-QUEUE : Hash: 0609AC1CE72199A958948F2A54FB045C2610CE45
29-Aug-2021 09:26:48 - DEBUG   :: mylar.load_torrent.124 : SEARCH-QUEUE : Torrent Hash (load_torrent): "0609ac1ce72199a958948f2a54fb045c2610ce45"
29-Aug-2021 09:26:48 - DEBUG   :: mylar.load_torrent.125 : SEARCH-QUEUE : FileName (load_torrent): Sabans_Go_Go_Power_Rangers_1_2017.torrent
29-Aug-2021 09:26:48 - DEBUG   :: mylar.find_torrent.49 : SEARCH-QUEUE : Finding Torrent hash: 0609ac1ce72199a958948f2a54fb045c2610ce45
29-Aug-2021 09:26:48 - DEBUG   :: mylar.get_torrent.57 : SEARCH-QUEUE : Getting Torrent info from hash: 0609ac1ce72199a958948f2a54fb045c2610ce45
29-Aug-2021 09:26:48 - INFO    :: mylar.load_torrent.134 : SEARCH-QUEUE : Torrent not added yet, trying to add it now!
29-Aug-2021 09:26:48 - DEBUG   :: mylar.load_torrent.138 : SEARCH-QUEUE : Torrent not added
29-Aug-2021 09:26:48 - ERROR   :: mylar.searcher.4014 : SEARCH-QUEUE : Unable to send torrent to client. Assuming incomplete link - sending to Failed Handler and continuing search.
29-Aug-2021 09:26:48 - INFO    :: mylar.markFailed.294 : SEARCH-QUEUE : [FAILED-DOWNLOAD] Marking as a Failed Download.
29-Aug-2021 09:26:48 - DEBUG   :: mylar.markFailed.296 : SEARCH-QUEUE : [FAILED-DOWNLOAD]nzb_name: Sabans.Go.Go.Power.Rangers.1.by.Ryan.Parrott.[ENG./]
29-Aug-2021 09:26:48 - DEBUG   :: mylar.markFailed.297 : SEARCH-QUEUE : [FAILED-DOWNLOAD]issueid: 609378
29-Aug-2021 09:26:48 - DEBUG   :: mylar.markFailed.298 : SEARCH-QUEUE : [FAILED-DOWNLOAD]nzb_id: 
29-Aug-2021 09:26:48 - DEBUG   :: mylar.markFailed.299 : SEARCH-QUEUE : [FAILED-DOWNLOAD]prov: torznab
29-Aug-2021 09:26:48 - DEBUG   :: mylar.markFailed.301 : SEARCH-QUEUE : oneoffinfo: {'ComicName': "Saban's Go Go Power Rangers", 'modcomicname': "Saban's Go Go Power Rangers", 'IssueNumber': '1', 'comyear': '2017'}
29-Aug-2021 09:26:48 - INFO    :: mylar.markFailed.331 : SEARCH-QUEUE : [FAILED-DOWNLOAD] Successfully marked as Failed.

This also gives me a little more indication where the breakdown is occurring trying to add the .torrent file to deluge.  The connection passes the test built into the downloader page (which I'm assuming is verified by the "connected to deluge" line), but for some reason is unable to add the torrent.  Any ideas?

[carepackage(1).zip](https://github.com/mylar3/mylar3/files/7072620/carepackage.1.zip)

**Comment by evilhero** [comment]
Did you enter in the deluge daemon port into mylar as opposed to the web ui port ? 

(``note this was taken verbatim from a forum post I did - but it should still apply``)
The Deluge daemon uses an auth file located in the user's .config directory normally (ie. /home/user/.config/deluge/auth), and it parses this for authentication. But in order to parse the file, you need to ensure the deluge daemon is enabled and running - Mylar connects via the daemon, not via the web UI.

Go into Preferences / Daemon. Then enable the Daemon port and chose an appropriate port number and ensure that 'Allow Remote Connections' is enabled as well. Then Apply the settings. In Mylar, you enter in the url:port as the host entry (ie. thisis.deluge.com:22181 - don't precede it with a protocol either).

Once you run the daemon once, the auth file is generated and from there you can edit the file manually and change passwords, or view what the username/passwords are - I believe it defaults to the username/password of whoever is running the Deluge daemon. So then just plunk in the username/password into Mylar, and save the config.

**Comment by garrettjones331** [comment]
I believe I have all of those things already set up and configured correctly.  Here's some images just to verify.

Torrent client config in Mylar & successful connection message
![image](https://user-images.githubusercontent.com/1960790/131318816-ad827bd0-f4c5-41f2-9e1e-64a68d39ac31.png)

Daemon config in deluge
![image](https://user-images.githubusercontent.com/1960790/131318907-bea5dfff-154d-4252-aeda-ae9e48cdaa5e.png)

Contents of my Auth file
![image](https://user-images.githubusercontent.com/1960790/131319715-5abb5e34-2b98-47ef-a31c-4038f2e7715a.png)

I noticed that I had set up the mylar account as a regular user (5). I tried changing it to admin level (10) just to see if that fixed anything, but it didn't.

**Comment by garrettjones331** [comment]
For further testing, I also tried remote connecting from another instance of deluge to my main instance and adding a .torrent using the account in the auth file, and everything seems to be working as expected that way.  For some reason there's some issue with the way mylar is attempting to add the .torrent

**Comment by evilhero** [comment]
Yeah I'd leave the user level at (5) - no point giving it admin access unless it's required (which it's not for this).

The only other thing I can think of is if you have created a label ``mylar`` in Deluge for mylar usage. I can't remember if Deluge was the one that wouldn't work unless the label was created manually beforehand or not.

**Comment by garrettjones331** [comment]
The label was already set up so I could define a specific download directory.
