### ISSUE TITLE
*check_github* and *check_github_on_startup* settings do not disable all github checks at startup

### ISSUE THREAD

**Issue by fulzamoth** [mylar3/mylar3#900]
**Description**
Based on their names, the *check_github* and *check_github_on_startup* config settings should be disabling all GitHub checks at startup. I have set both options to false in my *config.ini*:
```
check_github = False
check_github_on_startup = False
```
The expected behaviour is Mylar starts without attempting to connect to GitHub, but *getVersion()* has multiple places where it can make connections to GitHub without checking those settings. That leads to Mylar failing to start if there's a problem with accessing the GitHub API even if it has been configured not to check.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.10 (raspi)
 - Branch / commit:  
    ```
    v0.5.9
    cc29fd0966d658c6901f44bc0b854679c30268a7
    master
    ```

**Additional information**
This report is not asking for help with Mylar failing to start. I see on other bug reports that the API issue is usually throttling for one reason or another, and waiting awhile before attempting to restart does fix that problem. The question is whether Mylar should be attempting to use the API at all if these settings are *False*.

**Comment by evilhero** [comment]
Yeah - ``check_github`` is what the scheduler uses to trigger the github checking, so setting that to False should disable the auto-checking portion (which it does). 

However the ``check_github_on_startup`` wasn't being checked for in subsequent tries thru the module (as you mentioned), so will need to clean that portion up.

Just testing the changes now, with both options disabled it uses the current hash of the local repo and does not hit the github api for anything else after that. It doesn't store the release name, which I might fix - but it works with or without (just looks prettier in the config). The only time it will check with both options disabled, is if you manually hit the ``Check Version`` option in the lower right hand portion of the screen (cause then it kinda has to).

Setting both options to False essentially disables being notified of any updates due to not being able to check, and it becomes a manual thing (which is fine, and I'm assuming that's what you're after).

If you're running afoul of the github API calls (for w/e reason - in conjunction with other apps or just Mylar due to troubleshooting), you can also use the ``git_token`` field in the config.ini to specify your github api token. You can  create / view tokens if you go into your github ``Settings`` / ``Developer settings`` / ``Personal Access Tokens``. By default, and without a token specified, you're limited to 60 github API calls / hr across all your apps that use the API. Adding in the token value, allows the hits to go up to 5000 API calls / hr.

Fix should be in ``python3-dev`` later today
