### ISSUE TITLE
Noticing some incorrect info on some comics

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#952]
**Describe the bug**
Hi, I am experiencing this on a handful of comics, but not sure how many total. In this instance, Issue 23 has been out for a few days now, but is not available in the list. Interestingly, it says “23” in the “last issue” column, but not in the actual list. Is this something wrong with my system? Or something else? 

I have added new comics and they seemingly 
![D9E14524-4096-41A1-9AE5-C41CA7CFB7D2](https://user-images.githubusercontent.com/97095/141506300-d3bd0482-bc24-4944-8997-0ef0589c6150.jpeg)
![E8F66EB5-8D2E-42A9-9A6A-0D7C25B67855](https://user-images.githubusercontent.com/97095/141506303-27feeec7-984f-4c22-9598-fafb53e17179.jpeg)
downloaded fine.

**CarePackage**
Will submit logs if desired.
If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 Windows10
 - Branch / commit: 70f12a31c7166a57d75b4132fc061a862e507273 (master)

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
This is not new - this is and will always be a CV-type of problem.

Issue #23 is not on CV yet - so it won't appear in the issue list until its on CV. It also won't be able to search / post-process issues that aren't on CV until such time as they are.

It knows #23 is out (via the pull info), so that's why it shows the latest issue as such, but it can't link it to anything until CV data is present.

**Comment by AtariBaby** [comment]
Right right sorry for the trouble! I’ll just assume it’s a CV thing from now on. Sorry to bother.
