### ISSUE TITLE
Download Speed Throttling For DDL

### ISSUE THREAD

**Issue by LeeThompson** [mylar3/mylar3#954]
It would be nice to be able to speed throttle DDL downloads.

**Comment by evilhero** [comment]
Probably not going to happen anytime soon - we purposely limit to one concurrent download and that's not going to change anytime soon, as there's no real need for throttling and would only be used by a very, very, very small portion of the userbase - 

I really can't see any tangible benefit to being able to throttle a single download of a lone comic (a pack maybe, but even then mylar will only download one comic via DDL at any given time).

**Comment by LeeThompson** [comment]
I'm part of that userbase then; when it's DDLing, I get 4-8% packet loss on the internet connection (which isn't slow but it's not the fastest either).   I'm not sure why I get that much packet loss but it's enough to be noticeable.

**Comment by evilhero** [comment]
It's due to GC, nothing to do with mylar itself. The site gets hammered constantly by users and things eventually timeout due to excessive usage on their side. Throttling the download won't do anything to avoid them from being bombarded with requests and timing out on their side. 

Currently the DDL uses the direct option on GC, which means it goes thru their servers, so the server can't handle all of the massive requests coming in (usually more prominent on Wednesday /Thursday from our experience). 

Eventually mylar will prioritize using the mega links over the direct option, so that would help in lowering the timeouts significantly, as well as lowering the direct usage of GC's direct option. This is an upcoming feature, as its not built in as of yet.

**Comment by evilhero** [comment]
Closing - throttling isn't going to fix GC - it's GC. Tell them young kids to download porn instead of comics.

**Comment by LeeThompson** [comment]
I had to disable DDL,   (I have no idea what GC is.)

**Comment by cloudycloud47** [comment]
Is there an automated way to push DDL from GC to Jdownloader and let Jdownloader handle choosing the CDN?

**Comment by evilhero** [comment]
@cloudycloud47 no there isn't. 

Issue is closed also.
