### ISSUE TITLE
Added Cates’ “Hulk” to watchlist from “this week,” got 2016 “Hulk”

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#955]
**Describe the bug**
I added Hulk from Weekly Pull List Nov 21-27 and it downloaded Hulk v4 2016. Then I went back to look at the pull list and it’s listed as v4 2016. Sorry if this again a CV issue, but thought I should mention it just in case.

CarePackage
Will submit logs if desired.
If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk.

Do not paste from the GUI log.
Do not just paste a traceback/error.

Environment (please complete the following information):
Windows10

Branch / commit: 70f12a3 (master)

**Comment by evilhero** [comment]
That's 2 weeks away - so yeah mylar won't know exactly what issue is what in regards to releases, especially since CV doesn't put out issue data until the Sunday following the Wednesday.

I'll fix the backend so it won't link up, but then you also won't see any hulk for that given week until CV posts its data about it (the backend will only link to series that exist if I flip it for that particular series)

**Comment by AtariBaby** [comment]
I see. Totally makes sense! By all means do it whatever way you think works best. I can always just wait to add things later when that happens
