### ISSUE TITLE
500 Error After Clicking On Wanted

### ISSUE THREAD

**Issue by LeeThompson** [mylar3/mylar3#959]
**Describe the bug**
When I click on "Wanted" I get a 500 error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar3/mylar/webserve.py", line 2707, in upcoming
    issues_tmp = sorted(issues, key=itemgetter('ReleaseDate'), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/7559815/carepackage.zip)
I had to remove mylar.log.old as it was 600MB

**Environment (please complete the following information):**
 - OS: Debian (Synology DSM 6.2) Docker
 - Branch / commit: 70f12a31c7166a57d75b4132fc061a862e507273
 - Docker Image: linuxserver/mylar3:latest
 - Docker Image ID:  sha256:8cf873ecef4961fe129ae016d0089d634f9ac127f22450baa0e07c5968227c82

**Additional information**
Nothing appears in the log file, even with debug.

**Comment by LeeThompson** [comment]
I restarted the container and "Wanted" (aka Upcoming) is working again but not sure how long, it had been running only 5 days previously.

**Comment by evilhero** [comment]
This is probably due to CV getting issue data really late and it being incomplete as far as to what's normally been there in the past. From what I've seen this far, users are adding new issues to CV but their almost skeleton-like, and missing information like Store Date which is what mylar uses mainly as it's far more accurate than cover date.

The error in your logs is saying that one of the new issues (most likely new) does not have a ReleaseDate (which is the Store Date), so it can't finish sorting the results.

I'll have to look into it abit more closely (I have a few updates to the Wanted page coming soon that may actually fix this on its own).

**Comment by barbequesauce** [comment]
@LeeThompson is this still an issue?

**Comment by evilhero** [comment]
Assuming fixed due to all the recent changes, and if not it's stale. 

If it's still a problem, please open a new issue with the relevant information.
