### ISSUE TITLE
Tracking down incidents of incomplete files

### ISSUE THREAD

**Issue by AtariBaby** [mylar3/mylar3#970]
**Describe the bug**
I'm still getting incomplete files with some regularity. Currently using experimental and nzbhydra and sabnzbd.

I decided to analyze and test an incomplete file. I checked the logs. The incomplete file was downloaded from experimental and was 21mb, instead of 28mb, in sabnzbd logs. But I tried downloading later with only experimental checked, and from the experimental place directly without mylar, and just using nzbhydra without experimental, and couldn't repeat the incident. Each time I got a proper-sized 28+mb file. The only indication I could find was sabnzbd reporting that download as 21mb, instead of the proper size, 28-30nzb. I'm pretty sure this is the experimental site, and it shows the proper filesize also. 
Original incident:
![03117B8F-5EAD-451A-B516-FDC3141CC3E7](https://user-images.githubusercontent.com/97095/144720836-bf104074-7ff7-4f21-ba2d-7946c226df6f.jpeg)
Example of correct size:
![09201FFB-B7A0-4D4B-8018-0E45749BE70E](https://user-images.githubusercontent.com/97095/144720864-639b396a-5d16-4141-ba11-7b17a46ef064.jpeg)
This is the experimental site (I think?)
![434E820A-F75D-4E04-B587-BA3EC657B88E](https://user-images.githubusercontent.com/97095/144720882-e4a158d9-ddb1-4105-bec5-8314e369957d.jpeg)

As mentioned, I was unable to manually repeat the incident. But there are quite a few of these downloaded incompletely every week.

**CarePackage**
I tried to make a shortened log of this one incident. 

[mylarx.log](https://github.com/mylar3/mylar3/files/7654433/mylarx.log)
 
Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Branch / commit: ad278049d9b63df7157687c3186d4bb5b8abe69b

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
There's not much we can do about this ( as I eluded too in another thread I believe). It could be any number of factors really:
- the nzb generated had incomplete sections attached and it was corrected on their side shortly thereafter
- the news articles might not fully propagated when you tried it the first time, as opposed to 7 days later when they would be there completely.

I have a feeling this is probably more about a timing type of issue than any actual problem with mylar, or hydra per-se. Now if you were to try it immediately after the first failure and got different results with different methods then it would point to something else - but 7 days later would mean any available testing options would be inconclusive due to the time passed.

**Comment by AtariBaby** [comment]
I have actually had a number of incomplete files, presumably from this, so maybe it’s ongoing with them. And I do have a very fast system overall. It’s a good source because they sometimes get things that aren’t on my other indexers for a while, but I agree I think it’s best to turn experimental off, and then I always know where to get these manually if I need to. incomplete file seem to have stopped since I did.

Thanks for looking into it.
