### ISSUE TITLE
[Bug] Adding Series refreshes search page - loses filter settings and page your on

### ISSUE THREAD

**Issue by taibhse-designs** [mylar3/mylar3#976]
**Describe the bug**
When searching comics to add to mylar, if multiple in a franchise need to be added, eg invincible iron man, tony stark iron man, international iron man, etc, doing a franchise search for iron man yields all the results wanted, however upon adding the first, the ui refreshes, so if your on the second page of search results it skips you back to page one, if you had applied any filters by publisher, it resets and clears them.

This makes it take longer to add series overall, 

**CarePackage**
no errors reported in logs, this seems to be by design but results in an unfriendly UX

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: [v0.6.1] on python 3.8.1

**Additional information**
adding a series should not cause a full page reset result in a user losing their place or set filters, maybe if those got tagged on and read back in some way from the url, this would help mitigate a user losing progress on adding series in.

**Comment by evilhero** [comment]
This is due to some of the GIU changes that were made in v0.6.0 - in which almost every page has to be updated to accomodate the new layout/structures.

I was already aware of this problem - the problem being currently that the search results are not stored and are loaded dynamically so once you navigate away from the page the query is lost and it has to be fully regenerated (in the current iteration). Having an issue logged for it, isn't a bad thing either.

There's going to be a few more page updates coming in the next release (searchresults, wanted page), I just don't have an exact time frame due to the holidays upcoming and such. I'm hoping to get it out sometime this week into the python3-dev branch for further testing before hitting the master branch.

**Comment by barbequesauce** [comment]
@taibhse-designs please confirm this is still an issue?

**Comment by evilhero** [comment]
Fixed, and tested in latest versions - as well as having the option to mark multiple series for adding via the checkboxes.

Gonna close this.
