### ISSUE TITLE
404 Error when manually intervening in import results

### ISSUE THREAD

**Issue by mjd515** [mylar3/mylar3#980]
i can not seem to be able to pick the correct comic when importing a comic with an & in the title, every time it results in this error page
![err](https://user-images.githubusercontent.com/57189495/146947562-ff65275e-2532-497e-8b43-5f2f9b80263f.jpg)

**Comment by evilhero** [comment]
Please follow the issue template. It's there for a reason. 

Posting a screenshot of just the error is as helpful as a saying there's a problem.

Carepackage or debug logs are needed before we can help.

**Comment by mjd515** [comment]
i am sorry i didnt see a template, i can try and gen a care package and attach it for you :)

**Comment by mjd515** [comment]
https://mega.nz/file/I94i3QpT#3oVRlzV_oWNnMR1oMXl8TZj-OO3HTD1UlSc3oPtU6mY

**Comment by barbequesauce** [comment]
@mjd515 please confirm if you're still seeing this?

**Comment by evilhero** [comment]
Pretty sure this is fixed as this was initially when we the comicdetails underwent all the changes and the addbyid was referencing some incorrect variables.

Assuming closed, since it's been 3+months - if it's still an issue, please open a new github issue with the relevant information to get eyes on it.
