### ISSUE TITLE
Comic marked as snatched but not downloaded to cache

### ISSUE THREAD

**Issue by CubeyGlyph** [mylar3/mylar3#988]
**Describe the bug**
Comic marked as snatched but not downloaded to cache so post processing can never occur and status stays snatched indefinitely.

**CarePackage**
[mylar.log](https://github.com/mylar3/mylar3/files/7794263/mylar.log)

**Environment (please complete the following information):**
 - OS: Linux (Docker)
 - Branch / commit: linuxserver/mylar3:nightly-version-a36c5bcf (master)
 
**Additional information**
No config changes, worked fine for months suddenly stopped.

**Comment by evilhero** [comment]
Firstly, - your version of Mylar that you're running is (as best as I can tell) about 3+ months old based on the traceback error in your logs. You need to update.

You also can't run nightly and be on master - the two are exclusive. You're either running nightly and tied to the python3-dev branch, or you're on master. If you're running nightly via docker, then you need to make sure in your config.ini that you set the ``git_branch = python3-dev`` so that it can properly display/check things.

As well, always post DEBUG level logs. If you don't know how to do that you can check the wiki here on github on how to enable debug logging in a docker environment.

And finally, DDL will experience hiccups / stalls / timeouts as that's just the nature of the beast (especially on Wednesday - Thursday). I saw a reference in your logs that it was queuing up in position #20 of your DDL queue - and if one of those items timeouts / stalls, then you need to either Restart the Queue, Restart the Download, or Abort the current download (all options available on the ``Manage`` / ``Manage DDL`` tab.  If you're using DDL, you need to check the Manage DDL page in order to see if any downloads have timed out / stalled / w/e - this is not something that's handled automatically by mylar (at least atm), it might be able to handle some of the timeouts, but some it can't recover from (because it uses http to download the files).

**Comment by CubeyGlyph** [comment]
> Firstly, - your version of Mylar that you're running is (as best as I can tell) about 3+ months old based on the traceback error in your logs. You need to update.
> 
> You also can't run nightly and be on master - the two are exclusive. You're either running nightly and tied to the python3-dev branch, or you're on master. If you're running nightly via docker, then you need to make sure in your config.ini that you set the `git_branch = python3-dev` so that it can properly display/check things.
> 
> As well, always post DEBUG level logs. If you don't know how to do that you can check the wiki here on github on how to enable debug logging in a docker environment.
> 
> And finally, DDL will experience hiccups / stalls / timeouts as that's just the nature of the beast (especially on Wednesday - Thursday). I saw a reference in your logs that it was queuing up in position #20 of your DDL queue - and if one of those items timeouts / stalls, then you need to either Restart the Queue, Restart the Download, or Abort the current download (all options available on the `Manage` / `Manage DDL` tab. If you're using DDL, you need to check the Manage DDL page in order to see if any downloads have timed out / stalled / w/e - this is not something that's handled automatically by mylar (at least atm), it might be able to handle some of the timeouts, but some it can't recover from (because it uses http to download the files).

I will get with the docker image creator to pass along the info regarding the version.  Thanks for the info on DDL management I will look to that.

**Comment by barbequesauce** [comment]
For what it's worth @CubeyGlyph - we worked with LinuxServer.io on their image, we would recommend theirs.

**Comment by CubeyGlyph** [comment]
> For what it's worth @CubeyGlyph - we worked with LinuxServer.io on their image, we would recommend theirs.

That is the one I am using.  Any suggestions for where to look next?  The Manage DDL tab actually lists all the "Snatched" items as completed, despite not being in cache or target location.  Attempts to retry looks like it is downloading again but results in the same issue.  

```
"Hostname": "c19a8fcebc36",
        "Image": "linuxserver/mylar3:nightly-version-a36c5bcf",
        "Labels": {
            "build_version": "Linuxserver.io version:- a36c5bcf-ls134 Build-date:- 2021-09-30T21:21:53+02:00",
            "maintainer": "aptalca",
            "org.opencontainers.image.authors": "linuxserver.io",
            "org.opencontainers.image.created": "2021-09-30T21:21:53+02:00",
            "org.opencontainers.image.description": "[Mylar3](https://github.com/mylar3/mylar3) is an automated Comic Book downloader (cbr/cbz) for use with NZB and torrents written in python. It supports SABnzbd, NZBGET, and many torrent clients in addition to DDL.",
            "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-mylar3",
            "org.opencontainers.image.licenses": "GPL-3.0-only",
            "org.opencontainers.image.ref.name": "51ed0a405e290e47b16144206ef0624a91efadb4",
            "org.opencontainers.image.revision": "51ed0a405e290e47b16144206ef0624a91efadb4",
            "org.opencontainers.image.source": "https://github.com/linuxserver/docker-mylar3",
            "org.opencontainers.image.title": "Mylar3",
            "org.opencontainers.image.url": "https://github.com/linuxserver/docker-mylar3/packages",
            "org.opencontainers.image.vendor": "linuxserver.io",
            "org.opencontainers.image.version": "a36c5bcf-ls134"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/comics": {},
            "/config": {},
            "/downloads": {}
        },
```

**Comment by barbequesauce** [comment]
That shows you're using a master release from 9/30. The current image is from November - maybe update?

![image](https://user-images.githubusercontent.com/25070944/147931694-f34fb683-d3ce-4347-8b7a-6c3f51c42b0e.jpeg)

**Comment by barbequesauce** [comment]
As noted in the lsio ticket - you're pinned to the earlier release and need to unpin then update.

Closing here as it's not a code issue but a portainer configuration issue.

**Comment by CubeyGlyph** [comment]
> As noted in the lsio ticket - you're pinned to the earlier release and need to unpin then update.
> 
> Closing here as it's not a code issue but a portainer configuration issue.

Thank you. I need to figure out why my update process is failing then.
