### ISSUE TITLE
Failed to convert cbr to cbz

### ISSUE THREAD

**Issue by Frankthetankk** [mylar3/mylar3#993]
**Describe the bug**
When I try to meta-tag an issue with a file name as cbz it works successfully, but when I try to meta-tag an issue with a file name as cbr I get this error.
`WARNING | [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /config/mylar/cache and/or the location where Mylar is trying to tag the files from.`

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/7803366/carepackage.zip)

**Environment (please complete the following information):**
 - Unraid Docker mylar3 linuxserver 
 - This may or may not be the correct commit #https://github.com/linuxserver/docker-mylar3/commit/b6fe57fc0fee574617d2bcf9bee454f83da7bdac
 - mylar3 #https://github.com/mylar3/mylar3/commit/d09a2cda7ad5877c89e4e35aef76c0b70cc99fd4

**Additional information**
I've copied my config.ini file from other successful mylar3 VM installs. Testing this docker with a single series. A mix of both cbr and cbz files. I've found some past github issues with a similar problem.
#https://github.com/evilhero/mylar/issues/1970 I checked my permissions, and I believe they're setup fine. I did check if I have `/usr/bin/unrar` installed, and I do. I don't have `/usr/bin/rar` installed. Far as I can tell, it's no longer downloadable. Or perhaps I don't know how to install it.
#https://github.com/evilhero/mylar/issues/1283 Kindof same problem.
#https://github.com/mylar3/mylar3/issues/425 latest and similar problem as mine
#https://github.com/linuxserver/docker-mylar3/issues/1 I believe I tried to "bash" into the docker and used `apk add --no-cache unrar` but it didn't fix it.
#https://github.com/mylar3/mylar3/pull/428 In my comictagger settings file I tried setting `rar_exe_path = /usr/bin/unrar`
#https://forum.mylarcomics.com/viewtopic.php?t=2245 I read this
#https://forum.mylarcomics.com/viewtopic.php?t=2320 I read this

**Comment by evilhero** [comment]
Can you try turning off enforce permissions and seeing if that fixes anything ?

You also have some kind of permissions/access related problem with your database file:
``02-Jan-2022 04:45:34 - ERROR   :: mylar.initialize.211 : MainThread : Cannot connect to the database: not enough values to unpack (expected 2, got 1)``
I'm getting database malformed errors whenever I try to load up the db that's included in your carepackage, which kinda of leads me to think that your db file is kinda messed up somehow.

**Comment by Frankthetankk** [comment]
[carepackage (1).zip](https://github.com/mylar3/mylar3/files/7812261/carepackage.1.zip)
I tried turning off enforce permissions, restarted the docker, but still get the same error. I next tried stopping the docker and deleted the mylar.db file. Started it without enforce permissions and got the same error. I restarted the docker with enforce permissions and got the same error.

**Comment by evilhero** [comment]
Is your comics folder local to the machine that's running mylar or is external ? 

Can you open the files that are having problems (the cbr ones) and view any of the images therein? 

Are the files that you're tagging copied into the cache folder at all? If they are, what files are still located in there after the error ? 

Typically 90% of the time with this particular error it's due to permissions - not saying that's what this is, cause at this point I'm not sure - but the user running mylar has to have full access to both the cache folder location and the comics location where your comics are stored. This is because it copies the file from your comic location into the cache folder into a temp directory called ``mylar_XXXXX`` where the XXXXXX is just some random alphanumerics. It then  unrar's the files and after it gets the info from CV it writes it all back into a zip file with the included metadata. It then copies the files back to the original location, deletes the original copy if applicable, and cleans up the temp files.

There's probably also no need to specify the ``rar_exe_path`` value in the .ComicTagger/settings file as you're running docker - the issue you linked to in the LSIO was when they didn't have the unrar binary included in their image, that was since changed so there's no need for you to do that (and specifying something outside of the given container might cause problems since docker is locked into certain paths, as that's the nature of docker).

**Comment by Frankthetankk** [comment]
Apologies for the delay. I believe my issue is fixed. Big thanks to you.
> Is your comics folder local to the machine that's running mylar or is external ?

Yes
> Can you open the files that are having problems (the cbr ones) and view any of the images therein?

No, I could not open the files having problems. How my problem got fixed was that I noticed that my cbr files had little to no KB in them. I marked each one as "failed" in mylar. The new files were downloaded as cbr and post-processed to cbz and moved to my comics folder successfully.
> Are the files that you're tagging copied into the cache folder at all? If they are, what files are still located in there after the error ?
I am not sure if the files get copied into the cache folder. The files leftover in cache are the nzb and the cover jpg files.
> Typically 90% of the time with this particular error it's due to permissions - not saying that's what this is, cause at this point I'm not sure - but the user running mylar has to have full access to both the cache folder location and the comics location where your comics are stored. This is because it copies the file from your comic location into the cache folder into a temp directory called `mylar_XXXXX` where the XXXXXX is just some random alphanumerics. It then unrar's the files and after it gets the info from CV it writes it all back into a zip file with the included metadata. It then copies the files back to the original location, deletes the original copy if applicable, and cleans up the temp files.
> 
> There's probably also no need to specify the `rar_exe_path` value in the .ComicTagger/settings file as you're running docker - the issue you linked to in the LSIO was when they didn't have the unrar binary included in their image, that was since changed so there's no need for you to do that (and specifying something outside of the given container might cause problems since docker is locked into certain paths, as that's the nature of docker).

I will remove this value. Thank you
